// Generated by runtime/generate-lwjgl2-bindings.py. Do not edit.
//
// LWJGL 2's ARBFramebufferObject. Every method forwards to LWJGL 3's binding of the same GL
// function, reached through the package the compatibility jar relocates
// LWJGL 3's OpenGL module into. The constants are LWJGL 2's own values.
package org.lwjgl.opengl;

public final class ARBFramebufferObject {

    public static final int GL_COLOR_ATTACHMENT0 = 0x8CE0;
    public static final int GL_COLOR_ATTACHMENT1 = 0x8CE1;
    public static final int GL_COLOR_ATTACHMENT10 = 0x8CEA;
    public static final int GL_COLOR_ATTACHMENT11 = 0x8CEB;
    public static final int GL_COLOR_ATTACHMENT12 = 0x8CEC;
    public static final int GL_COLOR_ATTACHMENT13 = 0x8CED;
    public static final int GL_COLOR_ATTACHMENT14 = 0x8CEE;
    public static final int GL_COLOR_ATTACHMENT15 = 0x8CEF;
    public static final int GL_COLOR_ATTACHMENT2 = 0x8CE2;
    public static final int GL_COLOR_ATTACHMENT3 = 0x8CE3;
    public static final int GL_COLOR_ATTACHMENT4 = 0x8CE4;
    public static final int GL_COLOR_ATTACHMENT5 = 0x8CE5;
    public static final int GL_COLOR_ATTACHMENT6 = 0x8CE6;
    public static final int GL_COLOR_ATTACHMENT7 = 0x8CE7;
    public static final int GL_COLOR_ATTACHMENT8 = 0x8CE8;
    public static final int GL_COLOR_ATTACHMENT9 = 0x8CE9;
    public static final int GL_DEPTH24_STENCIL8 = 0x88F0;
    public static final int GL_DEPTH_ATTACHMENT = 0x8D00;
    public static final int GL_DEPTH_STENCIL = 0x84F9;
    public static final int GL_DEPTH_STENCIL_ATTACHMENT = 0x821A;
    public static final int GL_DRAW_FRAMEBUFFER = 0x8CA9;
    public static final int GL_DRAW_FRAMEBUFFER_BINDING = 0x8CA6;
    public static final int GL_FRAMEBUFFER = 0x8D40;
    public static final int GL_FRAMEBUFFER_ATTACHMENT_ALPHA_SIZE = 0x8215;
    public static final int GL_FRAMEBUFFER_ATTACHMENT_BLUE_SIZE = 0x8214;
    public static final int GL_FRAMEBUFFER_ATTACHMENT_COLOR_ENCODING = 0x8210;
    public static final int GL_FRAMEBUFFER_ATTACHMENT_COMPONENT_TYPE = 0x8211;
    public static final int GL_FRAMEBUFFER_ATTACHMENT_DEPTH_SIZE = 0x8216;
    public static final int GL_FRAMEBUFFER_ATTACHMENT_GREEN_SIZE = 0x8213;
    public static final int GL_FRAMEBUFFER_ATTACHMENT_OBJECT_NAME = 0x8CD1;
    public static final int GL_FRAMEBUFFER_ATTACHMENT_OBJECT_TYPE = 0x8CD0;
    public static final int GL_FRAMEBUFFER_ATTACHMENT_RED_SIZE = 0x8212;
    public static final int GL_FRAMEBUFFER_ATTACHMENT_STENCIL_SIZE = 0x8217;
    public static final int GL_FRAMEBUFFER_ATTACHMENT_TEXTURE_CUBE_MAP_FACE = 0x8CD3;
    public static final int GL_FRAMEBUFFER_ATTACHMENT_TEXTURE_LAYER = 0x8CD4;
    public static final int GL_FRAMEBUFFER_ATTACHMENT_TEXTURE_LEVEL = 0x8CD2;
    public static final int GL_FRAMEBUFFER_BINDING = 0x8CA6;
    public static final int GL_FRAMEBUFFER_COMPLETE = 0x8CD5;
    public static final int GL_FRAMEBUFFER_DEFAULT = 0x8218;
    public static final int GL_FRAMEBUFFER_INCOMPLETE_ATTACHMENT = 0x8CD6;
    public static final int GL_FRAMEBUFFER_INCOMPLETE_DRAW_BUFFER = 0x8CDB;
    public static final int GL_FRAMEBUFFER_INCOMPLETE_MISSING_ATTACHMENT = 0x8CD7;
    public static final int GL_FRAMEBUFFER_INCOMPLETE_MULTISAMPLE = 0x8D56;
    public static final int GL_FRAMEBUFFER_INCOMPLETE_READ_BUFFER = 0x8CDC;
    public static final int GL_FRAMEBUFFER_UNDEFINED = 0x8219;
    public static final int GL_FRAMEBUFFER_UNSUPPORTED = 0x8CDD;
    public static final int GL_INDEX = 0x8222;
    public static final int GL_INVALID_FRAMEBUFFER_OPERATION = 0x506;
    public static final int GL_MAX_COLOR_ATTACHMENTS = 0x8CDF;
    public static final int GL_MAX_RENDERBUFFER_SIZE = 0x84E8;
    public static final int GL_MAX_SAMPLES = 0x8D57;
    public static final int GL_READ_FRAMEBUFFER = 0x8CA8;
    public static final int GL_READ_FRAMEBUFFER_BINDING = 0x8CAA;
    public static final int GL_RENDERBUFFER = 0x8D41;
    public static final int GL_RENDERBUFFER_ALPHA_SIZE = 0x8D53;
    public static final int GL_RENDERBUFFER_BINDING = 0x8CA7;
    public static final int GL_RENDERBUFFER_BLUE_SIZE = 0x8D52;
    public static final int GL_RENDERBUFFER_DEPTH_SIZE = 0x8D54;
    public static final int GL_RENDERBUFFER_GREEN_SIZE = 0x8D51;
    public static final int GL_RENDERBUFFER_HEIGHT = 0x8D43;
    public static final int GL_RENDERBUFFER_INTERNAL_FORMAT = 0x8D44;
    public static final int GL_RENDERBUFFER_RED_SIZE = 0x8D50;
    public static final int GL_RENDERBUFFER_SAMPLES = 0x8CAB;
    public static final int GL_RENDERBUFFER_STENCIL_SIZE = 0x8D55;
    public static final int GL_RENDERBUFFER_WIDTH = 0x8D42;
    public static final int GL_SRGB = 0x8C40;
    public static final int GL_STENCIL_ATTACHMENT = 0x8D20;
    public static final int GL_STENCIL_INDEX1 = 0x8D46;
    public static final int GL_STENCIL_INDEX16 = 0x8D49;
    public static final int GL_STENCIL_INDEX4 = 0x8D47;
    public static final int GL_STENCIL_INDEX8 = 0x8D48;
    public static final int GL_TEXTURE_STENCIL_SIZE = 0x88F1;
    public static final int GL_UNSIGNED_INT_24_8 = 0x84FA;
    public static final int GL_UNSIGNED_NORMALIZED = 0x8C17;

    public static void glBindFramebuffer(int p0, int p1) {
        com.github.lodestone.lwjgl3.opengl.ARBFramebufferObject.glBindFramebuffer(p0, p1);
    }

    public static void glBindRenderbuffer(int p0, int p1) {
        com.github.lodestone.lwjgl3.opengl.ARBFramebufferObject.glBindRenderbuffer(p0, p1);
    }

    public static void glBlitFramebuffer(int p0, int p1, int p2, int p3, int p4, int p5, int p6, int p7, int p8, int p9) {
        com.github.lodestone.lwjgl3.opengl.ARBFramebufferObject.glBlitFramebuffer(p0, p1, p2, p3, p4, p5, p6, p7, p8, p9);
    }

    public static int glCheckFramebufferStatus(int p0) {
        return com.github.lodestone.lwjgl3.opengl.ARBFramebufferObject.glCheckFramebufferStatus(p0);
    }

    public static void glDeleteFramebuffers(int p0) {
        com.github.lodestone.lwjgl3.opengl.ARBFramebufferObject.glDeleteFramebuffers(p0);
    }

    public static void glDeleteFramebuffers(java.nio.IntBuffer p0) {
        com.github.lodestone.lwjgl3.opengl.ARBFramebufferObject.glDeleteFramebuffers(p0);
    }

    public static void glDeleteRenderbuffers(int p0) {
        com.github.lodestone.lwjgl3.opengl.ARBFramebufferObject.glDeleteRenderbuffers(p0);
    }

    public static void glDeleteRenderbuffers(java.nio.IntBuffer p0) {
        com.github.lodestone.lwjgl3.opengl.ARBFramebufferObject.glDeleteRenderbuffers(p0);
    }

    public static void glFramebufferRenderbuffer(int p0, int p1, int p2, int p3) {
        com.github.lodestone.lwjgl3.opengl.ARBFramebufferObject.glFramebufferRenderbuffer(p0, p1, p2, p3);
    }

    public static void glFramebufferTexture1D(int p0, int p1, int p2, int p3, int p4) {
        com.github.lodestone.lwjgl3.opengl.ARBFramebufferObject.glFramebufferTexture1D(p0, p1, p2, p3, p4);
    }

    public static void glFramebufferTexture2D(int p0, int p1, int p2, int p3, int p4) {
        com.github.lodestone.lwjgl3.opengl.ARBFramebufferObject.glFramebufferTexture2D(p0, p1, p2, p3, p4);
    }

    public static void glFramebufferTexture3D(int p0, int p1, int p2, int p3, int p4, int p5) {
        com.github.lodestone.lwjgl3.opengl.ARBFramebufferObject.glFramebufferTexture3D(p0, p1, p2, p3, p4, p5);
    }

    public static void glFramebufferTextureLayer(int p0, int p1, int p2, int p3, int p4) {
        com.github.lodestone.lwjgl3.opengl.ARBFramebufferObject.glFramebufferTextureLayer(p0, p1, p2, p3, p4);
    }

    public static int glGenFramebuffers() {
        return com.github.lodestone.lwjgl3.opengl.ARBFramebufferObject.glGenFramebuffers();
    }

    public static void glGenFramebuffers(java.nio.IntBuffer p0) {
        com.github.lodestone.lwjgl3.opengl.ARBFramebufferObject.glGenFramebuffers(p0);
    }

    public static int glGenRenderbuffers() {
        return com.github.lodestone.lwjgl3.opengl.ARBFramebufferObject.glGenRenderbuffers();
    }

    public static void glGenRenderbuffers(java.nio.IntBuffer p0) {
        com.github.lodestone.lwjgl3.opengl.ARBFramebufferObject.glGenRenderbuffers(p0);
    }

    public static void glGenerateMipmap(int p0) {
        com.github.lodestone.lwjgl3.opengl.ARBFramebufferObject.glGenerateMipmap(p0);
    }

    public static void glGetFramebufferAttachmentParameter(int p0, int p1, int p2, java.nio.IntBuffer p3) {
        com.github.lodestone.lwjgl3.opengl.ARBFramebufferObject.glGetFramebufferAttachmentParameteriv(p0, p1, p2, p3);
    }

    public static int glGetFramebufferAttachmentParameteri(int p0, int p1, int p2) {
        return com.github.lodestone.lwjgl3.opengl.ARBFramebufferObject.glGetFramebufferAttachmentParameteri(p0, p1, p2);
    }

    public static void glGetRenderbufferParameter(int p0, int p1, java.nio.IntBuffer p2) {
        com.github.lodestone.lwjgl3.opengl.ARBFramebufferObject.glGetRenderbufferParameteriv(p0, p1, p2);
    }

    public static int glGetRenderbufferParameteri(int p0, int p1) {
        return com.github.lodestone.lwjgl3.opengl.ARBFramebufferObject.glGetRenderbufferParameteri(p0, p1);
    }

    public static boolean glIsFramebuffer(int p0) {
        return com.github.lodestone.lwjgl3.opengl.ARBFramebufferObject.glIsFramebuffer(p0);
    }

    public static boolean glIsRenderbuffer(int p0) {
        return com.github.lodestone.lwjgl3.opengl.ARBFramebufferObject.glIsRenderbuffer(p0);
    }

    public static void glRenderbufferStorage(int p0, int p1, int p2, int p3) {
        com.github.lodestone.lwjgl3.opengl.ARBFramebufferObject.glRenderbufferStorage(p0, p1, p2, p3);
    }

    public static void glRenderbufferStorageMultisample(int p0, int p1, int p2, int p3, int p4) {
        com.github.lodestone.lwjgl3.opengl.ARBFramebufferObject.glRenderbufferStorageMultisample(p0, p1, p2, p3, p4);
    }

    private ARBFramebufferObject() {
    }
}
