// Generated by runtime/generate-lwjgl2-bindings.py. Do not edit.
//
// LWJGL 2's ARBMultitexture. Every method forwards to LWJGL 3's binding of the same GL
// function, reached through the package the compatibility jar relocates
// LWJGL 3's OpenGL module into. The constants are LWJGL 2's own values.
package org.lwjgl.opengl;

public final class ARBMultitexture {

    public static final int GL_ACTIVE_TEXTURE_ARB = 0x84E0;
    public static final int GL_CLIENT_ACTIVE_TEXTURE_ARB = 0x84E1;
    public static final int GL_MAX_TEXTURE_UNITS_ARB = 0x84E2;
    public static final int GL_TEXTURE0_ARB = 0x84C0;
    public static final int GL_TEXTURE10_ARB = 0x84CA;
    public static final int GL_TEXTURE11_ARB = 0x84CB;
    public static final int GL_TEXTURE12_ARB = 0x84CC;
    public static final int GL_TEXTURE13_ARB = 0x84CD;
    public static final int GL_TEXTURE14_ARB = 0x84CE;
    public static final int GL_TEXTURE15_ARB = 0x84CF;
    public static final int GL_TEXTURE16_ARB = 0x84D0;
    public static final int GL_TEXTURE17_ARB = 0x84D1;
    public static final int GL_TEXTURE18_ARB = 0x84D2;
    public static final int GL_TEXTURE19_ARB = 0x84D3;
    public static final int GL_TEXTURE1_ARB = 0x84C1;
    public static final int GL_TEXTURE20_ARB = 0x84D4;
    public static final int GL_TEXTURE21_ARB = 0x84D5;
    public static final int GL_TEXTURE22_ARB = 0x84D6;
    public static final int GL_TEXTURE23_ARB = 0x84D7;
    public static final int GL_TEXTURE24_ARB = 0x84D8;
    public static final int GL_TEXTURE25_ARB = 0x84D9;
    public static final int GL_TEXTURE26_ARB = 0x84DA;
    public static final int GL_TEXTURE27_ARB = 0x84DB;
    public static final int GL_TEXTURE28_ARB = 0x84DC;
    public static final int GL_TEXTURE29_ARB = 0x84DD;
    public static final int GL_TEXTURE2_ARB = 0x84C2;
    public static final int GL_TEXTURE30_ARB = 0x84DE;
    public static final int GL_TEXTURE31_ARB = 0x84DF;
    public static final int GL_TEXTURE3_ARB = 0x84C3;
    public static final int GL_TEXTURE4_ARB = 0x84C4;
    public static final int GL_TEXTURE5_ARB = 0x84C5;
    public static final int GL_TEXTURE6_ARB = 0x84C6;
    public static final int GL_TEXTURE7_ARB = 0x84C7;
    public static final int GL_TEXTURE8_ARB = 0x84C8;
    public static final int GL_TEXTURE9_ARB = 0x84C9;

    public static void glActiveTextureARB(int p0) {
        com.github.lodestone.lwjgl3.opengl.ARBMultitexture.glActiveTextureARB(p0);
    }

    public static void glClientActiveTextureARB(int p0) {
        com.github.lodestone.lwjgl3.opengl.ARBMultitexture.glClientActiveTextureARB(p0);
    }

    public static void glMultiTexCoord1dARB(int p0, double p1) {
        com.github.lodestone.lwjgl3.opengl.ARBMultitexture.glMultiTexCoord1dARB(p0, p1);
    }

    public static void glMultiTexCoord1fARB(int p0, float p1) {
        com.github.lodestone.lwjgl3.opengl.ARBMultitexture.glMultiTexCoord1fARB(p0, p1);
    }

    public static void glMultiTexCoord1iARB(int p0, int p1) {
        com.github.lodestone.lwjgl3.opengl.ARBMultitexture.glMultiTexCoord1iARB(p0, p1);
    }

    public static void glMultiTexCoord1sARB(int p0, short p1) {
        com.github.lodestone.lwjgl3.opengl.ARBMultitexture.glMultiTexCoord1sARB(p0, p1);
    }

    public static void glMultiTexCoord2dARB(int p0, double p1, double p2) {
        com.github.lodestone.lwjgl3.opengl.ARBMultitexture.glMultiTexCoord2dARB(p0, p1, p2);
    }

    public static void glMultiTexCoord2fARB(int p0, float p1, float p2) {
        com.github.lodestone.lwjgl3.opengl.ARBMultitexture.glMultiTexCoord2fARB(p0, p1, p2);
    }

    public static void glMultiTexCoord2iARB(int p0, int p1, int p2) {
        com.github.lodestone.lwjgl3.opengl.ARBMultitexture.glMultiTexCoord2iARB(p0, p1, p2);
    }

    public static void glMultiTexCoord2sARB(int p0, short p1, short p2) {
        com.github.lodestone.lwjgl3.opengl.ARBMultitexture.glMultiTexCoord2sARB(p0, p1, p2);
    }

    public static void glMultiTexCoord3dARB(int p0, double p1, double p2, double p3) {
        com.github.lodestone.lwjgl3.opengl.ARBMultitexture.glMultiTexCoord3dARB(p0, p1, p2, p3);
    }

    public static void glMultiTexCoord3fARB(int p0, float p1, float p2, float p3) {
        com.github.lodestone.lwjgl3.opengl.ARBMultitexture.glMultiTexCoord3fARB(p0, p1, p2, p3);
    }

    public static void glMultiTexCoord3iARB(int p0, int p1, int p2, int p3) {
        com.github.lodestone.lwjgl3.opengl.ARBMultitexture.glMultiTexCoord3iARB(p0, p1, p2, p3);
    }

    public static void glMultiTexCoord3sARB(int p0, short p1, short p2, short p3) {
        com.github.lodestone.lwjgl3.opengl.ARBMultitexture.glMultiTexCoord3sARB(p0, p1, p2, p3);
    }

    public static void glMultiTexCoord4dARB(int p0, double p1, double p2, double p3, double p4) {
        com.github.lodestone.lwjgl3.opengl.ARBMultitexture.glMultiTexCoord4dARB(p0, p1, p2, p3, p4);
    }

    public static void glMultiTexCoord4fARB(int p0, float p1, float p2, float p3, float p4) {
        com.github.lodestone.lwjgl3.opengl.ARBMultitexture.glMultiTexCoord4fARB(p0, p1, p2, p3, p4);
    }

    public static void glMultiTexCoord4iARB(int p0, int p1, int p2, int p3, int p4) {
        com.github.lodestone.lwjgl3.opengl.ARBMultitexture.glMultiTexCoord4iARB(p0, p1, p2, p3, p4);
    }

    public static void glMultiTexCoord4sARB(int p0, short p1, short p2, short p3, short p4) {
        com.github.lodestone.lwjgl3.opengl.ARBMultitexture.glMultiTexCoord4sARB(p0, p1, p2, p3, p4);
    }

    private ARBMultitexture() {
    }
}
