// Generated by runtime/generate-lwjgl2-bindings.py. Do not edit.
//
// LWJGL 2's ARBOcclusionQuery. Every method forwards to LWJGL 3's binding of the same GL
// function, reached through the package the compatibility jar relocates
// LWJGL 3's OpenGL module into. The constants are LWJGL 2's own values.
package org.lwjgl.opengl;

public final class ARBOcclusionQuery {

    public static final int GL_CURRENT_QUERY_ARB = 0x8865;
    public static final int GL_QUERY_COUNTER_BITS_ARB = 0x8864;
    public static final int GL_QUERY_RESULT_ARB = 0x8866;
    public static final int GL_QUERY_RESULT_AVAILABLE_ARB = 0x8867;
    public static final int GL_SAMPLES_PASSED_ARB = 0x8914;

    public static void glBeginQueryARB(int p0, int p1) {
        com.github.lodestone.lwjgl3.opengl.ARBOcclusionQuery.glBeginQueryARB(p0, p1);
    }

    public static void glDeleteQueriesARB(int p0) {
        com.github.lodestone.lwjgl3.opengl.ARBOcclusionQuery.glDeleteQueriesARB(p0);
    }

    public static void glDeleteQueriesARB(java.nio.IntBuffer p0) {
        com.github.lodestone.lwjgl3.opengl.ARBOcclusionQuery.glDeleteQueriesARB(p0);
    }

    public static void glEndQueryARB(int p0) {
        com.github.lodestone.lwjgl3.opengl.ARBOcclusionQuery.glEndQueryARB(p0);
    }

    public static int glGenQueriesARB() {
        return com.github.lodestone.lwjgl3.opengl.ARBOcclusionQuery.glGenQueriesARB();
    }

    public static void glGenQueriesARB(java.nio.IntBuffer p0) {
        com.github.lodestone.lwjgl3.opengl.ARBOcclusionQuery.glGenQueriesARB(p0);
    }

    public static void glGetQueryARB(int p0, int p1, java.nio.IntBuffer p2) {
        com.github.lodestone.lwjgl3.opengl.ARBOcclusionQuery.glGetQueryivARB(p0, p1, p2);
    }

    public static void glGetQueryObjectARB(int p0, int p1, java.nio.IntBuffer p2) {
        com.github.lodestone.lwjgl3.opengl.ARBOcclusionQuery.glGetQueryObjectivARB(p0, p1, p2);
    }

    public static int glGetQueryObjectiARB(int p0, int p1) {
        return com.github.lodestone.lwjgl3.opengl.ARBOcclusionQuery.glGetQueryObjectiARB(p0, p1);
    }

    public static void glGetQueryObjectuARB(int p0, int p1, java.nio.IntBuffer p2) {
        com.github.lodestone.lwjgl3.opengl.ARBOcclusionQuery.glGetQueryObjectuivARB(p0, p1, p2);
    }

    public static int glGetQueryObjectuiARB(int p0, int p1) {
        return com.github.lodestone.lwjgl3.opengl.ARBOcclusionQuery.glGetQueryObjectuiARB(p0, p1);
    }

    public static int glGetQueryiARB(int p0, int p1) {
        return com.github.lodestone.lwjgl3.opengl.ARBOcclusionQuery.glGetQueryiARB(p0, p1);
    }

    public static boolean glIsQueryARB(int p0) {
        return com.github.lodestone.lwjgl3.opengl.ARBOcclusionQuery.glIsQueryARB(p0);
    }

    private ARBOcclusionQuery() {
    }
}
