// Generated by runtime/generate-lwjgl2-bindings.py. Do not edit.
//
// LWJGL 2's ARBShaderObjects. Every method forwards to LWJGL 3's binding of the same GL
// function, reached through the package the compatibility jar relocates
// LWJGL 3's OpenGL module into. The constants are LWJGL 2's own values.
package org.lwjgl.opengl;

public final class ARBShaderObjects {

    public static final int GL_BOOL_ARB = 0x8B56;
    public static final int GL_BOOL_VEC2_ARB = 0x8B57;
    public static final int GL_BOOL_VEC3_ARB = 0x8B58;
    public static final int GL_BOOL_VEC4_ARB = 0x8B59;
    public static final int GL_FLOAT_MAT2_ARB = 0x8B5A;
    public static final int GL_FLOAT_MAT3_ARB = 0x8B5B;
    public static final int GL_FLOAT_MAT4_ARB = 0x8B5C;
    public static final int GL_FLOAT_VEC2_ARB = 0x8B50;
    public static final int GL_FLOAT_VEC3_ARB = 0x8B51;
    public static final int GL_FLOAT_VEC4_ARB = 0x8B52;
    public static final int GL_INT_VEC2_ARB = 0x8B53;
    public static final int GL_INT_VEC3_ARB = 0x8B54;
    public static final int GL_INT_VEC4_ARB = 0x8B55;
    public static final int GL_OBJECT_ACTIVE_UNIFORMS_ARB = 0x8B86;
    public static final int GL_OBJECT_ACTIVE_UNIFORM_MAX_LENGTH_ARB = 0x8B87;
    public static final int GL_OBJECT_ATTACHED_OBJECTS_ARB = 0x8B85;
    public static final int GL_OBJECT_COMPILE_STATUS_ARB = 0x8B81;
    public static final int GL_OBJECT_DELETE_STATUS_ARB = 0x8B80;
    public static final int GL_OBJECT_INFO_LOG_LENGTH_ARB = 0x8B84;
    public static final int GL_OBJECT_LINK_STATUS_ARB = 0x8B82;
    public static final int GL_OBJECT_SHADER_SOURCE_LENGTH_ARB = 0x8B88;
    public static final int GL_OBJECT_SUBTYPE_ARB = 0x8B4F;
    public static final int GL_OBJECT_TYPE_ARB = 0x8B4E;
    public static final int GL_OBJECT_VALIDATE_STATUS_ARB = 0x8B83;
    public static final int GL_PROGRAM_OBJECT_ARB = 0x8B40;
    public static final int GL_SAMPLER_1D_ARB = 0x8B5D;
    public static final int GL_SAMPLER_1D_SHADOW_ARB = 0x8B61;
    public static final int GL_SAMPLER_2D_ARB = 0x8B5E;
    public static final int GL_SAMPLER_2D_RECT_ARB = 0x8B63;
    public static final int GL_SAMPLER_2D_RECT_SHADOW_ARB = 0x8B64;
    public static final int GL_SAMPLER_2D_SHADOW_ARB = 0x8B62;
    public static final int GL_SAMPLER_3D_ARB = 0x8B5F;
    public static final int GL_SAMPLER_CUBE_ARB = 0x8B60;
    public static final int GL_SHADER_OBJECT_ARB = 0x8B48;

    public static void glAttachObjectARB(int p0, int p1) {
        com.github.lodestone.lwjgl3.opengl.ARBShaderObjects.glAttachObjectARB(p0, p1);
    }

    public static void glCompileShaderARB(int p0) {
        com.github.lodestone.lwjgl3.opengl.ARBShaderObjects.glCompileShaderARB(p0);
    }

    public static int glCreateProgramObjectARB() {
        return com.github.lodestone.lwjgl3.opengl.ARBShaderObjects.glCreateProgramObjectARB();
    }

    public static int glCreateShaderObjectARB(int p0) {
        return com.github.lodestone.lwjgl3.opengl.ARBShaderObjects.glCreateShaderObjectARB(p0);
    }

    public static void glDeleteObjectARB(int p0) {
        com.github.lodestone.lwjgl3.opengl.ARBShaderObjects.glDeleteObjectARB(p0);
    }

    public static void glDetachObjectARB(int p0, int p1) {
        com.github.lodestone.lwjgl3.opengl.ARBShaderObjects.glDetachObjectARB(p0, p1);
    }

    public static void glGetActiveUniformARB(int p0, int p1, java.nio.IntBuffer p2, java.nio.IntBuffer p3, java.nio.IntBuffer p4, java.nio.ByteBuffer p5) {
        com.github.lodestone.lwjgl3.opengl.ARBShaderObjects.glGetActiveUniformARB(p0, p1, p2, p3, p4, p5);
    }

    public static void glGetAttachedObjectsARB(int p0, java.nio.IntBuffer p1, java.nio.IntBuffer p2) {
        com.github.lodestone.lwjgl3.opengl.ARBShaderObjects.glGetAttachedObjectsARB(p0, p1, p2);
    }

    public static int glGetHandleARB(int p0) {
        return com.github.lodestone.lwjgl3.opengl.ARBShaderObjects.glGetHandleARB(p0);
    }

    public static java.lang.String glGetInfoLogARB(int p0, int p1) {
        return com.github.lodestone.lwjgl3.opengl.ARBShaderObjects.glGetInfoLogARB(p0, p1);
    }

    public static void glGetInfoLogARB(int p0, java.nio.IntBuffer p1, java.nio.ByteBuffer p2) {
        com.github.lodestone.lwjgl3.opengl.ARBShaderObjects.glGetInfoLogARB(p0, p1, p2);
    }

    public static void glGetObjectParameterARB(int p0, int p1, java.nio.FloatBuffer p2) {
        com.github.lodestone.lwjgl3.opengl.ARBShaderObjects.glGetObjectParameterfvARB(p0, p1, p2);
    }

    public static void glGetObjectParameterARB(int p0, int p1, java.nio.IntBuffer p2) {
        com.github.lodestone.lwjgl3.opengl.ARBShaderObjects.glGetObjectParameterivARB(p0, p1, p2);
    }

    public static int glGetObjectParameteriARB(int p0, int p1) {
        return com.github.lodestone.lwjgl3.opengl.ARBShaderObjects.glGetObjectParameteriARB(p0, p1);
    }

    public static java.lang.String glGetShaderSourceARB(int p0, int p1) {
        return com.github.lodestone.lwjgl3.opengl.ARBShaderObjects.glGetShaderSourceARB(p0, p1);
    }

    public static void glGetShaderSourceARB(int p0, java.nio.IntBuffer p1, java.nio.ByteBuffer p2) {
        com.github.lodestone.lwjgl3.opengl.ARBShaderObjects.glGetShaderSourceARB(p0, p1, p2);
    }

    public static void glGetUniformARB(int p0, int p1, java.nio.FloatBuffer p2) {
        com.github.lodestone.lwjgl3.opengl.ARBShaderObjects.glGetUniformfvARB(p0, p1, p2);
    }

    public static void glGetUniformARB(int p0, int p1, java.nio.IntBuffer p2) {
        com.github.lodestone.lwjgl3.opengl.ARBShaderObjects.glGetUniformivARB(p0, p1, p2);
    }

    public static int glGetUniformLocationARB(int p0, java.lang.CharSequence p1) {
        return com.github.lodestone.lwjgl3.opengl.ARBShaderObjects.glGetUniformLocationARB(p0, p1);
    }

    public static int glGetUniformLocationARB(int p0, java.nio.ByteBuffer p1) {
        return com.github.lodestone.lwjgl3.opengl.ARBShaderObjects.glGetUniformLocationARB(p0, p1);
    }

    public static void glLinkProgramARB(int p0) {
        com.github.lodestone.lwjgl3.opengl.ARBShaderObjects.glLinkProgramARB(p0);
    }

    public static void glShaderSourceARB(int p0, java.lang.CharSequence p1) {
        com.github.lodestone.lwjgl3.opengl.ARBShaderObjects.glShaderSourceARB(p0, p1);
    }

    public static void glShaderSourceARB(int p0, java.nio.ByteBuffer p1) {
        com.github.lodestone.lwjgl3.opengl.ARBShaderObjects.glShaderSourceARB(p0, org.lwjgl.system.MemoryUtil.memUTF8(p1.duplicate()));
    }

    public static void glShaderSourceARB(int p0, java.lang.CharSequence[] p1) {
        com.github.lodestone.lwjgl3.opengl.ARBShaderObjects.glShaderSourceARB(p0, p1);
    }

    public static void glUniform1ARB(int p0, java.nio.FloatBuffer p1) {
        com.github.lodestone.lwjgl3.opengl.ARBShaderObjects.glUniform1fvARB(p0, p1);
    }

    public static void glUniform1ARB(int p0, java.nio.IntBuffer p1) {
        com.github.lodestone.lwjgl3.opengl.ARBShaderObjects.glUniform1ivARB(p0, p1);
    }

    public static void glUniform1fARB(int p0, float p1) {
        com.github.lodestone.lwjgl3.opengl.ARBShaderObjects.glUniform1fARB(p0, p1);
    }

    public static void glUniform1iARB(int p0, int p1) {
        com.github.lodestone.lwjgl3.opengl.ARBShaderObjects.glUniform1iARB(p0, p1);
    }

    public static void glUniform2ARB(int p0, java.nio.FloatBuffer p1) {
        com.github.lodestone.lwjgl3.opengl.ARBShaderObjects.glUniform2fvARB(p0, p1);
    }

    public static void glUniform2ARB(int p0, java.nio.IntBuffer p1) {
        com.github.lodestone.lwjgl3.opengl.ARBShaderObjects.glUniform2ivARB(p0, p1);
    }

    public static void glUniform2fARB(int p0, float p1, float p2) {
        com.github.lodestone.lwjgl3.opengl.ARBShaderObjects.glUniform2fARB(p0, p1, p2);
    }

    public static void glUniform2iARB(int p0, int p1, int p2) {
        com.github.lodestone.lwjgl3.opengl.ARBShaderObjects.glUniform2iARB(p0, p1, p2);
    }

    public static void glUniform3ARB(int p0, java.nio.FloatBuffer p1) {
        com.github.lodestone.lwjgl3.opengl.ARBShaderObjects.glUniform3fvARB(p0, p1);
    }

    public static void glUniform3ARB(int p0, java.nio.IntBuffer p1) {
        com.github.lodestone.lwjgl3.opengl.ARBShaderObjects.glUniform3ivARB(p0, p1);
    }

    public static void glUniform3fARB(int p0, float p1, float p2, float p3) {
        com.github.lodestone.lwjgl3.opengl.ARBShaderObjects.glUniform3fARB(p0, p1, p2, p3);
    }

    public static void glUniform3iARB(int p0, int p1, int p2, int p3) {
        com.github.lodestone.lwjgl3.opengl.ARBShaderObjects.glUniform3iARB(p0, p1, p2, p3);
    }

    public static void glUniform4ARB(int p0, java.nio.FloatBuffer p1) {
        com.github.lodestone.lwjgl3.opengl.ARBShaderObjects.glUniform4fvARB(p0, p1);
    }

    public static void glUniform4ARB(int p0, java.nio.IntBuffer p1) {
        com.github.lodestone.lwjgl3.opengl.ARBShaderObjects.glUniform4ivARB(p0, p1);
    }

    public static void glUniform4fARB(int p0, float p1, float p2, float p3, float p4) {
        com.github.lodestone.lwjgl3.opengl.ARBShaderObjects.glUniform4fARB(p0, p1, p2, p3, p4);
    }

    public static void glUniform4iARB(int p0, int p1, int p2, int p3, int p4) {
        com.github.lodestone.lwjgl3.opengl.ARBShaderObjects.glUniform4iARB(p0, p1, p2, p3, p4);
    }

    public static void glUniformMatrix2ARB(int p0, boolean p1, java.nio.FloatBuffer p2) {
        com.github.lodestone.lwjgl3.opengl.ARBShaderObjects.glUniformMatrix2fvARB(p0, p1, p2);
    }

    public static void glUniformMatrix3ARB(int p0, boolean p1, java.nio.FloatBuffer p2) {
        com.github.lodestone.lwjgl3.opengl.ARBShaderObjects.glUniformMatrix3fvARB(p0, p1, p2);
    }

    public static void glUniformMatrix4ARB(int p0, boolean p1, java.nio.FloatBuffer p2) {
        com.github.lodestone.lwjgl3.opengl.ARBShaderObjects.glUniformMatrix4fvARB(p0, p1, p2);
    }

    public static void glUseProgramObjectARB(int p0) {
        com.github.lodestone.lwjgl3.opengl.ARBShaderObjects.glUseProgramObjectARB(p0);
    }

    public static void glValidateProgramARB(int p0) {
        com.github.lodestone.lwjgl3.opengl.ARBShaderObjects.glValidateProgramARB(p0);
    }

    private ARBShaderObjects() {
    }
}
