// Generated by runtime/generate-lwjgl2-bindings.py. Do not edit.
//
// LWJGL 2's ARBTextureFloat. Every method forwards to LWJGL 3's binding of the same GL
// function, reached through the package the compatibility jar relocates
// LWJGL 3's OpenGL module into. The constants are LWJGL 2's own values.
package org.lwjgl.opengl;

public final class ARBTextureFloat {

    public static final int GL_ALPHA16F_ARB = 0x881C;
    public static final int GL_ALPHA32F_ARB = 0x8816;
    public static final int GL_INTENSITY16F_ARB = 0x881D;
    public static final int GL_INTENSITY32F_ARB = 0x8817;
    public static final int GL_LUMINANCE16F_ARB = 0x881E;
    public static final int GL_LUMINANCE32F_ARB = 0x8818;
    public static final int GL_LUMINANCE_ALPHA16F_ARB = 0x881F;
    public static final int GL_LUMINANCE_ALPHA32F_ARB = 0x8819;
    public static final int GL_RGB16F_ARB = 0x881B;
    public static final int GL_RGB32F_ARB = 0x8815;
    public static final int GL_RGBA16F_ARB = 0x881A;
    public static final int GL_RGBA32F_ARB = 0x8814;
    public static final int GL_TEXTURE_ALPHA_TYPE_ARB = 0x8C13;
    public static final int GL_TEXTURE_BLUE_TYPE_ARB = 0x8C12;
    public static final int GL_TEXTURE_DEPTH_TYPE_ARB = 0x8C16;
    public static final int GL_TEXTURE_GREEN_TYPE_ARB = 0x8C11;
    public static final int GL_TEXTURE_INTENSITY_TYPE_ARB = 0x8C15;
    public static final int GL_TEXTURE_LUMINANCE_TYPE_ARB = 0x8C14;
    public static final int GL_TEXTURE_RED_TYPE_ARB = 0x8C10;
    public static final int GL_UNSIGNED_NORMALIZED_ARB = 0x8C17;

    private ARBTextureFloat() {
    }
}
