// Generated by runtime/generate-lwjgl2-bindings.py. Do not edit.
//
// LWJGL 2's ARBVertexShader. Every method forwards to LWJGL 3's binding of the same GL
// function, reached through the package the compatibility jar relocates
// LWJGL 3's OpenGL module into. The constants are LWJGL 2's own values.
package org.lwjgl.opengl;

public final class ARBVertexShader {

    public static final int GL_CURRENT_VERTEX_ATTRIB_ARB = 0x8626;
    public static final int GL_FLOAT_MAT2_ARB = 0x8B5A;
    public static final int GL_FLOAT_MAT3_ARB = 0x8B5B;
    public static final int GL_FLOAT_MAT4_ARB = 0x8B5C;
    public static final int GL_FLOAT_VEC2_ARB = 0x8B50;
    public static final int GL_FLOAT_VEC3_ARB = 0x8B51;
    public static final int GL_FLOAT_VEC4_ARB = 0x8B52;
    public static final int GL_MAX_COMBINED_TEXTURE_IMAGE_UNITS_ARB = 0x8B4D;
    public static final int GL_MAX_TEXTURE_COORDS_ARB = 0x8871;
    public static final int GL_MAX_TEXTURE_IMAGE_UNITS_ARB = 0x8872;
    public static final int GL_MAX_VARYING_FLOATS_ARB = 0x8B4B;
    public static final int GL_MAX_VERTEX_ATTRIBS_ARB = 0x8869;
    public static final int GL_MAX_VERTEX_TEXTURE_IMAGE_UNITS_ARB = 0x8B4C;
    public static final int GL_MAX_VERTEX_UNIFORM_COMPONENTS_ARB = 0x8B4A;
    public static final int GL_OBJECT_ACTIVE_ATTRIBUTES_ARB = 0x8B89;
    public static final int GL_OBJECT_ACTIVE_ATTRIBUTE_MAX_LENGTH_ARB = 0x8B8A;
    public static final int GL_VERTEX_ATTRIB_ARRAY_ENABLED_ARB = 0x8622;
    public static final int GL_VERTEX_ATTRIB_ARRAY_NORMALIZED_ARB = 0x886A;
    public static final int GL_VERTEX_ATTRIB_ARRAY_POINTER_ARB = 0x8645;
    public static final int GL_VERTEX_ATTRIB_ARRAY_SIZE_ARB = 0x8623;
    public static final int GL_VERTEX_ATTRIB_ARRAY_STRIDE_ARB = 0x8624;
    public static final int GL_VERTEX_ATTRIB_ARRAY_TYPE_ARB = 0x8625;
    public static final int GL_VERTEX_PROGRAM_POINT_SIZE_ARB = 0x8642;
    public static final int GL_VERTEX_PROGRAM_TWO_SIDE_ARB = 0x8643;
    public static final int GL_VERTEX_SHADER_ARB = 0x8B31;

    public static void glBindAttribLocationARB(int p0, int p1, java.lang.CharSequence p2) {
        com.github.lodestone.lwjgl3.opengl.ARBVertexShader.glBindAttribLocationARB(p0, p1, p2);
    }

    public static void glBindAttribLocationARB(int p0, int p1, java.nio.ByteBuffer p2) {
        com.github.lodestone.lwjgl3.opengl.ARBVertexShader.glBindAttribLocationARB(p0, p1, p2);
    }

    public static void glDisableVertexAttribArrayARB(int p0) {
        com.github.lodestone.lwjgl3.opengl.ARBVertexShader.glDisableVertexAttribArrayARB(p0);
    }

    public static void glEnableVertexAttribArrayARB(int p0) {
        com.github.lodestone.lwjgl3.opengl.ARBVertexShader.glEnableVertexAttribArrayARB(p0);
    }

    public static void glGetActiveAttribARB(int p0, int p1, java.nio.IntBuffer p2, java.nio.IntBuffer p3, java.nio.IntBuffer p4, java.nio.ByteBuffer p5) {
        com.github.lodestone.lwjgl3.opengl.ARBVertexShader.glGetActiveAttribARB(p0, p1, p2, p3, p4, p5);
    }

    public static int glGetAttribLocationARB(int p0, java.lang.CharSequence p1) {
        return com.github.lodestone.lwjgl3.opengl.ARBVertexShader.glGetAttribLocationARB(p0, p1);
    }

    public static int glGetAttribLocationARB(int p0, java.nio.ByteBuffer p1) {
        return com.github.lodestone.lwjgl3.opengl.ARBVertexShader.glGetAttribLocationARB(p0, p1);
    }

    public static void glGetVertexAttribARB(int p0, int p1, java.nio.DoubleBuffer p2) {
        com.github.lodestone.lwjgl3.opengl.ARBVertexShader.glGetVertexAttribdvARB(p0, p1, p2);
    }

    public static void glGetVertexAttribARB(int p0, int p1, java.nio.FloatBuffer p2) {
        com.github.lodestone.lwjgl3.opengl.ARBVertexShader.glGetVertexAttribfvARB(p0, p1, p2);
    }

    public static void glGetVertexAttribARB(int p0, int p1, java.nio.IntBuffer p2) {
        com.github.lodestone.lwjgl3.opengl.ARBVertexShader.glGetVertexAttribivARB(p0, p1, p2);
    }

    public static void glVertexAttrib1dARB(int p0, double p1) {
        com.github.lodestone.lwjgl3.opengl.ARBVertexShader.glVertexAttrib1dARB(p0, p1);
    }

    public static void glVertexAttrib1fARB(int p0, float p1) {
        com.github.lodestone.lwjgl3.opengl.ARBVertexShader.glVertexAttrib1fARB(p0, p1);
    }

    public static void glVertexAttrib1sARB(int p0, short p1) {
        com.github.lodestone.lwjgl3.opengl.ARBVertexShader.glVertexAttrib1sARB(p0, p1);
    }

    public static void glVertexAttrib2dARB(int p0, double p1, double p2) {
        com.github.lodestone.lwjgl3.opengl.ARBVertexShader.glVertexAttrib2dARB(p0, p1, p2);
    }

    public static void glVertexAttrib2fARB(int p0, float p1, float p2) {
        com.github.lodestone.lwjgl3.opengl.ARBVertexShader.glVertexAttrib2fARB(p0, p1, p2);
    }

    public static void glVertexAttrib2sARB(int p0, short p1, short p2) {
        com.github.lodestone.lwjgl3.opengl.ARBVertexShader.glVertexAttrib2sARB(p0, p1, p2);
    }

    public static void glVertexAttrib3dARB(int p0, double p1, double p2, double p3) {
        com.github.lodestone.lwjgl3.opengl.ARBVertexShader.glVertexAttrib3dARB(p0, p1, p2, p3);
    }

    public static void glVertexAttrib3fARB(int p0, float p1, float p2, float p3) {
        com.github.lodestone.lwjgl3.opengl.ARBVertexShader.glVertexAttrib3fARB(p0, p1, p2, p3);
    }

    public static void glVertexAttrib3sARB(int p0, short p1, short p2, short p3) {
        com.github.lodestone.lwjgl3.opengl.ARBVertexShader.glVertexAttrib3sARB(p0, p1, p2, p3);
    }

    public static void glVertexAttrib4NubARB(int p0, byte p1, byte p2, byte p3, byte p4) {
        com.github.lodestone.lwjgl3.opengl.ARBVertexShader.glVertexAttrib4NubARB(p0, p1, p2, p3, p4);
    }

    public static void glVertexAttrib4dARB(int p0, double p1, double p2, double p3, double p4) {
        com.github.lodestone.lwjgl3.opengl.ARBVertexShader.glVertexAttrib4dARB(p0, p1, p2, p3, p4);
    }

    public static void glVertexAttrib4fARB(int p0, float p1, float p2, float p3, float p4) {
        com.github.lodestone.lwjgl3.opengl.ARBVertexShader.glVertexAttrib4fARB(p0, p1, p2, p3, p4);
    }

    public static void glVertexAttrib4sARB(int p0, short p1, short p2, short p3, short p4) {
        com.github.lodestone.lwjgl3.opengl.ARBVertexShader.glVertexAttrib4sARB(p0, p1, p2, p3, p4);
    }

    public static void glVertexAttribPointerARB(int p0, int p1, int p2, boolean p3, int p4, long p5) {
        com.github.lodestone.lwjgl3.opengl.ARBVertexShader.glVertexAttribPointerARB(p0, p1, p2, p3, p4, p5);
    }

    public static void glVertexAttribPointerARB(int p0, int p1, int p2, boolean p3, int p4, java.nio.ByteBuffer p5) {
        com.github.lodestone.lwjgl3.opengl.ARBVertexShader.glVertexAttribPointerARB(p0, p1, p2, p3, p4, p5);
    }

    private ARBVertexShader() {
    }
}
