// Generated by runtime/generate-lwjgl2-bindings.py. Do not edit.
//
// LWJGL 2's ARBVertexBufferObject. Every method forwards to LWJGL 3's binding of the same GL
// function, reached through the package the compatibility jar relocates
// LWJGL 3's OpenGL module into. The constants are LWJGL 2's own values.
package org.lwjgl.opengl;

public final class ARBVertexBufferObject {

    public static final int GL_ARRAY_BUFFER_ARB = 0x8892;
    public static final int GL_ARRAY_BUFFER_BINDING_ARB = 0x8894;
    public static final int GL_BUFFER_ACCESS_ARB = 0x88BB;
    public static final int GL_BUFFER_MAPPED_ARB = 0x88BC;
    public static final int GL_BUFFER_MAP_POINTER_ARB = 0x88BD;
    public static final int GL_BUFFER_SIZE_ARB = 0x8764;
    public static final int GL_BUFFER_USAGE_ARB = 0x8765;
    public static final int GL_COLOR_ARRAY_BUFFER_BINDING_ARB = 0x8898;
    public static final int GL_DYNAMIC_COPY_ARB = 0x88EA;
    public static final int GL_DYNAMIC_DRAW_ARB = 0x88E8;
    public static final int GL_DYNAMIC_READ_ARB = 0x88E9;
    public static final int GL_EDGE_FLAG_ARRAY_BUFFER_BINDING_ARB = 0x889B;
    public static final int GL_ELEMENT_ARRAY_BUFFER_ARB = 0x8893;
    public static final int GL_ELEMENT_ARRAY_BUFFER_BINDING_ARB = 0x8895;
    public static final int GL_FOG_COORDINATE_ARRAY_BUFFER_BINDING_ARB = 0x889D;
    public static final int GL_INDEX_ARRAY_BUFFER_BINDING_ARB = 0x8899;
    public static final int GL_NORMAL_ARRAY_BUFFER_BINDING_ARB = 0x8897;
    public static final int GL_READ_ONLY_ARB = 0x88B8;
    public static final int GL_READ_WRITE_ARB = 0x88BA;
    public static final int GL_SECONDARY_COLOR_ARRAY_BUFFER_BINDING_ARB = 0x889C;
    public static final int GL_STATIC_COPY_ARB = 0x88E6;
    public static final int GL_STATIC_DRAW_ARB = 0x88E4;
    public static final int GL_STATIC_READ_ARB = 0x88E5;
    public static final int GL_STREAM_COPY_ARB = 0x88E2;
    public static final int GL_STREAM_DRAW_ARB = 0x88E0;
    public static final int GL_STREAM_READ_ARB = 0x88E1;
    public static final int GL_TEXTURE_COORD_ARRAY_BUFFER_BINDING_ARB = 0x889A;
    public static final int GL_VERTEX_ARRAY_BUFFER_BINDING_ARB = 0x8896;
    public static final int GL_VERTEX_ATTRIB_ARRAY_BUFFER_BINDING_ARB = 0x889F;
    public static final int GL_WEIGHT_ARRAY_BUFFER_BINDING_ARB = 0x889E;
    public static final int GL_WRITE_ONLY_ARB = 0x88B9;

    public static void glBindBufferARB(int p0, int p1) {
        com.github.lodestone.lwjgl3.opengl.ARBVertexBufferObject.glBindBufferARB(p0, p1);
    }

    public static void glBufferDataARB(int p0, long p1, int p2) {
        com.github.lodestone.lwjgl3.opengl.ARBVertexBufferObject.glBufferDataARB(p0, p1, p2);
    }

    public static void glBufferDataARB(int p0, java.nio.ByteBuffer p1, int p2) {
        com.github.lodestone.lwjgl3.opengl.ARBVertexBufferObject.glBufferDataARB(p0, p1, p2);
    }

    public static void glBufferDataARB(int p0, java.nio.DoubleBuffer p1, int p2) {
        com.github.lodestone.lwjgl3.opengl.ARBVertexBufferObject.glBufferDataARB(p0, p1, p2);
    }

    public static void glBufferDataARB(int p0, java.nio.FloatBuffer p1, int p2) {
        com.github.lodestone.lwjgl3.opengl.ARBVertexBufferObject.glBufferDataARB(p0, p1, p2);
    }

    public static void glBufferDataARB(int p0, java.nio.IntBuffer p1, int p2) {
        com.github.lodestone.lwjgl3.opengl.ARBVertexBufferObject.glBufferDataARB(p0, p1, p2);
    }

    public static void glBufferDataARB(int p0, java.nio.ShortBuffer p1, int p2) {
        com.github.lodestone.lwjgl3.opengl.ARBVertexBufferObject.glBufferDataARB(p0, p1, p2);
    }

    public static void glBufferSubDataARB(int p0, long p1, java.nio.ByteBuffer p2) {
        com.github.lodestone.lwjgl3.opengl.ARBVertexBufferObject.glBufferSubDataARB(p0, p1, p2);
    }

    public static void glBufferSubDataARB(int p0, long p1, java.nio.DoubleBuffer p2) {
        com.github.lodestone.lwjgl3.opengl.ARBVertexBufferObject.glBufferSubDataARB(p0, p1, p2);
    }

    public static void glBufferSubDataARB(int p0, long p1, java.nio.FloatBuffer p2) {
        com.github.lodestone.lwjgl3.opengl.ARBVertexBufferObject.glBufferSubDataARB(p0, p1, p2);
    }

    public static void glBufferSubDataARB(int p0, long p1, java.nio.IntBuffer p2) {
        com.github.lodestone.lwjgl3.opengl.ARBVertexBufferObject.glBufferSubDataARB(p0, p1, p2);
    }

    public static void glBufferSubDataARB(int p0, long p1, java.nio.ShortBuffer p2) {
        com.github.lodestone.lwjgl3.opengl.ARBVertexBufferObject.glBufferSubDataARB(p0, p1, p2);
    }

    public static void glDeleteBuffersARB(int p0) {
        com.github.lodestone.lwjgl3.opengl.ARBVertexBufferObject.glDeleteBuffersARB(p0);
    }

    public static void glDeleteBuffersARB(java.nio.IntBuffer p0) {
        com.github.lodestone.lwjgl3.opengl.ARBVertexBufferObject.glDeleteBuffersARB(p0);
    }

    public static int glGenBuffersARB() {
        return com.github.lodestone.lwjgl3.opengl.ARBVertexBufferObject.glGenBuffersARB();
    }

    public static void glGenBuffersARB(java.nio.IntBuffer p0) {
        com.github.lodestone.lwjgl3.opengl.ARBVertexBufferObject.glGenBuffersARB(p0);
    }

    public static void glGetBufferParameterARB(int p0, int p1, java.nio.IntBuffer p2) {
        com.github.lodestone.lwjgl3.opengl.ARBVertexBufferObject.glGetBufferParameterivARB(p0, p1, p2);
    }

    public static int glGetBufferParameteriARB(int p0, int p1) {
        return com.github.lodestone.lwjgl3.opengl.ARBVertexBufferObject.glGetBufferParameteriARB(p0, p1);
    }

    public static void glGetBufferSubDataARB(int p0, long p1, java.nio.ByteBuffer p2) {
        com.github.lodestone.lwjgl3.opengl.ARBVertexBufferObject.glGetBufferSubDataARB(p0, p1, p2);
    }

    public static void glGetBufferSubDataARB(int p0, long p1, java.nio.DoubleBuffer p2) {
        com.github.lodestone.lwjgl3.opengl.ARBVertexBufferObject.glGetBufferSubDataARB(p0, p1, p2);
    }

    public static void glGetBufferSubDataARB(int p0, long p1, java.nio.FloatBuffer p2) {
        com.github.lodestone.lwjgl3.opengl.ARBVertexBufferObject.glGetBufferSubDataARB(p0, p1, p2);
    }

    public static void glGetBufferSubDataARB(int p0, long p1, java.nio.IntBuffer p2) {
        com.github.lodestone.lwjgl3.opengl.ARBVertexBufferObject.glGetBufferSubDataARB(p0, p1, p2);
    }

    public static void glGetBufferSubDataARB(int p0, long p1, java.nio.ShortBuffer p2) {
        com.github.lodestone.lwjgl3.opengl.ARBVertexBufferObject.glGetBufferSubDataARB(p0, p1, p2);
    }

    public static boolean glIsBufferARB(int p0) {
        return com.github.lodestone.lwjgl3.opengl.ARBVertexBufferObject.glIsBufferARB(p0);
    }

    public static java.nio.ByteBuffer glMapBufferARB(int p0, int p1, long p2, java.nio.ByteBuffer p3) {
        return com.github.lodestone.lwjgl3.opengl.ARBVertexBufferObject.glMapBufferARB(p0, p1, p2, p3);
    }

    public static java.nio.ByteBuffer glMapBufferARB(int p0, int p1, java.nio.ByteBuffer p2) {
        return com.github.lodestone.lwjgl3.opengl.ARBVertexBufferObject.glMapBufferARB(p0, p1, p2);
    }

    public static boolean glUnmapBufferARB(int p0) {
        return com.github.lodestone.lwjgl3.opengl.ARBVertexBufferObject.glUnmapBufferARB(p0);
    }

    private ARBVertexBufferObject() {
    }
}
