// Generated by runtime/generate-lwjgl2-bindings.py. Do not edit.
//
// LWJGL 2's EXTBlendFuncSeparate. Every method forwards to LWJGL 3's binding of the same GL
// function, reached through the package the compatibility jar relocates
// LWJGL 3's OpenGL module into. The constants are LWJGL 2's own values.
package org.lwjgl.opengl;

public final class EXTBlendFuncSeparate {

    public static final int GL_BLEND_DST_ALPHA_EXT = 0x80CA;
    public static final int GL_BLEND_DST_RGB_EXT = 0x80C8;
    public static final int GL_BLEND_SRC_ALPHA_EXT = 0x80CB;
    public static final int GL_BLEND_SRC_RGB_EXT = 0x80C9;

    public static void glBlendFuncSeparateEXT(int p0, int p1, int p2, int p3) {
        com.github.lodestone.lwjgl3.opengl.EXTBlendFuncSeparate.glBlendFuncSeparateEXT(p0, p1, p2, p3);
    }

    private EXTBlendFuncSeparate() {
    }
}
