// Generated by runtime/generate-lwjgl2-bindings.py. Do not edit.
//
// LWJGL 2's EXTFramebufferObject. Every method forwards to LWJGL 3's binding of the same GL
// function, reached through the package the compatibility jar relocates
// LWJGL 3's OpenGL module into. The constants are LWJGL 2's own values.
package org.lwjgl.opengl;

public final class EXTFramebufferObject {

    public static final int GL_COLOR_ATTACHMENT0_EXT = 0x8CE0;
    public static final int GL_COLOR_ATTACHMENT10_EXT = 0x8CEA;
    public static final int GL_COLOR_ATTACHMENT11_EXT = 0x8CEB;
    public static final int GL_COLOR_ATTACHMENT12_EXT = 0x8CEC;
    public static final int GL_COLOR_ATTACHMENT13_EXT = 0x8CED;
    public static final int GL_COLOR_ATTACHMENT14_EXT = 0x8CEE;
    public static final int GL_COLOR_ATTACHMENT15_EXT = 0x8CEF;
    public static final int GL_COLOR_ATTACHMENT1_EXT = 0x8CE1;
    public static final int GL_COLOR_ATTACHMENT2_EXT = 0x8CE2;
    public static final int GL_COLOR_ATTACHMENT3_EXT = 0x8CE3;
    public static final int GL_COLOR_ATTACHMENT4_EXT = 0x8CE4;
    public static final int GL_COLOR_ATTACHMENT5_EXT = 0x8CE5;
    public static final int GL_COLOR_ATTACHMENT6_EXT = 0x8CE6;
    public static final int GL_COLOR_ATTACHMENT7_EXT = 0x8CE7;
    public static final int GL_COLOR_ATTACHMENT8_EXT = 0x8CE8;
    public static final int GL_COLOR_ATTACHMENT9_EXT = 0x8CE9;
    public static final int GL_DEPTH_ATTACHMENT_EXT = 0x8D00;
    public static final int GL_FRAMEBUFFER_ATTACHMENT_OBJECT_NAME_EXT = 0x8CD1;
    public static final int GL_FRAMEBUFFER_ATTACHMENT_OBJECT_TYPE_EXT = 0x8CD0;
    public static final int GL_FRAMEBUFFER_ATTACHMENT_TEXTURE_3D_ZOFFSET_EXT = 0x8CD4;
    public static final int GL_FRAMEBUFFER_ATTACHMENT_TEXTURE_CUBE_MAP_FACE_EXT = 0x8CD3;
    public static final int GL_FRAMEBUFFER_ATTACHMENT_TEXTURE_LEVEL_EXT = 0x8CD2;
    public static final int GL_FRAMEBUFFER_BINDING_EXT = 0x8CA6;
    public static final int GL_FRAMEBUFFER_COMPLETE_EXT = 0x8CD5;
    public static final int GL_FRAMEBUFFER_EXT = 0x8D40;
    public static final int GL_FRAMEBUFFER_INCOMPLETE_ATTACHMENT_EXT = 0x8CD6;
    public static final int GL_FRAMEBUFFER_INCOMPLETE_DIMENSIONS_EXT = 0x8CD9;
    public static final int GL_FRAMEBUFFER_INCOMPLETE_DRAW_BUFFER_EXT = 0x8CDB;
    public static final int GL_FRAMEBUFFER_INCOMPLETE_FORMATS_EXT = 0x8CDA;
    public static final int GL_FRAMEBUFFER_INCOMPLETE_MISSING_ATTACHMENT_EXT = 0x8CD7;
    public static final int GL_FRAMEBUFFER_INCOMPLETE_READ_BUFFER_EXT = 0x8CDC;
    public static final int GL_FRAMEBUFFER_UNSUPPORTED_EXT = 0x8CDD;
    public static final int GL_INVALID_FRAMEBUFFER_OPERATION_EXT = 0x506;
    public static final int GL_MAX_COLOR_ATTACHMENTS_EXT = 0x8CDF;
    public static final int GL_MAX_RENDERBUFFER_SIZE_EXT = 0x84E8;
    public static final int GL_RENDERBUFFER_ALPHA_SIZE_EXT = 0x8D53;
    public static final int GL_RENDERBUFFER_BINDING_EXT = 0x8CA7;
    public static final int GL_RENDERBUFFER_BLUE_SIZE_EXT = 0x8D52;
    public static final int GL_RENDERBUFFER_DEPTH_SIZE_EXT = 0x8D54;
    public static final int GL_RENDERBUFFER_EXT = 0x8D41;
    public static final int GL_RENDERBUFFER_GREEN_SIZE_EXT = 0x8D51;
    public static final int GL_RENDERBUFFER_HEIGHT_EXT = 0x8D43;
    public static final int GL_RENDERBUFFER_INTERNAL_FORMAT_EXT = 0x8D44;
    public static final int GL_RENDERBUFFER_RED_SIZE_EXT = 0x8D50;
    public static final int GL_RENDERBUFFER_STENCIL_SIZE_EXT = 0x8D55;
    public static final int GL_RENDERBUFFER_WIDTH_EXT = 0x8D42;
    public static final int GL_STENCIL_ATTACHMENT_EXT = 0x8D20;
    public static final int GL_STENCIL_INDEX16_EXT = 0x8D49;
    public static final int GL_STENCIL_INDEX1_EXT = 0x8D46;
    public static final int GL_STENCIL_INDEX4_EXT = 0x8D47;
    public static final int GL_STENCIL_INDEX8_EXT = 0x8D48;

    public static void glBindFramebufferEXT(int p0, int p1) {
        com.github.lodestone.lwjgl3.opengl.EXTFramebufferObject.glBindFramebufferEXT(p0, p1);
    }

    public static void glBindRenderbufferEXT(int p0, int p1) {
        com.github.lodestone.lwjgl3.opengl.EXTFramebufferObject.glBindRenderbufferEXT(p0, p1);
    }

    public static int glCheckFramebufferStatusEXT(int p0) {
        return com.github.lodestone.lwjgl3.opengl.EXTFramebufferObject.glCheckFramebufferStatusEXT(p0);
    }

    public static void glDeleteFramebuffersEXT(int p0) {
        com.github.lodestone.lwjgl3.opengl.EXTFramebufferObject.glDeleteFramebuffersEXT(p0);
    }

    public static void glDeleteFramebuffersEXT(java.nio.IntBuffer p0) {
        com.github.lodestone.lwjgl3.opengl.EXTFramebufferObject.glDeleteFramebuffersEXT(p0);
    }

    public static void glDeleteRenderbuffersEXT(int p0) {
        com.github.lodestone.lwjgl3.opengl.EXTFramebufferObject.glDeleteRenderbuffersEXT(p0);
    }

    public static void glDeleteRenderbuffersEXT(java.nio.IntBuffer p0) {
        com.github.lodestone.lwjgl3.opengl.EXTFramebufferObject.glDeleteRenderbuffersEXT(p0);
    }

    public static void glFramebufferRenderbufferEXT(int p0, int p1, int p2, int p3) {
        com.github.lodestone.lwjgl3.opengl.EXTFramebufferObject.glFramebufferRenderbufferEXT(p0, p1, p2, p3);
    }

    public static void glFramebufferTexture1DEXT(int p0, int p1, int p2, int p3, int p4) {
        com.github.lodestone.lwjgl3.opengl.EXTFramebufferObject.glFramebufferTexture1DEXT(p0, p1, p2, p3, p4);
    }

    public static void glFramebufferTexture2DEXT(int p0, int p1, int p2, int p3, int p4) {
        com.github.lodestone.lwjgl3.opengl.EXTFramebufferObject.glFramebufferTexture2DEXT(p0, p1, p2, p3, p4);
    }

    public static void glFramebufferTexture3DEXT(int p0, int p1, int p2, int p3, int p4, int p5) {
        com.github.lodestone.lwjgl3.opengl.EXTFramebufferObject.glFramebufferTexture3DEXT(p0, p1, p2, p3, p4, p5);
    }

    public static int glGenFramebuffersEXT() {
        return com.github.lodestone.lwjgl3.opengl.EXTFramebufferObject.glGenFramebuffersEXT();
    }

    public static void glGenFramebuffersEXT(java.nio.IntBuffer p0) {
        com.github.lodestone.lwjgl3.opengl.EXTFramebufferObject.glGenFramebuffersEXT(p0);
    }

    public static int glGenRenderbuffersEXT() {
        return com.github.lodestone.lwjgl3.opengl.EXTFramebufferObject.glGenRenderbuffersEXT();
    }

    public static void glGenRenderbuffersEXT(java.nio.IntBuffer p0) {
        com.github.lodestone.lwjgl3.opengl.EXTFramebufferObject.glGenRenderbuffersEXT(p0);
    }

    public static void glGenerateMipmapEXT(int p0) {
        com.github.lodestone.lwjgl3.opengl.EXTFramebufferObject.glGenerateMipmapEXT(p0);
    }

    public static void glGetFramebufferAttachmentParameterEXT(int p0, int p1, int p2, java.nio.IntBuffer p3) {
        com.github.lodestone.lwjgl3.opengl.EXTFramebufferObject.glGetFramebufferAttachmentParameterivEXT(p0, p1, p2, p3);
    }

    public static int glGetFramebufferAttachmentParameteriEXT(int p0, int p1, int p2) {
        return com.github.lodestone.lwjgl3.opengl.EXTFramebufferObject.glGetFramebufferAttachmentParameteriEXT(p0, p1, p2);
    }

    public static void glGetRenderbufferParameterEXT(int p0, int p1, java.nio.IntBuffer p2) {
        com.github.lodestone.lwjgl3.opengl.EXTFramebufferObject.glGetRenderbufferParameterivEXT(p0, p1, p2);
    }

    public static int glGetRenderbufferParameteriEXT(int p0, int p1) {
        return com.github.lodestone.lwjgl3.opengl.EXTFramebufferObject.glGetRenderbufferParameteriEXT(p0, p1);
    }

    public static boolean glIsFramebufferEXT(int p0) {
        return com.github.lodestone.lwjgl3.opengl.EXTFramebufferObject.glIsFramebufferEXT(p0);
    }

    public static boolean glIsRenderbufferEXT(int p0) {
        return com.github.lodestone.lwjgl3.opengl.EXTFramebufferObject.glIsRenderbufferEXT(p0);
    }

    public static void glRenderbufferStorageEXT(int p0, int p1, int p2, int p3) {
        com.github.lodestone.lwjgl3.opengl.EXTFramebufferObject.glRenderbufferStorageEXT(p0, p1, p2, p3);
    }

    private EXTFramebufferObject() {
    }
}
