// Generated by runtime/generate-lwjgl2-bindings.py. Do not edit.
//
// LWJGL 2's EXTTextureFilterAnisotropic. Every method forwards to LWJGL 3's binding of the same GL
// function, reached through the package the compatibility jar relocates
// LWJGL 3's OpenGL module into. The constants are LWJGL 2's own values.
package org.lwjgl.opengl;

public final class EXTTextureFilterAnisotropic {

    public static final int GL_MAX_TEXTURE_MAX_ANISOTROPY_EXT = 0x84FF;
    public static final int GL_TEXTURE_MAX_ANISOTROPY_EXT = 0x84FE;

    private EXTTextureFilterAnisotropic() {
    }
}
