// Generated by runtime/generate-lwjgl2-bindings.py. Do not edit.
//
// LWJGL 2's GL11. Every method forwards to LWJGL 3's binding of the same GL
// function, reached through the package the compatibility jar relocates
// LWJGL 3's OpenGL module into. The constants are LWJGL 2's own values.
package org.lwjgl.opengl;

public final class GL11 {

    public static final int GL_2D = 0x600;
    public static final int GL_2_BYTES = 0x1407;
    public static final int GL_3D = 0x601;
    public static final int GL_3D_COLOR = 0x602;
    public static final int GL_3D_COLOR_TEXTURE = 0x603;
    public static final int GL_3_BYTES = 0x1408;
    public static final int GL_4D_COLOR_TEXTURE = 0x604;
    public static final int GL_4_BYTES = 0x1409;
    public static final int GL_ACCUM = 0x100;
    public static final int GL_ACCUM_ALPHA_BITS = 0xD5B;
    public static final int GL_ACCUM_BLUE_BITS = 0xD5A;
    public static final int GL_ACCUM_BUFFER_BIT = 0x200;
    public static final int GL_ACCUM_CLEAR_VALUE = 0xB80;
    public static final int GL_ACCUM_GREEN_BITS = 0xD59;
    public static final int GL_ACCUM_RED_BITS = 0xD58;
    public static final int GL_ADD = 0x104;
    public static final int GL_ALL_ATTRIB_BITS = 0xFFFFF;
    public static final int GL_ALL_CLIENT_ATTRIB_BITS = -1;
    public static final int GL_ALPHA = 0x1906;
    public static final int GL_ALPHA12 = 0x803D;
    public static final int GL_ALPHA16 = 0x803E;
    public static final int GL_ALPHA4 = 0x803B;
    public static final int GL_ALPHA8 = 0x803C;
    public static final int GL_ALPHA_BIAS = 0xD1D;
    public static final int GL_ALPHA_BITS = 0xD55;
    public static final int GL_ALPHA_SCALE = 0xD1C;
    public static final int GL_ALPHA_TEST = 0xBC0;
    public static final int GL_ALPHA_TEST_FUNC = 0xBC1;
    public static final int GL_ALPHA_TEST_REF = 0xBC2;
    public static final int GL_ALWAYS = 0x207;
    public static final int GL_AMBIENT = 0x1200;
    public static final int GL_AMBIENT_AND_DIFFUSE = 0x1602;
    public static final int GL_AND = 0x1501;
    public static final int GL_AND_INVERTED = 0x1504;
    public static final int GL_AND_REVERSE = 0x1502;
    public static final int GL_ATTRIB_STACK_DEPTH = 0xBB0;
    public static final int GL_AUTO_NORMAL = 0xD80;
    public static final int GL_AUX0 = 0x409;
    public static final int GL_AUX1 = 0x40A;
    public static final int GL_AUX2 = 0x40B;
    public static final int GL_AUX3 = 0x40C;
    public static final int GL_AUX_BUFFERS = 0xC00;
    public static final int GL_BACK = 0x405;
    public static final int GL_BACK_LEFT = 0x402;
    public static final int GL_BACK_RIGHT = 0x403;
    public static final int GL_BITMAP = 0x1A00;
    public static final int GL_BITMAP_TOKEN = 0x704;
    public static final int GL_BLEND = 0xBE2;
    public static final int GL_BLEND_DST = 0xBE0;
    public static final int GL_BLEND_SRC = 0xBE1;
    public static final int GL_BLUE = 0x1905;
    public static final int GL_BLUE_BIAS = 0xD1B;
    public static final int GL_BLUE_BITS = 0xD54;
    public static final int GL_BLUE_SCALE = 0xD1A;
    public static final int GL_BYTE = 0x1400;
    public static final int GL_C3F_V3F = 0x2A24;
    public static final int GL_C4F_N3F_V3F = 0x2A26;
    public static final int GL_C4UB_V2F = 0x2A22;
    public static final int GL_C4UB_V3F = 0x2A23;
    public static final int GL_CCW = 0x901;
    public static final int GL_CLAMP = 0x2900;
    public static final int GL_CLEAR = 0x1500;
    public static final int GL_CLIENT_ATTRIB_STACK_DEPTH = 0xBB1;
    public static final int GL_CLIENT_PIXEL_STORE_BIT = 0x1;
    public static final int GL_CLIENT_VERTEX_ARRAY_BIT = 0x2;
    public static final int GL_CLIP_PLANE0 = 0x3000;
    public static final int GL_CLIP_PLANE1 = 0x3001;
    public static final int GL_CLIP_PLANE2 = 0x3002;
    public static final int GL_CLIP_PLANE3 = 0x3003;
    public static final int GL_CLIP_PLANE4 = 0x3004;
    public static final int GL_CLIP_PLANE5 = 0x3005;
    public static final int GL_COEFF = 0xA00;
    public static final int GL_COLOR = 0x1800;
    public static final int GL_COLOR_ARRAY = 0x8076;
    public static final int GL_COLOR_ARRAY_POINTER = 0x8090;
    public static final int GL_COLOR_ARRAY_SIZE = 0x8081;
    public static final int GL_COLOR_ARRAY_STRIDE = 0x8083;
    public static final int GL_COLOR_ARRAY_TYPE = 0x8082;
    public static final int GL_COLOR_BUFFER_BIT = 0x4000;
    public static final int GL_COLOR_CLEAR_VALUE = 0xC22;
    public static final int GL_COLOR_INDEX = 0x1900;
    public static final int GL_COLOR_INDEXES = 0x1603;
    public static final int GL_COLOR_LOGIC_OP = 0xBF2;
    public static final int GL_COLOR_MATERIAL = 0xB57;
    public static final int GL_COLOR_MATERIAL_FACE = 0xB55;
    public static final int GL_COLOR_MATERIAL_PARAMETER = 0xB56;
    public static final int GL_COLOR_WRITEMASK = 0xC23;
    public static final int GL_COMPILE = 0x1300;
    public static final int GL_COMPILE_AND_EXECUTE = 0x1301;
    public static final int GL_CONSTANT_ALPHA = 0x8003;
    public static final int GL_CONSTANT_ATTENUATION = 0x1207;
    public static final int GL_CONSTANT_COLOR = 0x8001;
    public static final int GL_COPY = 0x1503;
    public static final int GL_COPY_INVERTED = 0x150C;
    public static final int GL_COPY_PIXEL_TOKEN = 0x706;
    public static final int GL_CULL_FACE = 0xB44;
    public static final int GL_CULL_FACE_MODE = 0xB45;
    public static final int GL_CURRENT_BIT = 0x1;
    public static final int GL_CURRENT_COLOR = 0xB00;
    public static final int GL_CURRENT_INDEX = 0xB01;
    public static final int GL_CURRENT_NORMAL = 0xB02;
    public static final int GL_CURRENT_RASTER_COLOR = 0xB04;
    public static final int GL_CURRENT_RASTER_DISTANCE = 0xB09;
    public static final int GL_CURRENT_RASTER_INDEX = 0xB05;
    public static final int GL_CURRENT_RASTER_POSITION = 0xB07;
    public static final int GL_CURRENT_RASTER_POSITION_VALID = 0xB08;
    public static final int GL_CURRENT_RASTER_TEXTURE_COORDS = 0xB06;
    public static final int GL_CURRENT_TEXTURE_COORDS = 0xB03;
    public static final int GL_CW = 0x900;
    public static final int GL_DECAL = 0x2101;
    public static final int GL_DECR = 0x1E03;
    public static final int GL_DEPTH = 0x1801;
    public static final int GL_DEPTH_BIAS = 0xD1F;
    public static final int GL_DEPTH_BITS = 0xD56;
    public static final int GL_DEPTH_BUFFER_BIT = 0x100;
    public static final int GL_DEPTH_CLEAR_VALUE = 0xB73;
    public static final int GL_DEPTH_COMPONENT = 0x1902;
    public static final int GL_DEPTH_FUNC = 0xB74;
    public static final int GL_DEPTH_RANGE = 0xB70;
    public static final int GL_DEPTH_SCALE = 0xD1E;
    public static final int GL_DEPTH_TEST = 0xB71;
    public static final int GL_DEPTH_WRITEMASK = 0xB72;
    public static final int GL_DIFFUSE = 0x1201;
    public static final int GL_DITHER = 0xBD0;
    public static final int GL_DOMAIN = 0xA02;
    public static final int GL_DONT_CARE = 0x1100;
    public static final int GL_DOUBLE = 0x140A;
    public static final int GL_DOUBLEBUFFER = 0xC32;
    public static final int GL_DRAW_BUFFER = 0xC01;
    public static final int GL_DRAW_PIXEL_TOKEN = 0x705;
    public static final int GL_DST_ALPHA = 0x304;
    public static final int GL_DST_COLOR = 0x306;
    public static final int GL_EDGE_FLAG = 0xB43;
    public static final int GL_EDGE_FLAG_ARRAY = 0x8079;
    public static final int GL_EDGE_FLAG_ARRAY_POINTER = 0x8093;
    public static final int GL_EDGE_FLAG_ARRAY_STRIDE = 0x808C;
    public static final int GL_EMISSION = 0x1600;
    public static final int GL_ENABLE_BIT = 0x2000;
    public static final int GL_EQUAL = 0x202;
    public static final int GL_EQUIV = 0x1509;
    public static final int GL_EVAL_BIT = 0x10000;
    public static final int GL_EXP = 0x800;
    public static final int GL_EXP2 = 0x801;
    public static final int GL_EXTENSIONS = 0x1F03;
    public static final int GL_EYE_LINEAR = 0x2400;
    public static final int GL_EYE_PLANE = 0x2502;
    public static final int GL_FALSE = 0x0;
    public static final int GL_FASTEST = 0x1101;
    public static final int GL_FEEDBACK = 0x1C01;
    public static final int GL_FEEDBACK_BUFFER_POINTER = 0xDF0;
    public static final int GL_FEEDBACK_BUFFER_SIZE = 0xDF1;
    public static final int GL_FEEDBACK_BUFFER_TYPE = 0xDF2;
    public static final int GL_FILL = 0x1B02;
    public static final int GL_FLAT = 0x1D00;
    public static final int GL_FLOAT = 0x1406;
    public static final int GL_FOG = 0xB60;
    public static final int GL_FOG_BIT = 0x80;
    public static final int GL_FOG_COLOR = 0xB66;
    public static final int GL_FOG_DENSITY = 0xB62;
    public static final int GL_FOG_END = 0xB64;
    public static final int GL_FOG_HINT = 0xC54;
    public static final int GL_FOG_INDEX = 0xB61;
    public static final int GL_FOG_MODE = 0xB65;
    public static final int GL_FOG_START = 0xB63;
    public static final int GL_FRONT = 0x404;
    public static final int GL_FRONT_AND_BACK = 0x408;
    public static final int GL_FRONT_FACE = 0xB46;
    public static final int GL_FRONT_LEFT = 0x400;
    public static final int GL_FRONT_RIGHT = 0x401;
    public static final int GL_GEQUAL = 0x206;
    public static final int GL_GREATER = 0x204;
    public static final int GL_GREEN = 0x1904;
    public static final int GL_GREEN_BIAS = 0xD19;
    public static final int GL_GREEN_BITS = 0xD53;
    public static final int GL_GREEN_SCALE = 0xD18;
    public static final int GL_HINT_BIT = 0x8000;
    public static final int GL_INCR = 0x1E02;
    public static final int GL_INDEX_ARRAY = 0x8077;
    public static final int GL_INDEX_ARRAY_POINTER = 0x8091;
    public static final int GL_INDEX_ARRAY_STRIDE = 0x8086;
    public static final int GL_INDEX_ARRAY_TYPE = 0x8085;
    public static final int GL_INDEX_BITS = 0xD51;
    public static final int GL_INDEX_CLEAR_VALUE = 0xC20;
    public static final int GL_INDEX_LOGIC_OP = 0xBF1;
    public static final int GL_INDEX_MODE = 0xC30;
    public static final int GL_INDEX_OFFSET = 0xD13;
    public static final int GL_INDEX_SHIFT = 0xD12;
    public static final int GL_INDEX_WRITEMASK = 0xC21;
    public static final int GL_INT = 0x1404;
    public static final int GL_INTENSITY = 0x8049;
    public static final int GL_INTENSITY12 = 0x804C;
    public static final int GL_INTENSITY16 = 0x804D;
    public static final int GL_INTENSITY4 = 0x804A;
    public static final int GL_INTENSITY8 = 0x804B;
    public static final int GL_INVALID_ENUM = 0x500;
    public static final int GL_INVALID_OPERATION = 0x502;
    public static final int GL_INVALID_VALUE = 0x501;
    public static final int GL_INVERT = 0x150A;
    public static final int GL_KEEP = 0x1E00;
    public static final int GL_LEFT = 0x406;
    public static final int GL_LEQUAL = 0x203;
    public static final int GL_LESS = 0x201;
    public static final int GL_LIGHT0 = 0x4000;
    public static final int GL_LIGHT1 = 0x4001;
    public static final int GL_LIGHT2 = 0x4002;
    public static final int GL_LIGHT3 = 0x4003;
    public static final int GL_LIGHT4 = 0x4004;
    public static final int GL_LIGHT5 = 0x4005;
    public static final int GL_LIGHT6 = 0x4006;
    public static final int GL_LIGHT7 = 0x4007;
    public static final int GL_LIGHTING = 0xB50;
    public static final int GL_LIGHTING_BIT = 0x40;
    public static final int GL_LIGHT_MODEL_AMBIENT = 0xB53;
    public static final int GL_LIGHT_MODEL_LOCAL_VIEWER = 0xB51;
    public static final int GL_LIGHT_MODEL_TWO_SIDE = 0xB52;
    public static final int GL_LINE = 0x1B01;
    public static final int GL_LINEAR = 0x2601;
    public static final int GL_LINEAR_ATTENUATION = 0x1208;
    public static final int GL_LINEAR_MIPMAP_LINEAR = 0x2703;
    public static final int GL_LINEAR_MIPMAP_NEAREST = 0x2701;
    public static final int GL_LINES = 0x1;
    public static final int GL_LINE_BIT = 0x4;
    public static final int GL_LINE_LOOP = 0x2;
    public static final int GL_LINE_RESET_TOKEN = 0x707;
    public static final int GL_LINE_SMOOTH = 0xB20;
    public static final int GL_LINE_SMOOTH_HINT = 0xC52;
    public static final int GL_LINE_STIPPLE = 0xB24;
    public static final int GL_LINE_STIPPLE_PATTERN = 0xB25;
    public static final int GL_LINE_STIPPLE_REPEAT = 0xB26;
    public static final int GL_LINE_STRIP = 0x3;
    public static final int GL_LINE_TOKEN = 0x702;
    public static final int GL_LINE_WIDTH = 0xB21;
    public static final int GL_LINE_WIDTH_GRANULARITY = 0xB23;
    public static final int GL_LINE_WIDTH_RANGE = 0xB22;
    public static final int GL_LIST_BASE = 0xB32;
    public static final int GL_LIST_BIT = 0x20000;
    public static final int GL_LIST_INDEX = 0xB33;
    public static final int GL_LIST_MODE = 0xB30;
    public static final int GL_LOAD = 0x101;
    public static final int GL_LOGIC_OP = 0xBF1;
    public static final int GL_LOGIC_OP_MODE = 0xBF0;
    public static final int GL_LUMINANCE = 0x1909;
    public static final int GL_LUMINANCE12 = 0x8041;
    public static final int GL_LUMINANCE12_ALPHA12 = 0x8047;
    public static final int GL_LUMINANCE12_ALPHA4 = 0x8046;
    public static final int GL_LUMINANCE16 = 0x8042;
    public static final int GL_LUMINANCE16_ALPHA16 = 0x8048;
    public static final int GL_LUMINANCE4 = 0x803F;
    public static final int GL_LUMINANCE4_ALPHA4 = 0x8043;
    public static final int GL_LUMINANCE6_ALPHA2 = 0x8044;
    public static final int GL_LUMINANCE8 = 0x8040;
    public static final int GL_LUMINANCE8_ALPHA8 = 0x8045;
    public static final int GL_LUMINANCE_ALPHA = 0x190A;
    public static final int GL_MAP1_COLOR_4 = 0xD90;
    public static final int GL_MAP1_GRID_DOMAIN = 0xDD0;
    public static final int GL_MAP1_GRID_SEGMENTS = 0xDD1;
    public static final int GL_MAP1_INDEX = 0xD91;
    public static final int GL_MAP1_NORMAL = 0xD92;
    public static final int GL_MAP1_TEXTURE_COORD_1 = 0xD93;
    public static final int GL_MAP1_TEXTURE_COORD_2 = 0xD94;
    public static final int GL_MAP1_TEXTURE_COORD_3 = 0xD95;
    public static final int GL_MAP1_TEXTURE_COORD_4 = 0xD96;
    public static final int GL_MAP1_VERTEX_3 = 0xD97;
    public static final int GL_MAP1_VERTEX_4 = 0xD98;
    public static final int GL_MAP2_COLOR_4 = 0xDB0;
    public static final int GL_MAP2_GRID_DOMAIN = 0xDD2;
    public static final int GL_MAP2_GRID_SEGMENTS = 0xDD3;
    public static final int GL_MAP2_INDEX = 0xDB1;
    public static final int GL_MAP2_NORMAL = 0xDB2;
    public static final int GL_MAP2_TEXTURE_COORD_1 = 0xDB3;
    public static final int GL_MAP2_TEXTURE_COORD_2 = 0xDB4;
    public static final int GL_MAP2_TEXTURE_COORD_3 = 0xDB5;
    public static final int GL_MAP2_TEXTURE_COORD_4 = 0xDB6;
    public static final int GL_MAP2_VERTEX_3 = 0xDB7;
    public static final int GL_MAP2_VERTEX_4 = 0xDB8;
    public static final int GL_MAP_COLOR = 0xD10;
    public static final int GL_MAP_STENCIL = 0xD11;
    public static final int GL_MATRIX_MODE = 0xBA0;
    public static final int GL_MAX_ATTRIB_STACK_DEPTH = 0xD35;
    public static final int GL_MAX_CLIENT_ATTRIB_STACK_DEPTH = 0xD3B;
    public static final int GL_MAX_CLIP_PLANES = 0xD32;
    public static final int GL_MAX_EVAL_ORDER = 0xD30;
    public static final int GL_MAX_LIGHTS = 0xD31;
    public static final int GL_MAX_LIST_NESTING = 0xB31;
    public static final int GL_MAX_MODELVIEW_STACK_DEPTH = 0xD36;
    public static final int GL_MAX_NAME_STACK_DEPTH = 0xD37;
    public static final int GL_MAX_PIXEL_MAP_TABLE = 0xD34;
    public static final int GL_MAX_PROJECTION_STACK_DEPTH = 0xD38;
    public static final int GL_MAX_TEXTURE_SIZE = 0xD33;
    public static final int GL_MAX_TEXTURE_STACK_DEPTH = 0xD39;
    public static final int GL_MAX_VIEWPORT_DIMS = 0xD3A;
    public static final int GL_MODELVIEW = 0x1700;
    public static final int GL_MODELVIEW_MATRIX = 0xBA6;
    public static final int GL_MODELVIEW_STACK_DEPTH = 0xBA3;
    public static final int GL_MODULATE = 0x2100;
    public static final int GL_MULT = 0x103;
    public static final int GL_N3F_V3F = 0x2A25;
    public static final int GL_NAME_STACK_DEPTH = 0xD70;
    public static final int GL_NAND = 0x150E;
    public static final int GL_NEAREST = 0x2600;
    public static final int GL_NEAREST_MIPMAP_LINEAR = 0x2702;
    public static final int GL_NEAREST_MIPMAP_NEAREST = 0x2700;
    public static final int GL_NEVER = 0x200;
    public static final int GL_NICEST = 0x1102;
    public static final int GL_NONE = 0x0;
    public static final int GL_NOOP = 0x1505;
    public static final int GL_NOR = 0x1508;
    public static final int GL_NORMALIZE = 0xBA1;
    public static final int GL_NORMAL_ARRAY = 0x8075;
    public static final int GL_NORMAL_ARRAY_POINTER = 0x808F;
    public static final int GL_NORMAL_ARRAY_STRIDE = 0x807F;
    public static final int GL_NORMAL_ARRAY_TYPE = 0x807E;
    public static final int GL_NOTEQUAL = 0x205;
    public static final int GL_NO_ERROR = 0x0;
    public static final int GL_OBJECT_LINEAR = 0x2401;
    public static final int GL_OBJECT_PLANE = 0x2501;
    public static final int GL_ONE = 0x1;
    public static final int GL_ONE_MINUS_CONSTANT_ALPHA = 0x8004;
    public static final int GL_ONE_MINUS_CONSTANT_COLOR = 0x8002;
    public static final int GL_ONE_MINUS_DST_ALPHA = 0x305;
    public static final int GL_ONE_MINUS_DST_COLOR = 0x307;
    public static final int GL_ONE_MINUS_SRC_ALPHA = 0x303;
    public static final int GL_ONE_MINUS_SRC_COLOR = 0x301;
    public static final int GL_OR = 0x1507;
    public static final int GL_ORDER = 0xA01;
    public static final int GL_OR_INVERTED = 0x150D;
    public static final int GL_OR_REVERSE = 0x150B;
    public static final int GL_OUT_OF_MEMORY = 0x505;
    public static final int GL_PACK_ALIGNMENT = 0xD05;
    public static final int GL_PACK_LSB_FIRST = 0xD01;
    public static final int GL_PACK_ROW_LENGTH = 0xD02;
    public static final int GL_PACK_SKIP_PIXELS = 0xD04;
    public static final int GL_PACK_SKIP_ROWS = 0xD03;
    public static final int GL_PACK_SWAP_BYTES = 0xD00;
    public static final int GL_PASS_THROUGH_TOKEN = 0x700;
    public static final int GL_PERSPECTIVE_CORRECTION_HINT = 0xC50;
    public static final int GL_PIXEL_MAP_A_TO_A = 0xC79;
    public static final int GL_PIXEL_MAP_A_TO_A_SIZE = 0xCB9;
    public static final int GL_PIXEL_MAP_B_TO_B = 0xC78;
    public static final int GL_PIXEL_MAP_B_TO_B_SIZE = 0xCB8;
    public static final int GL_PIXEL_MAP_G_TO_G = 0xC77;
    public static final int GL_PIXEL_MAP_G_TO_G_SIZE = 0xCB7;
    public static final int GL_PIXEL_MAP_I_TO_A = 0xC75;
    public static final int GL_PIXEL_MAP_I_TO_A_SIZE = 0xCB5;
    public static final int GL_PIXEL_MAP_I_TO_B = 0xC74;
    public static final int GL_PIXEL_MAP_I_TO_B_SIZE = 0xCB4;
    public static final int GL_PIXEL_MAP_I_TO_G = 0xC73;
    public static final int GL_PIXEL_MAP_I_TO_G_SIZE = 0xCB3;
    public static final int GL_PIXEL_MAP_I_TO_I = 0xC70;
    public static final int GL_PIXEL_MAP_I_TO_I_SIZE = 0xCB0;
    public static final int GL_PIXEL_MAP_I_TO_R = 0xC72;
    public static final int GL_PIXEL_MAP_I_TO_R_SIZE = 0xCB2;
    public static final int GL_PIXEL_MAP_R_TO_R = 0xC76;
    public static final int GL_PIXEL_MAP_R_TO_R_SIZE = 0xCB6;
    public static final int GL_PIXEL_MAP_S_TO_S = 0xC71;
    public static final int GL_PIXEL_MAP_S_TO_S_SIZE = 0xCB1;
    public static final int GL_PIXEL_MODE_BIT = 0x20;
    public static final int GL_POINT = 0x1B00;
    public static final int GL_POINTS = 0x0;
    public static final int GL_POINT_BIT = 0x2;
    public static final int GL_POINT_SIZE = 0xB11;
    public static final int GL_POINT_SIZE_GRANULARITY = 0xB13;
    public static final int GL_POINT_SIZE_RANGE = 0xB12;
    public static final int GL_POINT_SMOOTH = 0xB10;
    public static final int GL_POINT_SMOOTH_HINT = 0xC51;
    public static final int GL_POINT_TOKEN = 0x701;
    public static final int GL_POLYGON = 0x9;
    public static final int GL_POLYGON_BIT = 0x8;
    public static final int GL_POLYGON_MODE = 0xB40;
    public static final int GL_POLYGON_OFFSET_FACTOR = 0x8038;
    public static final int GL_POLYGON_OFFSET_FILL = 0x8037;
    public static final int GL_POLYGON_OFFSET_LINE = 0x2A02;
    public static final int GL_POLYGON_OFFSET_POINT = 0x2A01;
    public static final int GL_POLYGON_OFFSET_UNITS = 0x2A00;
    public static final int GL_POLYGON_SMOOTH = 0xB41;
    public static final int GL_POLYGON_SMOOTH_HINT = 0xC53;
    public static final int GL_POLYGON_STIPPLE = 0xB42;
    public static final int GL_POLYGON_STIPPLE_BIT = 0x10;
    public static final int GL_POLYGON_TOKEN = 0x703;
    public static final int GL_POSITION = 0x1203;
    public static final int GL_PROJECTION = 0x1701;
    public static final int GL_PROJECTION_MATRIX = 0xBA7;
    public static final int GL_PROJECTION_STACK_DEPTH = 0xBA4;
    public static final int GL_PROXY_TEXTURE_1D = 0x8063;
    public static final int GL_PROXY_TEXTURE_2D = 0x8064;
    public static final int GL_Q = 0x2003;
    public static final int GL_QUADRATIC_ATTENUATION = 0x1209;
    public static final int GL_QUADS = 0x7;
    public static final int GL_QUAD_STRIP = 0x8;
    public static final int GL_R = 0x2002;
    public static final int GL_R3_G3_B2 = 0x2A10;
    public static final int GL_READ_BUFFER = 0xC02;
    public static final int GL_RED = 0x1903;
    public static final int GL_RED_BIAS = 0xD15;
    public static final int GL_RED_BITS = 0xD52;
    public static final int GL_RED_SCALE = 0xD14;
    public static final int GL_RENDER = 0x1C00;
    public static final int GL_RENDERER = 0x1F01;
    public static final int GL_RENDER_MODE = 0xC40;
    public static final int GL_REPEAT = 0x2901;
    public static final int GL_REPLACE = 0x1E01;
    public static final int GL_RETURN = 0x102;
    public static final int GL_RGB = 0x1907;
    public static final int GL_RGB10 = 0x8052;
    public static final int GL_RGB10_A2 = 0x8059;
    public static final int GL_RGB12 = 0x8053;
    public static final int GL_RGB16 = 0x8054;
    public static final int GL_RGB4 = 0x804F;
    public static final int GL_RGB5 = 0x8050;
    public static final int GL_RGB5_A1 = 0x8057;
    public static final int GL_RGB8 = 0x8051;
    public static final int GL_RGBA = 0x1908;
    public static final int GL_RGBA12 = 0x805A;
    public static final int GL_RGBA16 = 0x805B;
    public static final int GL_RGBA2 = 0x8055;
    public static final int GL_RGBA4 = 0x8056;
    public static final int GL_RGBA8 = 0x8058;
    public static final int GL_RGBA_MODE = 0xC31;
    public static final int GL_RIGHT = 0x407;
    public static final int GL_S = 0x2000;
    public static final int GL_SCISSOR_BIT = 0x80000;
    public static final int GL_SCISSOR_BOX = 0xC10;
    public static final int GL_SCISSOR_TEST = 0xC11;
    public static final int GL_SELECT = 0x1C02;
    public static final int GL_SELECTION_BUFFER_POINTER = 0xDF3;
    public static final int GL_SELECTION_BUFFER_SIZE = 0xDF4;
    public static final int GL_SET = 0x150F;
    public static final int GL_SHADE_MODEL = 0xB54;
    public static final int GL_SHININESS = 0x1601;
    public static final int GL_SHORT = 0x1402;
    public static final int GL_SMOOTH = 0x1D01;
    public static final int GL_SPECULAR = 0x1202;
    public static final int GL_SPHERE_MAP = 0x2402;
    public static final int GL_SPOT_CUTOFF = 0x1206;
    public static final int GL_SPOT_DIRECTION = 0x1204;
    public static final int GL_SPOT_EXPONENT = 0x1205;
    public static final int GL_SRC_ALPHA = 0x302;
    public static final int GL_SRC_ALPHA_SATURATE = 0x308;
    public static final int GL_SRC_COLOR = 0x300;
    public static final int GL_STACK_OVERFLOW = 0x503;
    public static final int GL_STACK_UNDERFLOW = 0x504;
    public static final int GL_STENCIL = 0x1802;
    public static final int GL_STENCIL_BITS = 0xD57;
    public static final int GL_STENCIL_BUFFER_BIT = 0x400;
    public static final int GL_STENCIL_CLEAR_VALUE = 0xB91;
    public static final int GL_STENCIL_FAIL = 0xB94;
    public static final int GL_STENCIL_FUNC = 0xB92;
    public static final int GL_STENCIL_INDEX = 0x1901;
    public static final int GL_STENCIL_PASS_DEPTH_FAIL = 0xB95;
    public static final int GL_STENCIL_PASS_DEPTH_PASS = 0xB96;
    public static final int GL_STENCIL_REF = 0xB97;
    public static final int GL_STENCIL_TEST = 0xB90;
    public static final int GL_STENCIL_VALUE_MASK = 0xB93;
    public static final int GL_STENCIL_WRITEMASK = 0xB98;
    public static final int GL_STEREO = 0xC33;
    public static final int GL_SUBPIXEL_BITS = 0xD50;
    public static final int GL_T = 0x2001;
    public static final int GL_T2F_C3F_V3F = 0x2A2A;
    public static final int GL_T2F_C4F_N3F_V3F = 0x2A2C;
    public static final int GL_T2F_C4UB_V3F = 0x2A29;
    public static final int GL_T2F_N3F_V3F = 0x2A2B;
    public static final int GL_T2F_V3F = 0x2A27;
    public static final int GL_T4F_C4F_N3F_V4F = 0x2A2D;
    public static final int GL_T4F_V4F = 0x2A28;
    public static final int GL_TEXTURE = 0x1702;
    public static final int GL_TEXTURE_1D = 0xDE0;
    public static final int GL_TEXTURE_2D = 0xDE1;
    public static final int GL_TEXTURE_ALPHA_SIZE = 0x805F;
    public static final int GL_TEXTURE_BINDING_1D = 0x8068;
    public static final int GL_TEXTURE_BINDING_2D = 0x8069;
    public static final int GL_TEXTURE_BIT = 0x40000;
    public static final int GL_TEXTURE_BLUE_SIZE = 0x805E;
    public static final int GL_TEXTURE_BORDER = 0x1005;
    public static final int GL_TEXTURE_BORDER_COLOR = 0x1004;
    public static final int GL_TEXTURE_COMPONENTS = 0x1003;
    public static final int GL_TEXTURE_COORD_ARRAY = 0x8078;
    public static final int GL_TEXTURE_COORD_ARRAY_POINTER = 0x8092;
    public static final int GL_TEXTURE_COORD_ARRAY_SIZE = 0x8088;
    public static final int GL_TEXTURE_COORD_ARRAY_STRIDE = 0x808A;
    public static final int GL_TEXTURE_COORD_ARRAY_TYPE = 0x8089;
    public static final int GL_TEXTURE_ENV = 0x2300;
    public static final int GL_TEXTURE_ENV_COLOR = 0x2201;
    public static final int GL_TEXTURE_ENV_MODE = 0x2200;
    public static final int GL_TEXTURE_GEN_MODE = 0x2500;
    public static final int GL_TEXTURE_GEN_Q = 0xC63;
    public static final int GL_TEXTURE_GEN_R = 0xC62;
    public static final int GL_TEXTURE_GEN_S = 0xC60;
    public static final int GL_TEXTURE_GEN_T = 0xC61;
    public static final int GL_TEXTURE_GREEN_SIZE = 0x805D;
    public static final int GL_TEXTURE_HEIGHT = 0x1001;
    public static final int GL_TEXTURE_INTENSITY_SIZE = 0x8061;
    public static final int GL_TEXTURE_INTERNAL_FORMAT = 0x1003;
    public static final int GL_TEXTURE_LUMINANCE_SIZE = 0x8060;
    public static final int GL_TEXTURE_MAG_FILTER = 0x2800;
    public static final int GL_TEXTURE_MATRIX = 0xBA8;
    public static final int GL_TEXTURE_MIN_FILTER = 0x2801;
    public static final int GL_TEXTURE_PRIORITY = 0x8066;
    public static final int GL_TEXTURE_RED_SIZE = 0x805C;
    public static final int GL_TEXTURE_RESIDENT = 0x8067;
    public static final int GL_TEXTURE_STACK_DEPTH = 0xBA5;
    public static final int GL_TEXTURE_WIDTH = 0x1000;
    public static final int GL_TEXTURE_WRAP_S = 0x2802;
    public static final int GL_TEXTURE_WRAP_T = 0x2803;
    public static final int GL_TRANSFORM_BIT = 0x1000;
    public static final int GL_TRIANGLES = 0x4;
    public static final int GL_TRIANGLE_FAN = 0x6;
    public static final int GL_TRIANGLE_STRIP = 0x5;
    public static final int GL_TRUE = 0x1;
    public static final int GL_UNPACK_ALIGNMENT = 0xCF5;
    public static final int GL_UNPACK_LSB_FIRST = 0xCF1;
    public static final int GL_UNPACK_ROW_LENGTH = 0xCF2;
    public static final int GL_UNPACK_SKIP_PIXELS = 0xCF4;
    public static final int GL_UNPACK_SKIP_ROWS = 0xCF3;
    public static final int GL_UNPACK_SWAP_BYTES = 0xCF0;
    public static final int GL_UNSIGNED_BYTE = 0x1401;
    public static final int GL_UNSIGNED_INT = 0x1405;
    public static final int GL_UNSIGNED_SHORT = 0x1403;
    public static final int GL_V2F = 0x2A20;
    public static final int GL_V3F = 0x2A21;
    public static final int GL_VENDOR = 0x1F00;
    public static final int GL_VERSION = 0x1F02;
    public static final int GL_VERTEX_ARRAY = 0x8074;
    public static final int GL_VERTEX_ARRAY_POINTER = 0x808E;
    public static final int GL_VERTEX_ARRAY_SIZE = 0x807A;
    public static final int GL_VERTEX_ARRAY_STRIDE = 0x807C;
    public static final int GL_VERTEX_ARRAY_TYPE = 0x807B;
    public static final int GL_VIEWPORT = 0xBA2;
    public static final int GL_VIEWPORT_BIT = 0x800;
    public static final int GL_XOR = 0x1506;
    public static final int GL_ZERO = 0x0;
    public static final int GL_ZOOM_X = 0xD16;
    public static final int GL_ZOOM_Y = 0xD17;

    public static void glAccum(int p0, float p1) {
        com.github.lodestone.lwjgl3.opengl.GL11.glAccum(p0, p1);
    }

    public static void glAlphaFunc(int p0, float p1) {
        com.github.lodestone.lwjgl3.opengl.GL11.glAlphaFunc(p0, p1);
    }

    public static boolean glAreTexturesResident(java.nio.IntBuffer p0, java.nio.ByteBuffer p1) {
        return com.github.lodestone.lwjgl3.opengl.GL11.glAreTexturesResident(p0, p1);
    }

    public static void glArrayElement(int p0) {
        com.github.lodestone.lwjgl3.opengl.GL11.glArrayElement(p0);
    }

    public static void glBegin(int p0) {
        com.github.lodestone.lwjgl3.opengl.GL11.glBegin(p0);
    }

    public static void glBindTexture(int p0, int p1) {
        com.github.lodestone.lwjgl3.opengl.GL11.glBindTexture(p0, p1);
    }

    public static void glBitmap(int p0, int p1, float p2, float p3, float p4, float p5, long p6) {
        com.github.lodestone.lwjgl3.opengl.GL11.glBitmap(p0, p1, p2, p3, p4, p5, p6);
    }

    public static void glBitmap(int p0, int p1, float p2, float p3, float p4, float p5, java.nio.ByteBuffer p6) {
        com.github.lodestone.lwjgl3.opengl.GL11.glBitmap(p0, p1, p2, p3, p4, p5, p6);
    }

    public static void glBlendFunc(int p0, int p1) {
        com.github.lodestone.lwjgl3.opengl.GL11.glBlendFunc(p0, p1);
    }

    public static void glCallList(int p0) {
        com.github.lodestone.lwjgl3.opengl.GL11.glCallList(p0);
    }

    public static void glCallLists(java.nio.ByteBuffer p0) {
        com.github.lodestone.lwjgl3.opengl.GL11.glCallLists(p0);
    }

    public static void glCallLists(java.nio.IntBuffer p0) {
        com.github.lodestone.lwjgl3.opengl.GL11.glCallLists(p0);
    }

    public static void glCallLists(java.nio.ShortBuffer p0) {
        com.github.lodestone.lwjgl3.opengl.GL11.glCallLists(p0);
    }

    public static void glClear(int p0) {
        com.github.lodestone.lwjgl3.opengl.GL11.glClear(p0);
    }

    public static void glClearAccum(float p0, float p1, float p2, float p3) {
        com.github.lodestone.lwjgl3.opengl.GL11.glClearAccum(p0, p1, p2, p3);
    }

    public static void glClearColor(float p0, float p1, float p2, float p3) {
        com.github.lodestone.lwjgl3.opengl.GL11.glClearColor(p0, p1, p2, p3);
    }

    public static void glClearDepth(double p0) {
        com.github.lodestone.lwjgl3.opengl.GL11.glClearDepth(p0);
    }

    public static void glClearStencil(int p0) {
        com.github.lodestone.lwjgl3.opengl.GL11.glClearStencil(p0);
    }

    public static void glClipPlane(int p0, java.nio.DoubleBuffer p1) {
        com.github.lodestone.lwjgl3.opengl.GL11.glClipPlane(p0, p1);
    }

    public static void glColor3b(byte p0, byte p1, byte p2) {
        com.github.lodestone.lwjgl3.opengl.GL11.glColor3b(p0, p1, p2);
    }

    public static void glColor3d(double p0, double p1, double p2) {
        com.github.lodestone.lwjgl3.opengl.GL11.glColor3d(p0, p1, p2);
    }

    public static void glColor3f(float p0, float p1, float p2) {
        com.github.lodestone.lwjgl3.opengl.GL11.glColor3f(p0, p1, p2);
    }

    public static void glColor3ub(byte p0, byte p1, byte p2) {
        com.github.lodestone.lwjgl3.opengl.GL11.glColor3ub(p0, p1, p2);
    }

    public static void glColor4b(byte p0, byte p1, byte p2, byte p3) {
        com.github.lodestone.lwjgl3.opengl.GL11.glColor4b(p0, p1, p2, p3);
    }

    public static void glColor4d(double p0, double p1, double p2, double p3) {
        com.github.lodestone.lwjgl3.opengl.GL11.glColor4d(p0, p1, p2, p3);
    }

    public static void glColor4f(float p0, float p1, float p2, float p3) {
        com.github.lodestone.lwjgl3.opengl.GL11.glColor4f(p0, p1, p2, p3);
    }

    public static void glColor4ub(byte p0, byte p1, byte p2, byte p3) {
        com.github.lodestone.lwjgl3.opengl.GL11.glColor4ub(p0, p1, p2, p3);
    }

    public static void glColorMask(boolean p0, boolean p1, boolean p2, boolean p3) {
        com.github.lodestone.lwjgl3.opengl.GL11.glColorMask(p0, p1, p2, p3);
    }

    public static void glColorMaterial(int p0, int p1) {
        com.github.lodestone.lwjgl3.opengl.GL11.glColorMaterial(p0, p1);
    }

    public static void glColorPointer(int p0, int p1, int p2, long p3) {
        com.github.lodestone.lwjgl3.opengl.GL11.glColorPointer(p0, p1, p2, p3);
    }

    public static void glColorPointer(int p0, int p1, int p2, java.nio.ByteBuffer p3) {
        com.github.lodestone.lwjgl3.opengl.GL11.glColorPointer(p0, p1, p2, p3);
    }

    public static void glColorPointer(int p0, int p1, java.nio.FloatBuffer p2) {
        com.github.lodestone.lwjgl3.opengl.GL11.glColorPointer(p0, GL_FLOAT, p1, p2);
    }

    public static void glColorPointer(int p0, boolean p1, int p2, java.nio.ByteBuffer p3) {
        com.github.lodestone.lwjgl3.opengl.GL11.glColorPointer(p0, p1 ? GL_UNSIGNED_BYTE : GL_BYTE, p2, p3);
    }

    public static void glCopyPixels(int p0, int p1, int p2, int p3, int p4) {
        com.github.lodestone.lwjgl3.opengl.GL11.glCopyPixels(p0, p1, p2, p3, p4);
    }

    public static void glCopyTexImage1D(int p0, int p1, int p2, int p3, int p4, int p5, int p6) {
        com.github.lodestone.lwjgl3.opengl.GL11.glCopyTexImage1D(p0, p1, p2, p3, p4, p5, p6);
    }

    public static void glCopyTexImage2D(int p0, int p1, int p2, int p3, int p4, int p5, int p6, int p7) {
        com.github.lodestone.lwjgl3.opengl.GL11.glCopyTexImage2D(p0, p1, p2, p3, p4, p5, p6, p7);
    }

    public static void glCopyTexSubImage1D(int p0, int p1, int p2, int p3, int p4, int p5) {
        com.github.lodestone.lwjgl3.opengl.GL11.glCopyTexSubImage1D(p0, p1, p2, p3, p4, p5);
    }

    public static void glCopyTexSubImage2D(int p0, int p1, int p2, int p3, int p4, int p5, int p6, int p7) {
        com.github.lodestone.lwjgl3.opengl.GL11.glCopyTexSubImage2D(p0, p1, p2, p3, p4, p5, p6, p7);
    }

    public static void glCullFace(int p0) {
        com.github.lodestone.lwjgl3.opengl.GL11.glCullFace(p0);
    }

    public static void glDeleteLists(int p0, int p1) {
        com.github.lodestone.lwjgl3.opengl.GL11.glDeleteLists(p0, p1);
    }

    public static void glDeleteTextures(int p0) {
        com.github.lodestone.lwjgl3.opengl.GL11.glDeleteTextures(p0);
    }

    public static void glDeleteTextures(java.nio.IntBuffer p0) {
        com.github.lodestone.lwjgl3.opengl.GL11.glDeleteTextures(p0);
    }

    public static void glDepthFunc(int p0) {
        com.github.lodestone.lwjgl3.opengl.GL11.glDepthFunc(p0);
    }

    public static void glDepthMask(boolean p0) {
        com.github.lodestone.lwjgl3.opengl.GL11.glDepthMask(p0);
    }

    public static void glDepthRange(double p0, double p1) {
        com.github.lodestone.lwjgl3.opengl.GL11.glDepthRange(p0, p1);
    }

    public static void glDisable(int p0) {
        com.github.lodestone.lwjgl3.opengl.GL11.glDisable(p0);
    }

    public static void glDisableClientState(int p0) {
        com.github.lodestone.lwjgl3.opengl.GL11.glDisableClientState(p0);
    }

    public static void glDrawArrays(int p0, int p1, int p2) {
        com.github.lodestone.lwjgl3.opengl.GL11.glDrawArrays(p0, p1, p2);
    }

    public static void glDrawBuffer(int p0) {
        com.github.lodestone.lwjgl3.opengl.GL11.glDrawBuffer(p0);
    }

    public static void glDrawElements(int p0, int p1, int p2, long p3) {
        com.github.lodestone.lwjgl3.opengl.GL11.glDrawElements(p0, p1, p2, p3);
    }

    public static void glDrawElements(int p0, java.nio.ByteBuffer p1) {
        com.github.lodestone.lwjgl3.opengl.GL11.glDrawElements(p0, p1);
    }

    public static void glDrawElements(int p0, java.nio.IntBuffer p1) {
        com.github.lodestone.lwjgl3.opengl.GL11.glDrawElements(p0, p1);
    }

    public static void glDrawElements(int p0, java.nio.ShortBuffer p1) {
        com.github.lodestone.lwjgl3.opengl.GL11.glDrawElements(p0, p1);
    }

    public static void glDrawPixels(int p0, int p1, int p2, int p3, long p4) {
        com.github.lodestone.lwjgl3.opengl.GL11.glDrawPixels(p0, p1, p2, p3, p4);
    }

    public static void glDrawPixels(int p0, int p1, int p2, int p3, java.nio.ByteBuffer p4) {
        com.github.lodestone.lwjgl3.opengl.GL11.glDrawPixels(p0, p1, p2, p3, p4);
    }

    public static void glDrawPixels(int p0, int p1, int p2, int p3, java.nio.IntBuffer p4) {
        com.github.lodestone.lwjgl3.opengl.GL11.glDrawPixels(p0, p1, p2, p3, p4);
    }

    public static void glDrawPixels(int p0, int p1, int p2, int p3, java.nio.ShortBuffer p4) {
        com.github.lodestone.lwjgl3.opengl.GL11.glDrawPixels(p0, p1, p2, p3, p4);
    }

    public static void glEdgeFlag(boolean p0) {
        com.github.lodestone.lwjgl3.opengl.GL11.glEdgeFlag(p0);
    }

    public static void glEdgeFlagPointer(int p0, long p1) {
        com.github.lodestone.lwjgl3.opengl.GL11.glEdgeFlagPointer(p0, p1);
    }

    public static void glEdgeFlagPointer(int p0, java.nio.ByteBuffer p1) {
        com.github.lodestone.lwjgl3.opengl.GL11.glEdgeFlagPointer(p0, p1);
    }

    public static void glEnable(int p0) {
        com.github.lodestone.lwjgl3.opengl.GL11.glEnable(p0);
    }

    public static void glEnableClientState(int p0) {
        com.github.lodestone.lwjgl3.opengl.GL11.glEnableClientState(p0);
    }

    public static void glEnd() {
        com.github.lodestone.lwjgl3.opengl.GL11.glEnd();
    }

    public static void glEndList() {
        com.github.lodestone.lwjgl3.opengl.GL11.glEndList();
    }

    public static void glEvalCoord1d(double p0) {
        com.github.lodestone.lwjgl3.opengl.GL11.glEvalCoord1d(p0);
    }

    public static void glEvalCoord1f(float p0) {
        com.github.lodestone.lwjgl3.opengl.GL11.glEvalCoord1f(p0);
    }

    public static void glEvalCoord2d(double p0, double p1) {
        com.github.lodestone.lwjgl3.opengl.GL11.glEvalCoord2d(p0, p1);
    }

    public static void glEvalCoord2f(float p0, float p1) {
        com.github.lodestone.lwjgl3.opengl.GL11.glEvalCoord2f(p0, p1);
    }

    public static void glEvalMesh1(int p0, int p1, int p2) {
        com.github.lodestone.lwjgl3.opengl.GL11.glEvalMesh1(p0, p1, p2);
    }

    public static void glEvalMesh2(int p0, int p1, int p2, int p3, int p4) {
        com.github.lodestone.lwjgl3.opengl.GL11.glEvalMesh2(p0, p1, p2, p3, p4);
    }

    public static void glEvalPoint1(int p0) {
        com.github.lodestone.lwjgl3.opengl.GL11.glEvalPoint1(p0);
    }

    public static void glEvalPoint2(int p0, int p1) {
        com.github.lodestone.lwjgl3.opengl.GL11.glEvalPoint2(p0, p1);
    }

    public static void glFeedbackBuffer(int p0, java.nio.FloatBuffer p1) {
        com.github.lodestone.lwjgl3.opengl.GL11.glFeedbackBuffer(p0, p1);
    }

    public static void glFinish() {
        com.github.lodestone.lwjgl3.opengl.GL11.glFinish();
    }

    public static void glFlush() {
        com.github.lodestone.lwjgl3.opengl.GL11.glFlush();
    }

    public static void glFog(int p0, java.nio.FloatBuffer p1) {
        com.github.lodestone.lwjgl3.opengl.GL11.glFogfv(p0, p1);
    }

    public static void glFog(int p0, java.nio.IntBuffer p1) {
        com.github.lodestone.lwjgl3.opengl.GL11.glFogiv(p0, p1);
    }

    public static void glFogf(int p0, float p1) {
        com.github.lodestone.lwjgl3.opengl.GL11.glFogf(p0, p1);
    }

    public static void glFogi(int p0, int p1) {
        com.github.lodestone.lwjgl3.opengl.GL11.glFogi(p0, p1);
    }

    public static void glFrontFace(int p0) {
        com.github.lodestone.lwjgl3.opengl.GL11.glFrontFace(p0);
    }

    public static void glFrustum(double p0, double p1, double p2, double p3, double p4, double p5) {
        com.github.lodestone.lwjgl3.opengl.GL11.glFrustum(p0, p1, p2, p3, p4, p5);
    }

    public static int glGenLists(int p0) {
        return com.github.lodestone.lwjgl3.opengl.GL11.glGenLists(p0);
    }

    public static int glGenTextures() {
        return com.github.lodestone.lwjgl3.opengl.GL11.glGenTextures();
    }

    public static void glGenTextures(java.nio.IntBuffer p0) {
        com.github.lodestone.lwjgl3.opengl.GL11.glGenTextures(p0);
    }

    public static boolean glGetBoolean(int p0) {
        return com.github.lodestone.lwjgl3.opengl.GL11.glGetBoolean(p0);
    }

    public static void glGetBoolean(int p0, java.nio.ByteBuffer p1) {
        com.github.lodestone.lwjgl3.opengl.GL11.glGetBooleanv(p0, p1);
    }

    public static void glGetClipPlane(int p0, java.nio.DoubleBuffer p1) {
        com.github.lodestone.lwjgl3.opengl.GL11.glGetClipPlane(p0, p1);
    }

    public static double glGetDouble(int p0) {
        return com.github.lodestone.lwjgl3.opengl.GL11.glGetDouble(p0);
    }

    public static void glGetDouble(int p0, java.nio.DoubleBuffer p1) {
        com.github.lodestone.lwjgl3.opengl.GL11.glGetDoublev(p0, p1);
    }

    public static int glGetError() {
        return com.github.lodestone.lwjgl3.opengl.GL11.glGetError();
    }

    public static float glGetFloat(int p0) {
        return com.github.lodestone.lwjgl3.opengl.GL11.glGetFloat(p0);
    }

    public static void glGetFloat(int p0, java.nio.FloatBuffer p1) {
        com.github.lodestone.lwjgl3.opengl.GL11.glGetFloatv(p0, p1);
    }

    public static int glGetInteger(int p0) {
        return com.github.lodestone.lwjgl3.opengl.GL11.glGetInteger(p0);
    }

    public static void glGetInteger(int p0, java.nio.IntBuffer p1) {
        com.github.lodestone.lwjgl3.opengl.GL11.glGetIntegerv(p0, p1);
    }

    public static void glGetLight(int p0, int p1, java.nio.FloatBuffer p2) {
        com.github.lodestone.lwjgl3.opengl.GL11.glGetLightfv(p0, p1, p2);
    }

    public static void glGetLight(int p0, int p1, java.nio.IntBuffer p2) {
        com.github.lodestone.lwjgl3.opengl.GL11.glGetLightiv(p0, p1, p2);
    }

    public static void glGetMap(int p0, int p1, java.nio.DoubleBuffer p2) {
        com.github.lodestone.lwjgl3.opengl.GL11.glGetMapdv(p0, p1, p2);
    }

    public static void glGetMap(int p0, int p1, java.nio.FloatBuffer p2) {
        com.github.lodestone.lwjgl3.opengl.GL11.glGetMapfv(p0, p1, p2);
    }

    public static void glGetMap(int p0, int p1, java.nio.IntBuffer p2) {
        com.github.lodestone.lwjgl3.opengl.GL11.glGetMapiv(p0, p1, p2);
    }

    public static void glGetMaterial(int p0, int p1, java.nio.FloatBuffer p2) {
        com.github.lodestone.lwjgl3.opengl.GL11.glGetMaterialfv(p0, p1, p2);
    }

    public static void glGetMaterial(int p0, int p1, java.nio.IntBuffer p2) {
        com.github.lodestone.lwjgl3.opengl.GL11.glGetMaterialiv(p0, p1, p2);
    }

    public static void glGetPixelMap(int p0, java.nio.FloatBuffer p1) {
        com.github.lodestone.lwjgl3.opengl.GL11.glGetPixelMapfv(p0, p1);
    }

    public static void glGetPixelMapfv(int p0, long p1) {
        com.github.lodestone.lwjgl3.opengl.GL11.glGetPixelMapfv(p0, p1);
    }

    public static void glGetPixelMapu(int p0, java.nio.IntBuffer p1) {
        com.github.lodestone.lwjgl3.opengl.GL11.glGetPixelMapuiv(p0, p1);
    }

    public static void glGetPixelMapu(int p0, java.nio.ShortBuffer p1) {
        com.github.lodestone.lwjgl3.opengl.GL11.glGetPixelMapusv(p0, p1);
    }

    public static void glGetPixelMapuiv(int p0, long p1) {
        com.github.lodestone.lwjgl3.opengl.GL11.glGetPixelMapuiv(p0, p1);
    }

    public static void glGetPixelMapusv(int p0, long p1) {
        com.github.lodestone.lwjgl3.opengl.GL11.glGetPixelMapusv(p0, p1);
    }

    public static void glGetPolygonStipple(long p0) {
        com.github.lodestone.lwjgl3.opengl.GL11.glGetPolygonStipple(p0);
    }

    public static void glGetPolygonStipple(java.nio.ByteBuffer p0) {
        com.github.lodestone.lwjgl3.opengl.GL11.glGetPolygonStipple(p0);
    }

    public static java.lang.String glGetString(int p0) {
        return com.github.lodestone.lwjgl3.opengl.GL11.glGetString(p0);
    }

    public static void glGetTexEnv(int p0, int p1, java.nio.FloatBuffer p2) {
        com.github.lodestone.lwjgl3.opengl.GL11.glGetTexEnvfv(p0, p1, p2);
    }

    public static void glGetTexEnv(int p0, int p1, java.nio.IntBuffer p2) {
        com.github.lodestone.lwjgl3.opengl.GL11.glGetTexEnviv(p0, p1, p2);
    }

    public static float glGetTexEnvf(int p0, int p1) {
        return com.github.lodestone.lwjgl3.opengl.GL11.glGetTexEnvf(p0, p1);
    }

    public static int glGetTexEnvi(int p0, int p1) {
        return com.github.lodestone.lwjgl3.opengl.GL11.glGetTexEnvi(p0, p1);
    }

    public static void glGetTexGen(int p0, int p1, java.nio.DoubleBuffer p2) {
        com.github.lodestone.lwjgl3.opengl.GL11.glGetTexGendv(p0, p1, p2);
    }

    public static void glGetTexGen(int p0, int p1, java.nio.FloatBuffer p2) {
        com.github.lodestone.lwjgl3.opengl.GL11.glGetTexGenfv(p0, p1, p2);
    }

    public static void glGetTexGen(int p0, int p1, java.nio.IntBuffer p2) {
        com.github.lodestone.lwjgl3.opengl.GL11.glGetTexGeniv(p0, p1, p2);
    }

    public static double glGetTexGend(int p0, int p1) {
        return com.github.lodestone.lwjgl3.opengl.GL11.glGetTexGend(p0, p1);
    }

    public static float glGetTexGenf(int p0, int p1) {
        return com.github.lodestone.lwjgl3.opengl.GL11.glGetTexGenf(p0, p1);
    }

    public static int glGetTexGeni(int p0, int p1) {
        return com.github.lodestone.lwjgl3.opengl.GL11.glGetTexGeni(p0, p1);
    }

    public static void glGetTexImage(int p0, int p1, int p2, int p3, long p4) {
        com.github.lodestone.lwjgl3.opengl.GL11.glGetTexImage(p0, p1, p2, p3, p4);
    }

    public static void glGetTexImage(int p0, int p1, int p2, int p3, java.nio.ByteBuffer p4) {
        com.github.lodestone.lwjgl3.opengl.GL11.glGetTexImage(p0, p1, p2, p3, p4);
    }

    public static void glGetTexImage(int p0, int p1, int p2, int p3, java.nio.DoubleBuffer p4) {
        com.github.lodestone.lwjgl3.opengl.GL11.glGetTexImage(p0, p1, p2, p3, p4);
    }

    public static void glGetTexImage(int p0, int p1, int p2, int p3, java.nio.FloatBuffer p4) {
        com.github.lodestone.lwjgl3.opengl.GL11.glGetTexImage(p0, p1, p2, p3, p4);
    }

    public static void glGetTexImage(int p0, int p1, int p2, int p3, java.nio.IntBuffer p4) {
        com.github.lodestone.lwjgl3.opengl.GL11.glGetTexImage(p0, p1, p2, p3, p4);
    }

    public static void glGetTexImage(int p0, int p1, int p2, int p3, java.nio.ShortBuffer p4) {
        com.github.lodestone.lwjgl3.opengl.GL11.glGetTexImage(p0, p1, p2, p3, p4);
    }

    public static void glGetTexLevelParameter(int p0, int p1, int p2, java.nio.FloatBuffer p3) {
        com.github.lodestone.lwjgl3.opengl.GL11.glGetTexLevelParameterfv(p0, p1, p2, p3);
    }

    public static void glGetTexLevelParameter(int p0, int p1, int p2, java.nio.IntBuffer p3) {
        com.github.lodestone.lwjgl3.opengl.GL11.glGetTexLevelParameteriv(p0, p1, p2, p3);
    }

    public static float glGetTexLevelParameterf(int p0, int p1, int p2) {
        return com.github.lodestone.lwjgl3.opengl.GL11.glGetTexLevelParameterf(p0, p1, p2);
    }

    public static int glGetTexLevelParameteri(int p0, int p1, int p2) {
        return com.github.lodestone.lwjgl3.opengl.GL11.glGetTexLevelParameteri(p0, p1, p2);
    }

    public static void glGetTexParameter(int p0, int p1, java.nio.FloatBuffer p2) {
        com.github.lodestone.lwjgl3.opengl.GL11.glGetTexParameterfv(p0, p1, p2);
    }

    public static void glGetTexParameter(int p0, int p1, java.nio.IntBuffer p2) {
        com.github.lodestone.lwjgl3.opengl.GL11.glGetTexParameteriv(p0, p1, p2);
    }

    public static float glGetTexParameterf(int p0, int p1) {
        return com.github.lodestone.lwjgl3.opengl.GL11.glGetTexParameterf(p0, p1);
    }

    public static int glGetTexParameteri(int p0, int p1) {
        return com.github.lodestone.lwjgl3.opengl.GL11.glGetTexParameteri(p0, p1);
    }

    public static void glHint(int p0, int p1) {
        com.github.lodestone.lwjgl3.opengl.GL11.glHint(p0, p1);
    }

    public static void glInitNames() {
        com.github.lodestone.lwjgl3.opengl.GL11.glInitNames();
    }

    public static void glInterleavedArrays(int p0, int p1, long p2) {
        com.github.lodestone.lwjgl3.opengl.GL11.glInterleavedArrays(p0, p1, p2);
    }

    public static void glInterleavedArrays(int p0, int p1, java.nio.ByteBuffer p2) {
        com.github.lodestone.lwjgl3.opengl.GL11.glInterleavedArrays(p0, p1, p2);
    }

    public static void glInterleavedArrays(int p0, int p1, java.nio.DoubleBuffer p2) {
        com.github.lodestone.lwjgl3.opengl.GL11.glInterleavedArrays(p0, p1, p2);
    }

    public static void glInterleavedArrays(int p0, int p1, java.nio.FloatBuffer p2) {
        com.github.lodestone.lwjgl3.opengl.GL11.glInterleavedArrays(p0, p1, p2);
    }

    public static void glInterleavedArrays(int p0, int p1, java.nio.IntBuffer p2) {
        com.github.lodestone.lwjgl3.opengl.GL11.glInterleavedArrays(p0, p1, p2);
    }

    public static void glInterleavedArrays(int p0, int p1, java.nio.ShortBuffer p2) {
        com.github.lodestone.lwjgl3.opengl.GL11.glInterleavedArrays(p0, p1, p2);
    }

    public static boolean glIsEnabled(int p0) {
        return com.github.lodestone.lwjgl3.opengl.GL11.glIsEnabled(p0);
    }

    public static boolean glIsList(int p0) {
        return com.github.lodestone.lwjgl3.opengl.GL11.glIsList(p0);
    }

    public static boolean glIsTexture(int p0) {
        return com.github.lodestone.lwjgl3.opengl.GL11.glIsTexture(p0);
    }

    public static void glLight(int p0, int p1, java.nio.FloatBuffer p2) {
        com.github.lodestone.lwjgl3.opengl.GL11.glLightfv(p0, p1, p2);
    }

    public static void glLight(int p0, int p1, java.nio.IntBuffer p2) {
        com.github.lodestone.lwjgl3.opengl.GL11.glLightiv(p0, p1, p2);
    }

    public static void glLightModel(int p0, java.nio.FloatBuffer p1) {
        com.github.lodestone.lwjgl3.opengl.GL11.glLightModelfv(p0, p1);
    }

    public static void glLightModel(int p0, java.nio.IntBuffer p1) {
        com.github.lodestone.lwjgl3.opengl.GL11.glLightModeliv(p0, p1);
    }

    public static void glLightModelf(int p0, float p1) {
        com.github.lodestone.lwjgl3.opengl.GL11.glLightModelf(p0, p1);
    }

    public static void glLightModeli(int p0, int p1) {
        com.github.lodestone.lwjgl3.opengl.GL11.glLightModeli(p0, p1);
    }

    public static void glLightf(int p0, int p1, float p2) {
        com.github.lodestone.lwjgl3.opengl.GL11.glLightf(p0, p1, p2);
    }

    public static void glLighti(int p0, int p1, int p2) {
        com.github.lodestone.lwjgl3.opengl.GL11.glLighti(p0, p1, p2);
    }

    public static void glLineStipple(int p0, short p1) {
        com.github.lodestone.lwjgl3.opengl.GL11.glLineStipple(p0, p1);
    }

    public static void glLineWidth(float p0) {
        com.github.lodestone.lwjgl3.opengl.GL11.glLineWidth(p0);
    }

    public static void glListBase(int p0) {
        com.github.lodestone.lwjgl3.opengl.GL11.glListBase(p0);
    }

    public static void glLoadIdentity() {
        com.github.lodestone.lwjgl3.opengl.GL11.glLoadIdentity();
    }

    public static void glLoadMatrix(java.nio.DoubleBuffer p0) {
        com.github.lodestone.lwjgl3.opengl.GL11.glLoadMatrixd(p0);
    }

    public static void glLoadMatrix(java.nio.FloatBuffer p0) {
        com.github.lodestone.lwjgl3.opengl.GL11.glLoadMatrixf(p0);
    }

    public static void glLoadName(int p0) {
        com.github.lodestone.lwjgl3.opengl.GL11.glLoadName(p0);
    }

    public static void glLogicOp(int p0) {
        com.github.lodestone.lwjgl3.opengl.GL11.glLogicOp(p0);
    }

    public static void glMap1d(int p0, double p1, double p2, int p3, int p4, java.nio.DoubleBuffer p5) {
        com.github.lodestone.lwjgl3.opengl.GL11.glMap1d(p0, p1, p2, p3, p4, p5);
    }

    public static void glMap1f(int p0, float p1, float p2, int p3, int p4, java.nio.FloatBuffer p5) {
        com.github.lodestone.lwjgl3.opengl.GL11.glMap1f(p0, p1, p2, p3, p4, p5);
    }

    public static void glMap2d(int p0, double p1, double p2, int p3, int p4, double p5, double p6, int p7, int p8, java.nio.DoubleBuffer p9) {
        com.github.lodestone.lwjgl3.opengl.GL11.glMap2d(p0, p1, p2, p3, p4, p5, p6, p7, p8, p9);
    }

    public static void glMap2f(int p0, float p1, float p2, int p3, int p4, float p5, float p6, int p7, int p8, java.nio.FloatBuffer p9) {
        com.github.lodestone.lwjgl3.opengl.GL11.glMap2f(p0, p1, p2, p3, p4, p5, p6, p7, p8, p9);
    }

    public static void glMapGrid1d(int p0, double p1, double p2) {
        com.github.lodestone.lwjgl3.opengl.GL11.glMapGrid1d(p0, p1, p2);
    }

    public static void glMapGrid1f(int p0, float p1, float p2) {
        com.github.lodestone.lwjgl3.opengl.GL11.glMapGrid1f(p0, p1, p2);
    }

    public static void glMapGrid2d(int p0, double p1, double p2, int p3, double p4, double p5) {
        com.github.lodestone.lwjgl3.opengl.GL11.glMapGrid2d(p0, p1, p2, p3, p4, p5);
    }

    public static void glMapGrid2f(int p0, float p1, float p2, int p3, float p4, float p5) {
        com.github.lodestone.lwjgl3.opengl.GL11.glMapGrid2f(p0, p1, p2, p3, p4, p5);
    }

    public static void glMaterial(int p0, int p1, java.nio.FloatBuffer p2) {
        com.github.lodestone.lwjgl3.opengl.GL11.glMaterialfv(p0, p1, p2);
    }

    public static void glMaterial(int p0, int p1, java.nio.IntBuffer p2) {
        com.github.lodestone.lwjgl3.opengl.GL11.glMaterialiv(p0, p1, p2);
    }

    public static void glMaterialf(int p0, int p1, float p2) {
        com.github.lodestone.lwjgl3.opengl.GL11.glMaterialf(p0, p1, p2);
    }

    public static void glMateriali(int p0, int p1, int p2) {
        com.github.lodestone.lwjgl3.opengl.GL11.glMateriali(p0, p1, p2);
    }

    public static void glMatrixMode(int p0) {
        com.github.lodestone.lwjgl3.opengl.GL11.glMatrixMode(p0);
    }

    public static void glMultMatrix(java.nio.DoubleBuffer p0) {
        com.github.lodestone.lwjgl3.opengl.GL11.glMultMatrixd(p0);
    }

    public static void glMultMatrix(java.nio.FloatBuffer p0) {
        com.github.lodestone.lwjgl3.opengl.GL11.glMultMatrixf(p0);
    }

    public static void glNewList(int p0, int p1) {
        com.github.lodestone.lwjgl3.opengl.GL11.glNewList(p0, p1);
    }

    public static void glNormal3b(byte p0, byte p1, byte p2) {
        com.github.lodestone.lwjgl3.opengl.GL11.glNormal3b(p0, p1, p2);
    }

    public static void glNormal3d(double p0, double p1, double p2) {
        com.github.lodestone.lwjgl3.opengl.GL11.glNormal3d(p0, p1, p2);
    }

    public static void glNormal3f(float p0, float p1, float p2) {
        com.github.lodestone.lwjgl3.opengl.GL11.glNormal3f(p0, p1, p2);
    }

    public static void glNormal3i(int p0, int p1, int p2) {
        com.github.lodestone.lwjgl3.opengl.GL11.glNormal3i(p0, p1, p2);
    }

    public static void glNormalPointer(int p0, int p1, long p2) {
        com.github.lodestone.lwjgl3.opengl.GL11.glNormalPointer(p0, p1, p2);
    }

    public static void glNormalPointer(int p0, int p1, java.nio.ByteBuffer p2) {
        com.github.lodestone.lwjgl3.opengl.GL11.glNormalPointer(p0, p1, p2);
    }

    public static void glNormalPointer(int p0, java.nio.ByteBuffer p1) {
        com.github.lodestone.lwjgl3.opengl.GL11.glNormalPointer(GL_BYTE, p0, p1);
    }

    public static void glNormalPointer(int p0, java.nio.FloatBuffer p1) {
        com.github.lodestone.lwjgl3.opengl.GL11.glNormalPointer(GL_FLOAT, p0, p1);
    }

    public static void glNormalPointer(int p0, java.nio.IntBuffer p1) {
        com.github.lodestone.lwjgl3.opengl.GL11.glNormalPointer(GL_INT, p0, p1);
    }

    public static void glOrtho(double p0, double p1, double p2, double p3, double p4, double p5) {
        com.github.lodestone.lwjgl3.opengl.GL11.glOrtho(p0, p1, p2, p3, p4, p5);
    }

    public static void glPassThrough(float p0) {
        com.github.lodestone.lwjgl3.opengl.GL11.glPassThrough(p0);
    }

    public static void glPixelMap(int p0, java.nio.FloatBuffer p1) {
        com.github.lodestone.lwjgl3.opengl.GL11.glPixelMapfv(p0, p1);
    }

    public static void glPixelMapfv(int p0, int p1, long p2) {
        com.github.lodestone.lwjgl3.opengl.GL11.glPixelMapfv(p0, p1, p2);
    }

    public static void glPixelMapu(int p0, java.nio.IntBuffer p1) {
        com.github.lodestone.lwjgl3.opengl.GL11.glPixelMapuiv(p0, p1);
    }

    public static void glPixelMapu(int p0, java.nio.ShortBuffer p1) {
        com.github.lodestone.lwjgl3.opengl.GL11.glPixelMapusv(p0, p1);
    }

    public static void glPixelMapuiv(int p0, int p1, long p2) {
        com.github.lodestone.lwjgl3.opengl.GL11.glPixelMapuiv(p0, p1, p2);
    }

    public static void glPixelMapusv(int p0, int p1, long p2) {
        com.github.lodestone.lwjgl3.opengl.GL11.glPixelMapusv(p0, p1, p2);
    }

    public static void glPixelStoref(int p0, float p1) {
        com.github.lodestone.lwjgl3.opengl.GL11.glPixelStoref(p0, p1);
    }

    public static void glPixelStorei(int p0, int p1) {
        com.github.lodestone.lwjgl3.opengl.GL11.glPixelStorei(p0, p1);
    }

    public static void glPixelTransferf(int p0, float p1) {
        com.github.lodestone.lwjgl3.opengl.GL11.glPixelTransferf(p0, p1);
    }

    public static void glPixelTransferi(int p0, int p1) {
        com.github.lodestone.lwjgl3.opengl.GL11.glPixelTransferi(p0, p1);
    }

    public static void glPixelZoom(float p0, float p1) {
        com.github.lodestone.lwjgl3.opengl.GL11.glPixelZoom(p0, p1);
    }

    public static void glPointSize(float p0) {
        com.github.lodestone.lwjgl3.opengl.GL11.glPointSize(p0);
    }

    public static void glPolygonMode(int p0, int p1) {
        com.github.lodestone.lwjgl3.opengl.GL11.glPolygonMode(p0, p1);
    }

    public static void glPolygonOffset(float p0, float p1) {
        com.github.lodestone.lwjgl3.opengl.GL11.glPolygonOffset(p0, p1);
    }

    public static void glPolygonStipple(long p0) {
        com.github.lodestone.lwjgl3.opengl.GL11.glPolygonStipple(p0);
    }

    public static void glPolygonStipple(java.nio.ByteBuffer p0) {
        com.github.lodestone.lwjgl3.opengl.GL11.glPolygonStipple(p0);
    }

    public static void glPopAttrib() {
        com.github.lodestone.lwjgl3.opengl.GL11.glPopAttrib();
    }

    public static void glPopClientAttrib() {
        com.github.lodestone.lwjgl3.opengl.GL11.glPopClientAttrib();
    }

    public static void glPopMatrix() {
        com.github.lodestone.lwjgl3.opengl.GL11.glPopMatrix();
    }

    public static void glPopName() {
        com.github.lodestone.lwjgl3.opengl.GL11.glPopName();
    }

    public static void glPrioritizeTextures(java.nio.IntBuffer p0, java.nio.FloatBuffer p1) {
        com.github.lodestone.lwjgl3.opengl.GL11.glPrioritizeTextures(p0, p1);
    }

    public static void glPushAttrib(int p0) {
        com.github.lodestone.lwjgl3.opengl.GL11.glPushAttrib(p0);
    }

    public static void glPushClientAttrib(int p0) {
        com.github.lodestone.lwjgl3.opengl.GL11.glPushClientAttrib(p0);
    }

    public static void glPushMatrix() {
        com.github.lodestone.lwjgl3.opengl.GL11.glPushMatrix();
    }

    public static void glPushName(int p0) {
        com.github.lodestone.lwjgl3.opengl.GL11.glPushName(p0);
    }

    public static void glRasterPos2d(double p0, double p1) {
        com.github.lodestone.lwjgl3.opengl.GL11.glRasterPos2d(p0, p1);
    }

    public static void glRasterPos2f(float p0, float p1) {
        com.github.lodestone.lwjgl3.opengl.GL11.glRasterPos2f(p0, p1);
    }

    public static void glRasterPos2i(int p0, int p1) {
        com.github.lodestone.lwjgl3.opengl.GL11.glRasterPos2i(p0, p1);
    }

    public static void glRasterPos3d(double p0, double p1, double p2) {
        com.github.lodestone.lwjgl3.opengl.GL11.glRasterPos3d(p0, p1, p2);
    }

    public static void glRasterPos3f(float p0, float p1, float p2) {
        com.github.lodestone.lwjgl3.opengl.GL11.glRasterPos3f(p0, p1, p2);
    }

    public static void glRasterPos3i(int p0, int p1, int p2) {
        com.github.lodestone.lwjgl3.opengl.GL11.glRasterPos3i(p0, p1, p2);
    }

    public static void glRasterPos4d(double p0, double p1, double p2, double p3) {
        com.github.lodestone.lwjgl3.opengl.GL11.glRasterPos4d(p0, p1, p2, p3);
    }

    public static void glRasterPos4f(float p0, float p1, float p2, float p3) {
        com.github.lodestone.lwjgl3.opengl.GL11.glRasterPos4f(p0, p1, p2, p3);
    }

    public static void glRasterPos4i(int p0, int p1, int p2, int p3) {
        com.github.lodestone.lwjgl3.opengl.GL11.glRasterPos4i(p0, p1, p2, p3);
    }

    public static void glReadBuffer(int p0) {
        com.github.lodestone.lwjgl3.opengl.GL11.glReadBuffer(p0);
    }

    public static void glReadPixels(int p0, int p1, int p2, int p3, int p4, int p5, long p6) {
        com.github.lodestone.lwjgl3.opengl.GL11.glReadPixels(p0, p1, p2, p3, p4, p5, p6);
    }

    public static void glReadPixels(int p0, int p1, int p2, int p3, int p4, int p5, java.nio.ByteBuffer p6) {
        com.github.lodestone.lwjgl3.opengl.GL11.glReadPixels(p0, p1, p2, p3, p4, p5, p6);
    }

    public static void glReadPixels(int p0, int p1, int p2, int p3, int p4, int p5, java.nio.FloatBuffer p6) {
        com.github.lodestone.lwjgl3.opengl.GL11.glReadPixels(p0, p1, p2, p3, p4, p5, p6);
    }

    public static void glReadPixels(int p0, int p1, int p2, int p3, int p4, int p5, java.nio.IntBuffer p6) {
        com.github.lodestone.lwjgl3.opengl.GL11.glReadPixels(p0, p1, p2, p3, p4, p5, p6);
    }

    public static void glReadPixels(int p0, int p1, int p2, int p3, int p4, int p5, java.nio.ShortBuffer p6) {
        com.github.lodestone.lwjgl3.opengl.GL11.glReadPixels(p0, p1, p2, p3, p4, p5, p6);
    }

    public static void glRectd(double p0, double p1, double p2, double p3) {
        com.github.lodestone.lwjgl3.opengl.GL11.glRectd(p0, p1, p2, p3);
    }

    public static void glRectf(float p0, float p1, float p2, float p3) {
        com.github.lodestone.lwjgl3.opengl.GL11.glRectf(p0, p1, p2, p3);
    }

    public static void glRecti(int p0, int p1, int p2, int p3) {
        com.github.lodestone.lwjgl3.opengl.GL11.glRecti(p0, p1, p2, p3);
    }

    public static int glRenderMode(int p0) {
        return com.github.lodestone.lwjgl3.opengl.GL11.glRenderMode(p0);
    }

    public static void glRotated(double p0, double p1, double p2, double p3) {
        com.github.lodestone.lwjgl3.opengl.GL11.glRotated(p0, p1, p2, p3);
    }

    public static void glRotatef(float p0, float p1, float p2, float p3) {
        com.github.lodestone.lwjgl3.opengl.GL11.glRotatef(p0, p1, p2, p3);
    }

    public static void glScaled(double p0, double p1, double p2) {
        com.github.lodestone.lwjgl3.opengl.GL11.glScaled(p0, p1, p2);
    }

    public static void glScalef(float p0, float p1, float p2) {
        com.github.lodestone.lwjgl3.opengl.GL11.glScalef(p0, p1, p2);
    }

    public static void glScissor(int p0, int p1, int p2, int p3) {
        com.github.lodestone.lwjgl3.opengl.GL11.glScissor(p0, p1, p2, p3);
    }

    public static void glSelectBuffer(java.nio.IntBuffer p0) {
        com.github.lodestone.lwjgl3.opengl.GL11.glSelectBuffer(p0);
    }

    public static void glShadeModel(int p0) {
        com.github.lodestone.lwjgl3.opengl.GL11.glShadeModel(p0);
    }

    public static void glStencilFunc(int p0, int p1, int p2) {
        com.github.lodestone.lwjgl3.opengl.GL11.glStencilFunc(p0, p1, p2);
    }

    public static void glStencilMask(int p0) {
        com.github.lodestone.lwjgl3.opengl.GL11.glStencilMask(p0);
    }

    public static void glStencilOp(int p0, int p1, int p2) {
        com.github.lodestone.lwjgl3.opengl.GL11.glStencilOp(p0, p1, p2);
    }

    public static void glTexCoord1d(double p0) {
        com.github.lodestone.lwjgl3.opengl.GL11.glTexCoord1d(p0);
    }

    public static void glTexCoord1f(float p0) {
        com.github.lodestone.lwjgl3.opengl.GL11.glTexCoord1f(p0);
    }

    public static void glTexCoord2d(double p0, double p1) {
        com.github.lodestone.lwjgl3.opengl.GL11.glTexCoord2d(p0, p1);
    }

    public static void glTexCoord2f(float p0, float p1) {
        com.github.lodestone.lwjgl3.opengl.GL11.glTexCoord2f(p0, p1);
    }

    public static void glTexCoord3d(double p0, double p1, double p2) {
        com.github.lodestone.lwjgl3.opengl.GL11.glTexCoord3d(p0, p1, p2);
    }

    public static void glTexCoord3f(float p0, float p1, float p2) {
        com.github.lodestone.lwjgl3.opengl.GL11.glTexCoord3f(p0, p1, p2);
    }

    public static void glTexCoord4d(double p0, double p1, double p2, double p3) {
        com.github.lodestone.lwjgl3.opengl.GL11.glTexCoord4d(p0, p1, p2, p3);
    }

    public static void glTexCoord4f(float p0, float p1, float p2, float p3) {
        com.github.lodestone.lwjgl3.opengl.GL11.glTexCoord4f(p0, p1, p2, p3);
    }

    public static void glTexCoordPointer(int p0, int p1, int p2, long p3) {
        com.github.lodestone.lwjgl3.opengl.GL11.glTexCoordPointer(p0, p1, p2, p3);
    }

    public static void glTexCoordPointer(int p0, int p1, int p2, java.nio.ByteBuffer p3) {
        com.github.lodestone.lwjgl3.opengl.GL11.glTexCoordPointer(p0, p1, p2, p3);
    }

    public static void glTexCoordPointer(int p0, int p1, java.nio.FloatBuffer p2) {
        com.github.lodestone.lwjgl3.opengl.GL11.glTexCoordPointer(p0, GL_FLOAT, p1, p2);
    }

    public static void glTexCoordPointer(int p0, int p1, java.nio.IntBuffer p2) {
        com.github.lodestone.lwjgl3.opengl.GL11.glTexCoordPointer(p0, GL_INT, p1, p2);
    }

    public static void glTexCoordPointer(int p0, int p1, java.nio.ShortBuffer p2) {
        com.github.lodestone.lwjgl3.opengl.GL11.glTexCoordPointer(p0, GL_SHORT, p1, p2);
    }

    public static void glTexEnv(int p0, int p1, java.nio.FloatBuffer p2) {
        com.github.lodestone.lwjgl3.opengl.GL11.glTexEnvfv(p0, p1, p2);
    }

    public static void glTexEnv(int p0, int p1, java.nio.IntBuffer p2) {
        com.github.lodestone.lwjgl3.opengl.GL11.glTexEnviv(p0, p1, p2);
    }

    public static void glTexEnvf(int p0, int p1, float p2) {
        com.github.lodestone.lwjgl3.opengl.GL11.glTexEnvf(p0, p1, p2);
    }

    public static void glTexEnvi(int p0, int p1, int p2) {
        com.github.lodestone.lwjgl3.opengl.GL11.glTexEnvi(p0, p1, p2);
    }

    public static void glTexGen(int p0, int p1, java.nio.DoubleBuffer p2) {
        com.github.lodestone.lwjgl3.opengl.GL11.glTexGendv(p0, p1, p2);
    }

    public static void glTexGen(int p0, int p1, java.nio.FloatBuffer p2) {
        com.github.lodestone.lwjgl3.opengl.GL11.glTexGenfv(p0, p1, p2);
    }

    public static void glTexGen(int p0, int p1, java.nio.IntBuffer p2) {
        com.github.lodestone.lwjgl3.opengl.GL11.glTexGeniv(p0, p1, p2);
    }

    public static void glTexGend(int p0, int p1, double p2) {
        com.github.lodestone.lwjgl3.opengl.GL11.glTexGend(p0, p1, p2);
    }

    public static void glTexGenf(int p0, int p1, float p2) {
        com.github.lodestone.lwjgl3.opengl.GL11.glTexGenf(p0, p1, p2);
    }

    public static void glTexGeni(int p0, int p1, int p2) {
        com.github.lodestone.lwjgl3.opengl.GL11.glTexGeni(p0, p1, p2);
    }

    public static void glTexImage1D(int p0, int p1, int p2, int p3, int p4, int p5, int p6, long p7) {
        com.github.lodestone.lwjgl3.opengl.GL11.glTexImage1D(p0, p1, p2, p3, p4, p5, p6, p7);
    }

    public static void glTexImage1D(int p0, int p1, int p2, int p3, int p4, int p5, int p6, java.nio.ByteBuffer p7) {
        com.github.lodestone.lwjgl3.opengl.GL11.glTexImage1D(p0, p1, p2, p3, p4, p5, p6, p7);
    }

    public static void glTexImage1D(int p0, int p1, int p2, int p3, int p4, int p5, int p6, java.nio.DoubleBuffer p7) {
        com.github.lodestone.lwjgl3.opengl.GL11.glTexImage1D(p0, p1, p2, p3, p4, p5, p6, p7);
    }

    public static void glTexImage1D(int p0, int p1, int p2, int p3, int p4, int p5, int p6, java.nio.FloatBuffer p7) {
        com.github.lodestone.lwjgl3.opengl.GL11.glTexImage1D(p0, p1, p2, p3, p4, p5, p6, p7);
    }

    public static void glTexImage1D(int p0, int p1, int p2, int p3, int p4, int p5, int p6, java.nio.IntBuffer p7) {
        com.github.lodestone.lwjgl3.opengl.GL11.glTexImage1D(p0, p1, p2, p3, p4, p5, p6, p7);
    }

    public static void glTexImage1D(int p0, int p1, int p2, int p3, int p4, int p5, int p6, java.nio.ShortBuffer p7) {
        com.github.lodestone.lwjgl3.opengl.GL11.glTexImage1D(p0, p1, p2, p3, p4, p5, p6, p7);
    }

    public static void glTexImage2D(int p0, int p1, int p2, int p3, int p4, int p5, int p6, int p7, long p8) {
        com.github.lodestone.lwjgl3.opengl.GL11.glTexImage2D(p0, p1, p2, p3, p4, p5, p6, p7, p8);
    }

    public static void glTexImage2D(int p0, int p1, int p2, int p3, int p4, int p5, int p6, int p7, java.nio.ByteBuffer p8) {
        com.github.lodestone.lwjgl3.opengl.GL11.glTexImage2D(p0, p1, p2, p3, p4, p5, p6, p7, p8);
    }

    public static void glTexImage2D(int p0, int p1, int p2, int p3, int p4, int p5, int p6, int p7, java.nio.DoubleBuffer p8) {
        com.github.lodestone.lwjgl3.opengl.GL11.glTexImage2D(p0, p1, p2, p3, p4, p5, p6, p7, p8);
    }

    public static void glTexImage2D(int p0, int p1, int p2, int p3, int p4, int p5, int p6, int p7, java.nio.FloatBuffer p8) {
        com.github.lodestone.lwjgl3.opengl.GL11.glTexImage2D(p0, p1, p2, p3, p4, p5, p6, p7, p8);
    }

    public static void glTexImage2D(int p0, int p1, int p2, int p3, int p4, int p5, int p6, int p7, java.nio.IntBuffer p8) {
        com.github.lodestone.lwjgl3.opengl.GL11.glTexImage2D(p0, p1, p2, p3, p4, p5, p6, p7, p8);
    }

    public static void glTexImage2D(int p0, int p1, int p2, int p3, int p4, int p5, int p6, int p7, java.nio.ShortBuffer p8) {
        com.github.lodestone.lwjgl3.opengl.GL11.glTexImage2D(p0, p1, p2, p3, p4, p5, p6, p7, p8);
    }

    public static void glTexParameter(int p0, int p1, java.nio.FloatBuffer p2) {
        com.github.lodestone.lwjgl3.opengl.GL11.glTexParameterfv(p0, p1, p2);
    }

    public static void glTexParameter(int p0, int p1, java.nio.IntBuffer p2) {
        com.github.lodestone.lwjgl3.opengl.GL11.glTexParameteriv(p0, p1, p2);
    }

    public static void glTexParameterf(int p0, int p1, float p2) {
        com.github.lodestone.lwjgl3.opengl.GL11.glTexParameterf(p0, p1, p2);
    }

    public static void glTexParameteri(int p0, int p1, int p2) {
        com.github.lodestone.lwjgl3.opengl.GL11.glTexParameteri(p0, p1, p2);
    }

    public static void glTexSubImage1D(int p0, int p1, int p2, int p3, int p4, int p5, long p6) {
        com.github.lodestone.lwjgl3.opengl.GL11.glTexSubImage1D(p0, p1, p2, p3, p4, p5, p6);
    }

    public static void glTexSubImage1D(int p0, int p1, int p2, int p3, int p4, int p5, java.nio.ByteBuffer p6) {
        com.github.lodestone.lwjgl3.opengl.GL11.glTexSubImage1D(p0, p1, p2, p3, p4, p5, p6);
    }

    public static void glTexSubImage1D(int p0, int p1, int p2, int p3, int p4, int p5, java.nio.DoubleBuffer p6) {
        com.github.lodestone.lwjgl3.opengl.GL11.glTexSubImage1D(p0, p1, p2, p3, p4, p5, p6);
    }

    public static void glTexSubImage1D(int p0, int p1, int p2, int p3, int p4, int p5, java.nio.FloatBuffer p6) {
        com.github.lodestone.lwjgl3.opengl.GL11.glTexSubImage1D(p0, p1, p2, p3, p4, p5, p6);
    }

    public static void glTexSubImage1D(int p0, int p1, int p2, int p3, int p4, int p5, java.nio.IntBuffer p6) {
        com.github.lodestone.lwjgl3.opengl.GL11.glTexSubImage1D(p0, p1, p2, p3, p4, p5, p6);
    }

    public static void glTexSubImage1D(int p0, int p1, int p2, int p3, int p4, int p5, java.nio.ShortBuffer p6) {
        com.github.lodestone.lwjgl3.opengl.GL11.glTexSubImage1D(p0, p1, p2, p3, p4, p5, p6);
    }

    public static void glTexSubImage2D(int p0, int p1, int p2, int p3, int p4, int p5, int p6, int p7, long p8) {
        com.github.lodestone.lwjgl3.opengl.GL11.glTexSubImage2D(p0, p1, p2, p3, p4, p5, p6, p7, p8);
    }

    public static void glTexSubImage2D(int p0, int p1, int p2, int p3, int p4, int p5, int p6, int p7, java.nio.ByteBuffer p8) {
        com.github.lodestone.lwjgl3.opengl.GL11.glTexSubImage2D(p0, p1, p2, p3, p4, p5, p6, p7, p8);
    }

    public static void glTexSubImage2D(int p0, int p1, int p2, int p3, int p4, int p5, int p6, int p7, java.nio.DoubleBuffer p8) {
        com.github.lodestone.lwjgl3.opengl.GL11.glTexSubImage2D(p0, p1, p2, p3, p4, p5, p6, p7, p8);
    }

    public static void glTexSubImage2D(int p0, int p1, int p2, int p3, int p4, int p5, int p6, int p7, java.nio.FloatBuffer p8) {
        com.github.lodestone.lwjgl3.opengl.GL11.glTexSubImage2D(p0, p1, p2, p3, p4, p5, p6, p7, p8);
    }

    public static void glTexSubImage2D(int p0, int p1, int p2, int p3, int p4, int p5, int p6, int p7, java.nio.IntBuffer p8) {
        com.github.lodestone.lwjgl3.opengl.GL11.glTexSubImage2D(p0, p1, p2, p3, p4, p5, p6, p7, p8);
    }

    public static void glTexSubImage2D(int p0, int p1, int p2, int p3, int p4, int p5, int p6, int p7, java.nio.ShortBuffer p8) {
        com.github.lodestone.lwjgl3.opengl.GL11.glTexSubImage2D(p0, p1, p2, p3, p4, p5, p6, p7, p8);
    }

    public static void glTranslated(double p0, double p1, double p2) {
        com.github.lodestone.lwjgl3.opengl.GL11.glTranslated(p0, p1, p2);
    }

    public static void glTranslatef(float p0, float p1, float p2) {
        com.github.lodestone.lwjgl3.opengl.GL11.glTranslatef(p0, p1, p2);
    }

    public static void glVertex2d(double p0, double p1) {
        com.github.lodestone.lwjgl3.opengl.GL11.glVertex2d(p0, p1);
    }

    public static void glVertex2f(float p0, float p1) {
        com.github.lodestone.lwjgl3.opengl.GL11.glVertex2f(p0, p1);
    }

    public static void glVertex2i(int p0, int p1) {
        com.github.lodestone.lwjgl3.opengl.GL11.glVertex2i(p0, p1);
    }

    public static void glVertex3d(double p0, double p1, double p2) {
        com.github.lodestone.lwjgl3.opengl.GL11.glVertex3d(p0, p1, p2);
    }

    public static void glVertex3f(float p0, float p1, float p2) {
        com.github.lodestone.lwjgl3.opengl.GL11.glVertex3f(p0, p1, p2);
    }

    public static void glVertex3i(int p0, int p1, int p2) {
        com.github.lodestone.lwjgl3.opengl.GL11.glVertex3i(p0, p1, p2);
    }

    public static void glVertex4d(double p0, double p1, double p2, double p3) {
        com.github.lodestone.lwjgl3.opengl.GL11.glVertex4d(p0, p1, p2, p3);
    }

    public static void glVertex4f(float p0, float p1, float p2, float p3) {
        com.github.lodestone.lwjgl3.opengl.GL11.glVertex4f(p0, p1, p2, p3);
    }

    public static void glVertex4i(int p0, int p1, int p2, int p3) {
        com.github.lodestone.lwjgl3.opengl.GL11.glVertex4i(p0, p1, p2, p3);
    }

    public static void glVertexPointer(int p0, int p1, int p2, long p3) {
        com.github.lodestone.lwjgl3.opengl.GL11.glVertexPointer(p0, p1, p2, p3);
    }

    public static void glVertexPointer(int p0, int p1, int p2, java.nio.ByteBuffer p3) {
        com.github.lodestone.lwjgl3.opengl.GL11.glVertexPointer(p0, p1, p2, p3);
    }

    public static void glVertexPointer(int p0, int p1, java.nio.FloatBuffer p2) {
        com.github.lodestone.lwjgl3.opengl.GL11.glVertexPointer(p0, GL_FLOAT, p1, p2);
    }

    public static void glVertexPointer(int p0, int p1, java.nio.IntBuffer p2) {
        com.github.lodestone.lwjgl3.opengl.GL11.glVertexPointer(p0, GL_INT, p1, p2);
    }

    public static void glVertexPointer(int p0, int p1, java.nio.ShortBuffer p2) {
        com.github.lodestone.lwjgl3.opengl.GL11.glVertexPointer(p0, GL_SHORT, p1, p2);
    }

    public static void glViewport(int p0, int p1, int p2, int p3) {
        com.github.lodestone.lwjgl3.opengl.GL11.glViewport(p0, p1, p2, p3);
    }

    private GL11() {
    }
}
