// Generated by runtime/generate-lwjgl2-bindings.py. Do not edit.
//
// LWJGL 2's GL12. Every method forwards to LWJGL 3's binding of the same GL
// function, reached through the package the compatibility jar relocates
// LWJGL 3's OpenGL module into. The constants are LWJGL 2's own values.
package org.lwjgl.opengl;

public final class GL12 {

    public static final int GL_ALIASED_LINE_WIDTH_RANGE = 0x846E;
    public static final int GL_ALIASED_POINT_SIZE_RANGE = 0x846D;
    public static final int GL_BGR = 0x80E0;
    public static final int GL_BGRA = 0x80E1;
    public static final int GL_CLAMP_TO_EDGE = 0x812F;
    public static final int GL_LIGHT_MODEL_COLOR_CONTROL = 0x81F8;
    public static final int GL_MAX_3D_TEXTURE_SIZE = 0x8073;
    public static final int GL_MAX_ELEMENTS_INDICES = 0x80E9;
    public static final int GL_MAX_ELEMENTS_VERTICES = 0x80E8;
    public static final int GL_PACK_IMAGE_HEIGHT = 0x806C;
    public static final int GL_PACK_SKIP_IMAGES = 0x806B;
    public static final int GL_PROXY_TEXTURE_3D = 0x8070;
    public static final int GL_RESCALE_NORMAL = 0x803A;
    public static final int GL_SEPARATE_SPECULAR_COLOR = 0x81FA;
    public static final int GL_SINGLE_COLOR = 0x81F9;
    public static final int GL_SMOOTH_LINE_WIDTH_GRANULARITY = 0xB23;
    public static final int GL_SMOOTH_LINE_WIDTH_RANGE = 0xB22;
    public static final int GL_SMOOTH_POINT_SIZE_GRANULARITY = 0xB13;
    public static final int GL_SMOOTH_POINT_SIZE_RANGE = 0xB12;
    public static final int GL_TEXTURE_3D = 0x806F;
    public static final int GL_TEXTURE_BASE_LEVEL = 0x813C;
    public static final int GL_TEXTURE_BINDING_3D = 0x806A;
    public static final int GL_TEXTURE_DEPTH = 0x8071;
    public static final int GL_TEXTURE_MAX_LEVEL = 0x813D;
    public static final int GL_TEXTURE_MAX_LOD = 0x813B;
    public static final int GL_TEXTURE_MIN_LOD = 0x813A;
    public static final int GL_TEXTURE_WRAP_R = 0x8072;
    public static final int GL_UNPACK_IMAGE_HEIGHT = 0x806E;
    public static final int GL_UNPACK_SKIP_IMAGES = 0x806D;
    public static final int GL_UNSIGNED_BYTE_2_3_3_REV = 0x8362;
    public static final int GL_UNSIGNED_BYTE_3_3_2 = 0x8032;
    public static final int GL_UNSIGNED_INT_10_10_10_2 = 0x8036;
    public static final int GL_UNSIGNED_INT_2_10_10_10_REV = 0x8368;
    public static final int GL_UNSIGNED_INT_8_8_8_8 = 0x8035;
    public static final int GL_UNSIGNED_INT_8_8_8_8_REV = 0x8367;
    public static final int GL_UNSIGNED_SHORT_1_5_5_5_REV = 0x8366;
    public static final int GL_UNSIGNED_SHORT_4_4_4_4 = 0x8033;
    public static final int GL_UNSIGNED_SHORT_4_4_4_4_REV = 0x8365;
    public static final int GL_UNSIGNED_SHORT_5_5_5_1 = 0x8034;
    public static final int GL_UNSIGNED_SHORT_5_6_5 = 0x8363;
    public static final int GL_UNSIGNED_SHORT_5_6_5_REV = 0x8364;

    public static void glCopyTexSubImage3D(int p0, int p1, int p2, int p3, int p4, int p5, int p6, int p7, int p8) {
        com.github.lodestone.lwjgl3.opengl.GL12.glCopyTexSubImage3D(p0, p1, p2, p3, p4, p5, p6, p7, p8);
    }

    public static void glDrawRangeElements(int p0, int p1, int p2, int p3, int p4, long p5) {
        com.github.lodestone.lwjgl3.opengl.GL12.glDrawRangeElements(p0, p1, p2, p3, p4, p5);
    }

    public static void glDrawRangeElements(int p0, int p1, int p2, java.nio.ByteBuffer p3) {
        com.github.lodestone.lwjgl3.opengl.GL12.glDrawRangeElements(p0, p1, p2, p3);
    }

    public static void glDrawRangeElements(int p0, int p1, int p2, java.nio.IntBuffer p3) {
        com.github.lodestone.lwjgl3.opengl.GL12.glDrawRangeElements(p0, p1, p2, p3);
    }

    public static void glDrawRangeElements(int p0, int p1, int p2, java.nio.ShortBuffer p3) {
        com.github.lodestone.lwjgl3.opengl.GL12.glDrawRangeElements(p0, p1, p2, p3);
    }

    public static void glTexImage3D(int p0, int p1, int p2, int p3, int p4, int p5, int p6, int p7, int p8, long p9) {
        com.github.lodestone.lwjgl3.opengl.GL12.glTexImage3D(p0, p1, p2, p3, p4, p5, p6, p7, p8, p9);
    }

    public static void glTexImage3D(int p0, int p1, int p2, int p3, int p4, int p5, int p6, int p7, int p8, java.nio.ByteBuffer p9) {
        com.github.lodestone.lwjgl3.opengl.GL12.glTexImage3D(p0, p1, p2, p3, p4, p5, p6, p7, p8, p9);
    }

    public static void glTexImage3D(int p0, int p1, int p2, int p3, int p4, int p5, int p6, int p7, int p8, java.nio.DoubleBuffer p9) {
        com.github.lodestone.lwjgl3.opengl.GL12.glTexImage3D(p0, p1, p2, p3, p4, p5, p6, p7, p8, p9);
    }

    public static void glTexImage3D(int p0, int p1, int p2, int p3, int p4, int p5, int p6, int p7, int p8, java.nio.FloatBuffer p9) {
        com.github.lodestone.lwjgl3.opengl.GL12.glTexImage3D(p0, p1, p2, p3, p4, p5, p6, p7, p8, p9);
    }

    public static void glTexImage3D(int p0, int p1, int p2, int p3, int p4, int p5, int p6, int p7, int p8, java.nio.IntBuffer p9) {
        com.github.lodestone.lwjgl3.opengl.GL12.glTexImage3D(p0, p1, p2, p3, p4, p5, p6, p7, p8, p9);
    }

    public static void glTexImage3D(int p0, int p1, int p2, int p3, int p4, int p5, int p6, int p7, int p8, java.nio.ShortBuffer p9) {
        com.github.lodestone.lwjgl3.opengl.GL12.glTexImage3D(p0, p1, p2, p3, p4, p5, p6, p7, p8, p9);
    }

    public static void glTexSubImage3D(int p0, int p1, int p2, int p3, int p4, int p5, int p6, int p7, int p8, int p9, long p10) {
        com.github.lodestone.lwjgl3.opengl.GL12.glTexSubImage3D(p0, p1, p2, p3, p4, p5, p6, p7, p8, p9, p10);
    }

    public static void glTexSubImage3D(int p0, int p1, int p2, int p3, int p4, int p5, int p6, int p7, int p8, int p9, java.nio.ByteBuffer p10) {
        com.github.lodestone.lwjgl3.opengl.GL12.glTexSubImage3D(p0, p1, p2, p3, p4, p5, p6, p7, p8, p9, p10);
    }

    public static void glTexSubImage3D(int p0, int p1, int p2, int p3, int p4, int p5, int p6, int p7, int p8, int p9, java.nio.DoubleBuffer p10) {
        com.github.lodestone.lwjgl3.opengl.GL12.glTexSubImage3D(p0, p1, p2, p3, p4, p5, p6, p7, p8, p9, p10);
    }

    public static void glTexSubImage3D(int p0, int p1, int p2, int p3, int p4, int p5, int p6, int p7, int p8, int p9, java.nio.FloatBuffer p10) {
        com.github.lodestone.lwjgl3.opengl.GL12.glTexSubImage3D(p0, p1, p2, p3, p4, p5, p6, p7, p8, p9, p10);
    }

    public static void glTexSubImage3D(int p0, int p1, int p2, int p3, int p4, int p5, int p6, int p7, int p8, int p9, java.nio.IntBuffer p10) {
        com.github.lodestone.lwjgl3.opengl.GL12.glTexSubImage3D(p0, p1, p2, p3, p4, p5, p6, p7, p8, p9, p10);
    }

    public static void glTexSubImage3D(int p0, int p1, int p2, int p3, int p4, int p5, int p6, int p7, int p8, int p9, java.nio.ShortBuffer p10) {
        com.github.lodestone.lwjgl3.opengl.GL12.glTexSubImage3D(p0, p1, p2, p3, p4, p5, p6, p7, p8, p9, p10);
    }

    private GL12() {
    }
}
