// Generated by runtime/generate-lwjgl2-bindings.py. Do not edit.
//
// LWJGL 2's GL13. Every method forwards to LWJGL 3's binding of the same GL
// function, reached through the package the compatibility jar relocates
// LWJGL 3's OpenGL module into. The constants are LWJGL 2's own values.
package org.lwjgl.opengl;

public final class GL13 {

    public static final int GL_ACTIVE_TEXTURE = 0x84E0;
    public static final int GL_ADD_SIGNED = 0x8574;
    public static final int GL_CLAMP_TO_BORDER = 0x812D;
    public static final int GL_CLIENT_ACTIVE_TEXTURE = 0x84E1;
    public static final int GL_COMBINE = 0x8570;
    public static final int GL_COMBINE_ALPHA = 0x8572;
    public static final int GL_COMBINE_RGB = 0x8571;
    public static final int GL_COMPRESSED_ALPHA = 0x84E9;
    public static final int GL_COMPRESSED_INTENSITY = 0x84EC;
    public static final int GL_COMPRESSED_LUMINANCE = 0x84EA;
    public static final int GL_COMPRESSED_LUMINANCE_ALPHA = 0x84EB;
    public static final int GL_COMPRESSED_RGB = 0x84ED;
    public static final int GL_COMPRESSED_RGBA = 0x84EE;
    public static final int GL_COMPRESSED_TEXTURE_FORMATS = 0x86A3;
    public static final int GL_CONSTANT = 0x8576;
    public static final int GL_DOT3_RGB = 0x86AE;
    public static final int GL_DOT3_RGBA = 0x86AF;
    public static final int GL_INTERPOLATE = 0x8575;
    public static final int GL_MAX_CUBE_MAP_TEXTURE_SIZE = 0x851C;
    public static final int GL_MAX_TEXTURE_UNITS = 0x84E2;
    public static final int GL_MULTISAMPLE = 0x809D;
    public static final int GL_MULTISAMPLE_BIT = 0x20000000;
    public static final int GL_NORMAL_MAP = 0x8511;
    public static final int GL_NUM_COMPRESSED_TEXTURE_FORMATS = 0x86A2;
    public static final int GL_OPERAND0_ALPHA = 0x8598;
    public static final int GL_OPERAND0_RGB = 0x8590;
    public static final int GL_OPERAND1_ALPHA = 0x8599;
    public static final int GL_OPERAND1_RGB = 0x8591;
    public static final int GL_OPERAND2_ALPHA = 0x859A;
    public static final int GL_OPERAND2_RGB = 0x8592;
    public static final int GL_PREVIOUS = 0x8578;
    public static final int GL_PRIMARY_COLOR = 0x8577;
    public static final int GL_PROXY_TEXTURE_CUBE_MAP = 0x851B;
    public static final int GL_REFLECTION_MAP = 0x8512;
    public static final int GL_RGB_SCALE = 0x8573;
    public static final int GL_SAMPLES = 0x80A9;
    public static final int GL_SAMPLE_ALPHA_TO_COVERAGE = 0x809E;
    public static final int GL_SAMPLE_ALPHA_TO_ONE = 0x809F;
    public static final int GL_SAMPLE_BUFFERS = 0x80A8;
    public static final int GL_SAMPLE_COVERAGE = 0x80A0;
    public static final int GL_SAMPLE_COVERAGE_INVERT = 0x80AB;
    public static final int GL_SAMPLE_COVERAGE_VALUE = 0x80AA;
    public static final int GL_SOURCE0_ALPHA = 0x8588;
    public static final int GL_SOURCE0_RGB = 0x8580;
    public static final int GL_SOURCE1_ALPHA = 0x8589;
    public static final int GL_SOURCE1_RGB = 0x8581;
    public static final int GL_SOURCE2_ALPHA = 0x858A;
    public static final int GL_SOURCE2_RGB = 0x8582;
    public static final int GL_SUBTRACT = 0x84E7;
    public static final int GL_TEXTURE0 = 0x84C0;
    public static final int GL_TEXTURE1 = 0x84C1;
    public static final int GL_TEXTURE10 = 0x84CA;
    public static final int GL_TEXTURE11 = 0x84CB;
    public static final int GL_TEXTURE12 = 0x84CC;
    public static final int GL_TEXTURE13 = 0x84CD;
    public static final int GL_TEXTURE14 = 0x84CE;
    public static final int GL_TEXTURE15 = 0x84CF;
    public static final int GL_TEXTURE16 = 0x84D0;
    public static final int GL_TEXTURE17 = 0x84D1;
    public static final int GL_TEXTURE18 = 0x84D2;
    public static final int GL_TEXTURE19 = 0x84D3;
    public static final int GL_TEXTURE2 = 0x84C2;
    public static final int GL_TEXTURE20 = 0x84D4;
    public static final int GL_TEXTURE21 = 0x84D5;
    public static final int GL_TEXTURE22 = 0x84D6;
    public static final int GL_TEXTURE23 = 0x84D7;
    public static final int GL_TEXTURE24 = 0x84D8;
    public static final int GL_TEXTURE25 = 0x84D9;
    public static final int GL_TEXTURE26 = 0x84DA;
    public static final int GL_TEXTURE27 = 0x84DB;
    public static final int GL_TEXTURE28 = 0x84DC;
    public static final int GL_TEXTURE29 = 0x84DD;
    public static final int GL_TEXTURE3 = 0x84C3;
    public static final int GL_TEXTURE30 = 0x84DE;
    public static final int GL_TEXTURE31 = 0x84DF;
    public static final int GL_TEXTURE4 = 0x84C4;
    public static final int GL_TEXTURE5 = 0x84C5;
    public static final int GL_TEXTURE6 = 0x84C6;
    public static final int GL_TEXTURE7 = 0x84C7;
    public static final int GL_TEXTURE8 = 0x84C8;
    public static final int GL_TEXTURE9 = 0x84C9;
    public static final int GL_TEXTURE_BINDING_CUBE_MAP = 0x8514;
    public static final int GL_TEXTURE_COMPRESSED = 0x86A1;
    public static final int GL_TEXTURE_COMPRESSED_IMAGE_SIZE = 0x86A0;
    public static final int GL_TEXTURE_COMPRESSION_HINT = 0x84EF;
    public static final int GL_TEXTURE_CUBE_MAP = 0x8513;
    public static final int GL_TEXTURE_CUBE_MAP_NEGATIVE_X = 0x8516;
    public static final int GL_TEXTURE_CUBE_MAP_NEGATIVE_Y = 0x8518;
    public static final int GL_TEXTURE_CUBE_MAP_NEGATIVE_Z = 0x851A;
    public static final int GL_TEXTURE_CUBE_MAP_POSITIVE_X = 0x8515;
    public static final int GL_TEXTURE_CUBE_MAP_POSITIVE_Y = 0x8517;
    public static final int GL_TEXTURE_CUBE_MAP_POSITIVE_Z = 0x8519;
    public static final int GL_TRANSPOSE_COLOR_MATRIX = 0x84E6;
    public static final int GL_TRANSPOSE_MODELVIEW_MATRIX = 0x84E3;
    public static final int GL_TRANSPOSE_PROJECTION_MATRIX = 0x84E4;
    public static final int GL_TRANSPOSE_TEXTURE_MATRIX = 0x84E5;

    public static void glActiveTexture(int p0) {
        com.github.lodestone.lwjgl3.opengl.GL13.glActiveTexture(p0);
    }

    public static void glClientActiveTexture(int p0) {
        com.github.lodestone.lwjgl3.opengl.GL13.glClientActiveTexture(p0);
    }

    public static void glCompressedTexImage1D(int p0, int p1, int p2, int p3, int p4, int p5, long p6) {
        com.github.lodestone.lwjgl3.opengl.GL13.glCompressedTexImage1D(p0, p1, p2, p3, p4, p5, p6);
    }

    public static void glCompressedTexImage1D(int p0, int p1, int p2, int p3, int p4, java.nio.ByteBuffer p5) {
        com.github.lodestone.lwjgl3.opengl.GL13.glCompressedTexImage1D(p0, p1, p2, p3, p4, p5);
    }

    public static void glCompressedTexImage2D(int p0, int p1, int p2, int p3, int p4, int p5, int p6, long p7) {
        com.github.lodestone.lwjgl3.opengl.GL13.glCompressedTexImage2D(p0, p1, p2, p3, p4, p5, p6, p7);
    }

    public static void glCompressedTexImage2D(int p0, int p1, int p2, int p3, int p4, int p5, java.nio.ByteBuffer p6) {
        com.github.lodestone.lwjgl3.opengl.GL13.glCompressedTexImage2D(p0, p1, p2, p3, p4, p5, p6);
    }

    public static void glCompressedTexImage3D(int p0, int p1, int p2, int p3, int p4, int p5, int p6, int p7, long p8) {
        com.github.lodestone.lwjgl3.opengl.GL13.glCompressedTexImage3D(p0, p1, p2, p3, p4, p5, p6, p7, p8);
    }

    public static void glCompressedTexImage3D(int p0, int p1, int p2, int p3, int p4, int p5, int p6, java.nio.ByteBuffer p7) {
        com.github.lodestone.lwjgl3.opengl.GL13.glCompressedTexImage3D(p0, p1, p2, p3, p4, p5, p6, p7);
    }

    public static void glCompressedTexSubImage1D(int p0, int p1, int p2, int p3, int p4, int p5, long p6) {
        com.github.lodestone.lwjgl3.opengl.GL13.glCompressedTexSubImage1D(p0, p1, p2, p3, p4, p5, p6);
    }

    public static void glCompressedTexSubImage1D(int p0, int p1, int p2, int p3, int p4, java.nio.ByteBuffer p5) {
        com.github.lodestone.lwjgl3.opengl.GL13.glCompressedTexSubImage1D(p0, p1, p2, p3, p4, p5);
    }

    public static void glCompressedTexSubImage2D(int p0, int p1, int p2, int p3, int p4, int p5, int p6, int p7, long p8) {
        com.github.lodestone.lwjgl3.opengl.GL13.glCompressedTexSubImage2D(p0, p1, p2, p3, p4, p5, p6, p7, p8);
    }

    public static void glCompressedTexSubImage2D(int p0, int p1, int p2, int p3, int p4, int p5, int p6, java.nio.ByteBuffer p7) {
        com.github.lodestone.lwjgl3.opengl.GL13.glCompressedTexSubImage2D(p0, p1, p2, p3, p4, p5, p6, p7);
    }

    public static void glCompressedTexSubImage3D(int p0, int p1, int p2, int p3, int p4, int p5, int p6, int p7, int p8, int p9, long p10) {
        com.github.lodestone.lwjgl3.opengl.GL13.glCompressedTexSubImage3D(p0, p1, p2, p3, p4, p5, p6, p7, p8, p9, p10);
    }

    public static void glCompressedTexSubImage3D(int p0, int p1, int p2, int p3, int p4, int p5, int p6, int p7, int p8, java.nio.ByteBuffer p9) {
        com.github.lodestone.lwjgl3.opengl.GL13.glCompressedTexSubImage3D(p0, p1, p2, p3, p4, p5, p6, p7, p8, p9);
    }

    public static void glGetCompressedTexImage(int p0, int p1, long p2) {
        com.github.lodestone.lwjgl3.opengl.GL13.glGetCompressedTexImage(p0, p1, p2);
    }

    public static void glGetCompressedTexImage(int p0, int p1, java.nio.ByteBuffer p2) {
        com.github.lodestone.lwjgl3.opengl.GL13.glGetCompressedTexImage(p0, p1, p2);
    }

    public static void glLoadTransposeMatrix(java.nio.DoubleBuffer p0) {
        com.github.lodestone.lwjgl3.opengl.GL13.glLoadTransposeMatrixd(p0);
    }

    public static void glLoadTransposeMatrix(java.nio.FloatBuffer p0) {
        com.github.lodestone.lwjgl3.opengl.GL13.glLoadTransposeMatrixf(p0);
    }

    public static void glMultTransposeMatrix(java.nio.DoubleBuffer p0) {
        com.github.lodestone.lwjgl3.opengl.GL13.glMultTransposeMatrixd(p0);
    }

    public static void glMultTransposeMatrix(java.nio.FloatBuffer p0) {
        com.github.lodestone.lwjgl3.opengl.GL13.glMultTransposeMatrixf(p0);
    }

    public static void glMultiTexCoord1d(int p0, double p1) {
        com.github.lodestone.lwjgl3.opengl.GL13.glMultiTexCoord1d(p0, p1);
    }

    public static void glMultiTexCoord1f(int p0, float p1) {
        com.github.lodestone.lwjgl3.opengl.GL13.glMultiTexCoord1f(p0, p1);
    }

    public static void glMultiTexCoord2d(int p0, double p1, double p2) {
        com.github.lodestone.lwjgl3.opengl.GL13.glMultiTexCoord2d(p0, p1, p2);
    }

    public static void glMultiTexCoord2f(int p0, float p1, float p2) {
        com.github.lodestone.lwjgl3.opengl.GL13.glMultiTexCoord2f(p0, p1, p2);
    }

    public static void glMultiTexCoord3d(int p0, double p1, double p2, double p3) {
        com.github.lodestone.lwjgl3.opengl.GL13.glMultiTexCoord3d(p0, p1, p2, p3);
    }

    public static void glMultiTexCoord3f(int p0, float p1, float p2, float p3) {
        com.github.lodestone.lwjgl3.opengl.GL13.glMultiTexCoord3f(p0, p1, p2, p3);
    }

    public static void glMultiTexCoord4d(int p0, double p1, double p2, double p3, double p4) {
        com.github.lodestone.lwjgl3.opengl.GL13.glMultiTexCoord4d(p0, p1, p2, p3, p4);
    }

    public static void glMultiTexCoord4f(int p0, float p1, float p2, float p3, float p4) {
        com.github.lodestone.lwjgl3.opengl.GL13.glMultiTexCoord4f(p0, p1, p2, p3, p4);
    }

    public static void glSampleCoverage(float p0, boolean p1) {
        com.github.lodestone.lwjgl3.opengl.GL13.glSampleCoverage(p0, p1);
    }

    private GL13() {
    }
}
