// Generated by runtime/generate-lwjgl2-bindings.py. Do not edit.
//
// LWJGL 2's GL14. Every method forwards to LWJGL 3's binding of the same GL
// function, reached through the package the compatibility jar relocates
// LWJGL 3's OpenGL module into. The constants are LWJGL 2's own values.
package org.lwjgl.opengl;

public final class GL14 {

    public static final int GL_BLEND_COLOR = 0x8005;
    public static final int GL_BLEND_DST_ALPHA = 0x80CA;
    public static final int GL_BLEND_DST_RGB = 0x80C8;
    public static final int GL_BLEND_EQUATION = 0x8009;
    public static final int GL_BLEND_SRC_ALPHA = 0x80CB;
    public static final int GL_BLEND_SRC_RGB = 0x80C9;
    public static final int GL_COLOR_SUM = 0x8458;
    public static final int GL_COMPARE_R_TO_TEXTURE = 0x884E;
    public static final int GL_CURRENT_FOG_COORDINATE = 0x8453;
    public static final int GL_CURRENT_SECONDARY_COLOR = 0x8459;
    public static final int GL_DECR_WRAP = 0x8508;
    public static final int GL_DEPTH_COMPONENT16 = 0x81A5;
    public static final int GL_DEPTH_COMPONENT24 = 0x81A6;
    public static final int GL_DEPTH_COMPONENT32 = 0x81A7;
    public static final int GL_DEPTH_TEXTURE_MODE = 0x884B;
    public static final int GL_FOG_COORDINATE = 0x8451;
    public static final int GL_FOG_COORDINATE_ARRAY = 0x8457;
    public static final int GL_FOG_COORDINATE_ARRAY_POINTER = 0x8456;
    public static final int GL_FOG_COORDINATE_ARRAY_STRIDE = 0x8455;
    public static final int GL_FOG_COORDINATE_ARRAY_TYPE = 0x8454;
    public static final int GL_FOG_COORDINATE_SOURCE = 0x8450;
    public static final int GL_FRAGMENT_DEPTH = 0x8452;
    public static final int GL_FUNC_ADD = 0x8006;
    public static final int GL_FUNC_REVERSE_SUBTRACT = 0x800B;
    public static final int GL_FUNC_SUBTRACT = 0x800A;
    public static final int GL_GENERATE_MIPMAP = 0x8191;
    public static final int GL_GENERATE_MIPMAP_HINT = 0x8192;
    public static final int GL_INCR_WRAP = 0x8507;
    public static final int GL_MAX = 0x8008;
    public static final int GL_MAX_TEXTURE_LOD_BIAS = 0x84FD;
    public static final int GL_MIN = 0x8007;
    public static final int GL_MIRRORED_REPEAT = 0x8370;
    public static final int GL_POINT_DISTANCE_ATTENUATION = 0x8129;
    public static final int GL_POINT_FADE_THRESHOLD_SIZE = 0x8128;
    public static final int GL_POINT_SIZE_MAX = 0x8127;
    public static final int GL_POINT_SIZE_MIN = 0x8126;
    public static final int GL_SECONDARY_COLOR_ARRAY = 0x845E;
    public static final int GL_SECONDARY_COLOR_ARRAY_POINTER = 0x845D;
    public static final int GL_SECONDARY_COLOR_ARRAY_SIZE = 0x845A;
    public static final int GL_SECONDARY_COLOR_ARRAY_STRIDE = 0x845C;
    public static final int GL_SECONDARY_COLOR_ARRAY_TYPE = 0x845B;
    public static final int GL_TEXTURE_COMPARE_FUNC = 0x884D;
    public static final int GL_TEXTURE_COMPARE_MODE = 0x884C;
    public static final int GL_TEXTURE_DEPTH_SIZE = 0x884A;
    public static final int GL_TEXTURE_FILTER_CONTROL = 0x8500;
    public static final int GL_TEXTURE_LOD_BIAS = 0x8501;

    public static void glBlendColor(float p0, float p1, float p2, float p3) {
        com.github.lodestone.lwjgl3.opengl.GL14.glBlendColor(p0, p1, p2, p3);
    }

    public static void glBlendEquation(int p0) {
        com.github.lodestone.lwjgl3.opengl.GL14.glBlendEquation(p0);
    }

    public static void glBlendFuncSeparate(int p0, int p1, int p2, int p3) {
        com.github.lodestone.lwjgl3.opengl.GL14.glBlendFuncSeparate(p0, p1, p2, p3);
    }

    public static void glFogCoordPointer(int p0, int p1, long p2) {
        com.github.lodestone.lwjgl3.opengl.GL14.glFogCoordPointer(p0, p1, p2);
    }

    public static void glFogCoordd(double p0) {
        com.github.lodestone.lwjgl3.opengl.GL14.glFogCoordd(p0);
    }

    public static void glFogCoordf(float p0) {
        com.github.lodestone.lwjgl3.opengl.GL14.glFogCoordf(p0);
    }

    public static void glMultiDrawArrays(int p0, java.nio.IntBuffer p1, java.nio.IntBuffer p2) {
        com.github.lodestone.lwjgl3.opengl.GL14.glMultiDrawArrays(p0, p1, p2);
    }

    public static void glPointParameter(int p0, java.nio.FloatBuffer p1) {
        com.github.lodestone.lwjgl3.opengl.GL14.glPointParameterfv(p0, p1);
    }

    public static void glPointParameter(int p0, java.nio.IntBuffer p1) {
        com.github.lodestone.lwjgl3.opengl.GL14.glPointParameteriv(p0, p1);
    }

    public static void glPointParameterf(int p0, float p1) {
        com.github.lodestone.lwjgl3.opengl.GL14.glPointParameterf(p0, p1);
    }

    public static void glPointParameteri(int p0, int p1) {
        com.github.lodestone.lwjgl3.opengl.GL14.glPointParameteri(p0, p1);
    }

    public static void glSecondaryColor3b(byte p0, byte p1, byte p2) {
        com.github.lodestone.lwjgl3.opengl.GL14.glSecondaryColor3b(p0, p1, p2);
    }

    public static void glSecondaryColor3d(double p0, double p1, double p2) {
        com.github.lodestone.lwjgl3.opengl.GL14.glSecondaryColor3d(p0, p1, p2);
    }

    public static void glSecondaryColor3f(float p0, float p1, float p2) {
        com.github.lodestone.lwjgl3.opengl.GL14.glSecondaryColor3f(p0, p1, p2);
    }

    public static void glSecondaryColor3ub(byte p0, byte p1, byte p2) {
        com.github.lodestone.lwjgl3.opengl.GL14.glSecondaryColor3ub(p0, p1, p2);
    }

    public static void glSecondaryColorPointer(int p0, int p1, int p2, long p3) {
        com.github.lodestone.lwjgl3.opengl.GL14.glSecondaryColorPointer(p0, p1, p2, p3);
    }

    public static void glWindowPos2d(double p0, double p1) {
        com.github.lodestone.lwjgl3.opengl.GL14.glWindowPos2d(p0, p1);
    }

    public static void glWindowPos2f(float p0, float p1) {
        com.github.lodestone.lwjgl3.opengl.GL14.glWindowPos2f(p0, p1);
    }

    public static void glWindowPos2i(int p0, int p1) {
        com.github.lodestone.lwjgl3.opengl.GL14.glWindowPos2i(p0, p1);
    }

    public static void glWindowPos3d(double p0, double p1, double p2) {
        com.github.lodestone.lwjgl3.opengl.GL14.glWindowPos3d(p0, p1, p2);
    }

    public static void glWindowPos3f(float p0, float p1, float p2) {
        com.github.lodestone.lwjgl3.opengl.GL14.glWindowPos3f(p0, p1, p2);
    }

    public static void glWindowPos3i(int p0, int p1, int p2) {
        com.github.lodestone.lwjgl3.opengl.GL14.glWindowPos3i(p0, p1, p2);
    }

    private GL14() {
    }
}
