// Generated by runtime/generate-lwjgl2-bindings.py. Do not edit.
//
// LWJGL 2's GL15. Every method forwards to LWJGL 3's binding of the same GL
// function, reached through the package the compatibility jar relocates
// LWJGL 3's OpenGL module into. The constants are LWJGL 2's own values.
package org.lwjgl.opengl;

public final class GL15 {

    public static final int GL_ARRAY_BUFFER = 0x8892;
    public static final int GL_ARRAY_BUFFER_BINDING = 0x8894;
    public static final int GL_BUFFER_ACCESS = 0x88BB;
    public static final int GL_BUFFER_MAPPED = 0x88BC;
    public static final int GL_BUFFER_MAP_POINTER = 0x88BD;
    public static final int GL_BUFFER_SIZE = 0x8764;
    public static final int GL_BUFFER_USAGE = 0x8765;
    public static final int GL_COLOR_ARRAY_BUFFER_BINDING = 0x8898;
    public static final int GL_CURRENT_FOG_COORD = 0x8453;
    public static final int GL_CURRENT_QUERY = 0x8865;
    public static final int GL_DYNAMIC_COPY = 0x88EA;
    public static final int GL_DYNAMIC_DRAW = 0x88E8;
    public static final int GL_DYNAMIC_READ = 0x88E9;
    public static final int GL_EDGE_FLAG_ARRAY_BUFFER_BINDING = 0x889B;
    public static final int GL_ELEMENT_ARRAY_BUFFER = 0x8893;
    public static final int GL_ELEMENT_ARRAY_BUFFER_BINDING = 0x8895;
    public static final int GL_FOG_COORD = 0x8451;
    public static final int GL_FOG_COORDINATE_ARRAY_BUFFER_BINDING = 0x889D;
    public static final int GL_FOG_COORD_ARRAY = 0x8457;
    public static final int GL_FOG_COORD_ARRAY_BUFFER_BINDING = 0x889D;
    public static final int GL_FOG_COORD_ARRAY_POINTER = 0x8456;
    public static final int GL_FOG_COORD_ARRAY_STRIDE = 0x8455;
    public static final int GL_FOG_COORD_ARRAY_TYPE = 0x8454;
    public static final int GL_FOG_COORD_SRC = 0x8450;
    public static final int GL_INDEX_ARRAY_BUFFER_BINDING = 0x8899;
    public static final int GL_NORMAL_ARRAY_BUFFER_BINDING = 0x8897;
    public static final int GL_QUERY_COUNTER_BITS = 0x8864;
    public static final int GL_QUERY_RESULT = 0x8866;
    public static final int GL_QUERY_RESULT_AVAILABLE = 0x8867;
    public static final int GL_READ_ONLY = 0x88B8;
    public static final int GL_READ_WRITE = 0x88BA;
    public static final int GL_SAMPLES_PASSED = 0x8914;
    public static final int GL_SECONDARY_COLOR_ARRAY_BUFFER_BINDING = 0x889C;
    public static final int GL_SRC0_ALPHA = 0x8588;
    public static final int GL_SRC0_RGB = 0x8580;
    public static final int GL_SRC1_ALPHA = 0x8589;
    public static final int GL_SRC1_RGB = 0x8581;
    public static final int GL_SRC2_ALPHA = 0x858A;
    public static final int GL_SRC2_RGB = 0x8582;
    public static final int GL_STATIC_COPY = 0x88E6;
    public static final int GL_STATIC_DRAW = 0x88E4;
    public static final int GL_STATIC_READ = 0x88E5;
    public static final int GL_STREAM_COPY = 0x88E2;
    public static final int GL_STREAM_DRAW = 0x88E0;
    public static final int GL_STREAM_READ = 0x88E1;
    public static final int GL_TEXTURE_COORD_ARRAY_BUFFER_BINDING = 0x889A;
    public static final int GL_VERTEX_ARRAY_BUFFER_BINDING = 0x8896;
    public static final int GL_VERTEX_ATTRIB_ARRAY_BUFFER_BINDING = 0x889F;
    public static final int GL_WEIGHT_ARRAY_BUFFER_BINDING = 0x889E;
    public static final int GL_WRITE_ONLY = 0x88B9;

    public static void glBeginQuery(int p0, int p1) {
        com.github.lodestone.lwjgl3.opengl.GL15.glBeginQuery(p0, p1);
    }

    public static void glBindBuffer(int p0, int p1) {
        com.github.lodestone.lwjgl3.opengl.GL15.glBindBuffer(p0, p1);
    }

    public static void glBufferData(int p0, long p1, int p2) {
        com.github.lodestone.lwjgl3.opengl.GL15.glBufferData(p0, p1, p2);
    }

    public static void glBufferData(int p0, java.nio.ByteBuffer p1, int p2) {
        com.github.lodestone.lwjgl3.opengl.GL15.glBufferData(p0, p1, p2);
    }

    public static void glBufferData(int p0, java.nio.DoubleBuffer p1, int p2) {
        com.github.lodestone.lwjgl3.opengl.GL15.glBufferData(p0, p1, p2);
    }

    public static void glBufferData(int p0, java.nio.FloatBuffer p1, int p2) {
        com.github.lodestone.lwjgl3.opengl.GL15.glBufferData(p0, p1, p2);
    }

    public static void glBufferData(int p0, java.nio.IntBuffer p1, int p2) {
        com.github.lodestone.lwjgl3.opengl.GL15.glBufferData(p0, p1, p2);
    }

    public static void glBufferData(int p0, java.nio.ShortBuffer p1, int p2) {
        com.github.lodestone.lwjgl3.opengl.GL15.glBufferData(p0, p1, p2);
    }

    public static void glBufferSubData(int p0, long p1, java.nio.ByteBuffer p2) {
        com.github.lodestone.lwjgl3.opengl.GL15.glBufferSubData(p0, p1, p2);
    }

    public static void glBufferSubData(int p0, long p1, java.nio.DoubleBuffer p2) {
        com.github.lodestone.lwjgl3.opengl.GL15.glBufferSubData(p0, p1, p2);
    }

    public static void glBufferSubData(int p0, long p1, java.nio.FloatBuffer p2) {
        com.github.lodestone.lwjgl3.opengl.GL15.glBufferSubData(p0, p1, p2);
    }

    public static void glBufferSubData(int p0, long p1, java.nio.IntBuffer p2) {
        com.github.lodestone.lwjgl3.opengl.GL15.glBufferSubData(p0, p1, p2);
    }

    public static void glBufferSubData(int p0, long p1, java.nio.ShortBuffer p2) {
        com.github.lodestone.lwjgl3.opengl.GL15.glBufferSubData(p0, p1, p2);
    }

    public static void glDeleteBuffers(int p0) {
        com.github.lodestone.lwjgl3.opengl.GL15.glDeleteBuffers(p0);
    }

    public static void glDeleteBuffers(java.nio.IntBuffer p0) {
        com.github.lodestone.lwjgl3.opengl.GL15.glDeleteBuffers(p0);
    }

    public static void glDeleteQueries(int p0) {
        com.github.lodestone.lwjgl3.opengl.GL15.glDeleteQueries(p0);
    }

    public static void glDeleteQueries(java.nio.IntBuffer p0) {
        com.github.lodestone.lwjgl3.opengl.GL15.glDeleteQueries(p0);
    }

    public static void glEndQuery(int p0) {
        com.github.lodestone.lwjgl3.opengl.GL15.glEndQuery(p0);
    }

    public static int glGenBuffers() {
        return com.github.lodestone.lwjgl3.opengl.GL15.glGenBuffers();
    }

    public static void glGenBuffers(java.nio.IntBuffer p0) {
        com.github.lodestone.lwjgl3.opengl.GL15.glGenBuffers(p0);
    }

    public static int glGenQueries() {
        return com.github.lodestone.lwjgl3.opengl.GL15.glGenQueries();
    }

    public static void glGenQueries(java.nio.IntBuffer p0) {
        com.github.lodestone.lwjgl3.opengl.GL15.glGenQueries(p0);
    }

    public static void glGetBufferParameter(int p0, int p1, java.nio.IntBuffer p2) {
        com.github.lodestone.lwjgl3.opengl.GL15.glGetBufferParameteriv(p0, p1, p2);
    }

    public static int glGetBufferParameteri(int p0, int p1) {
        return com.github.lodestone.lwjgl3.opengl.GL15.glGetBufferParameteri(p0, p1);
    }

    public static void glGetBufferSubData(int p0, long p1, java.nio.ByteBuffer p2) {
        com.github.lodestone.lwjgl3.opengl.GL15.glGetBufferSubData(p0, p1, p2);
    }

    public static void glGetBufferSubData(int p0, long p1, java.nio.DoubleBuffer p2) {
        com.github.lodestone.lwjgl3.opengl.GL15.glGetBufferSubData(p0, p1, p2);
    }

    public static void glGetBufferSubData(int p0, long p1, java.nio.FloatBuffer p2) {
        com.github.lodestone.lwjgl3.opengl.GL15.glGetBufferSubData(p0, p1, p2);
    }

    public static void glGetBufferSubData(int p0, long p1, java.nio.IntBuffer p2) {
        com.github.lodestone.lwjgl3.opengl.GL15.glGetBufferSubData(p0, p1, p2);
    }

    public static void glGetBufferSubData(int p0, long p1, java.nio.ShortBuffer p2) {
        com.github.lodestone.lwjgl3.opengl.GL15.glGetBufferSubData(p0, p1, p2);
    }

    public static void glGetQuery(int p0, int p1, java.nio.IntBuffer p2) {
        com.github.lodestone.lwjgl3.opengl.GL15.glGetQueryiv(p0, p1, p2);
    }

    public static void glGetQueryObject(int p0, int p1, java.nio.IntBuffer p2) {
        com.github.lodestone.lwjgl3.opengl.GL15.glGetQueryObjectiv(p0, p1, p2);
    }

    public static int glGetQueryObjecti(int p0, int p1) {
        return com.github.lodestone.lwjgl3.opengl.GL15.glGetQueryObjecti(p0, p1);
    }

    public static void glGetQueryObjectu(int p0, int p1, java.nio.IntBuffer p2) {
        com.github.lodestone.lwjgl3.opengl.GL15.glGetQueryObjectuiv(p0, p1, p2);
    }

    public static int glGetQueryObjectui(int p0, int p1) {
        return com.github.lodestone.lwjgl3.opengl.GL15.glGetQueryObjectui(p0, p1);
    }

    public static int glGetQueryi(int p0, int p1) {
        return com.github.lodestone.lwjgl3.opengl.GL15.glGetQueryi(p0, p1);
    }

    public static boolean glIsBuffer(int p0) {
        return com.github.lodestone.lwjgl3.opengl.GL15.glIsBuffer(p0);
    }

    public static boolean glIsQuery(int p0) {
        return com.github.lodestone.lwjgl3.opengl.GL15.glIsQuery(p0);
    }

    public static java.nio.ByteBuffer glMapBuffer(int p0, int p1, long p2, java.nio.ByteBuffer p3) {
        return com.github.lodestone.lwjgl3.opengl.GL15.glMapBuffer(p0, p1, p2, p3);
    }

    public static java.nio.ByteBuffer glMapBuffer(int p0, int p1, java.nio.ByteBuffer p2) {
        return com.github.lodestone.lwjgl3.opengl.GL15.glMapBuffer(p0, p1, p2);
    }

    public static boolean glUnmapBuffer(int p0) {
        return com.github.lodestone.lwjgl3.opengl.GL15.glUnmapBuffer(p0);
    }

    private GL15() {
    }
}
