// Generated by runtime/generate-lwjgl2-bindings.py. Do not edit.
//
// LWJGL 2's GL20. Every method forwards to LWJGL 3's binding of the same GL
// function, reached through the package the compatibility jar relocates
// LWJGL 3's OpenGL module into. The constants are LWJGL 2's own values.
package org.lwjgl.opengl;

public final class GL20 {

    public static final int GL_ACTIVE_ATTRIBUTES = 0x8B89;
    public static final int GL_ACTIVE_ATTRIBUTE_MAX_LENGTH = 0x8B8A;
    public static final int GL_ACTIVE_UNIFORMS = 0x8B86;
    public static final int GL_ACTIVE_UNIFORM_MAX_LENGTH = 0x8B87;
    public static final int GL_ATTACHED_SHADERS = 0x8B85;
    public static final int GL_BLEND_EQUATION_ALPHA = 0x883D;
    public static final int GL_BLEND_EQUATION_RGB = 0x8009;
    public static final int GL_BOOL = 0x8B56;
    public static final int GL_BOOL_VEC2 = 0x8B57;
    public static final int GL_BOOL_VEC3 = 0x8B58;
    public static final int GL_BOOL_VEC4 = 0x8B59;
    public static final int GL_COMPILE_STATUS = 0x8B81;
    public static final int GL_COORD_REPLACE = 0x8862;
    public static final int GL_CURRENT_PROGRAM = 0x8B8D;
    public static final int GL_CURRENT_VERTEX_ATTRIB = 0x8626;
    public static final int GL_DELETE_STATUS = 0x8B80;
    public static final int GL_DRAW_BUFFER0 = 0x8825;
    public static final int GL_DRAW_BUFFER1 = 0x8826;
    public static final int GL_DRAW_BUFFER10 = 0x882F;
    public static final int GL_DRAW_BUFFER11 = 0x8830;
    public static final int GL_DRAW_BUFFER12 = 0x8831;
    public static final int GL_DRAW_BUFFER13 = 0x8832;
    public static final int GL_DRAW_BUFFER14 = 0x8833;
    public static final int GL_DRAW_BUFFER15 = 0x8834;
    public static final int GL_DRAW_BUFFER2 = 0x8827;
    public static final int GL_DRAW_BUFFER3 = 0x8828;
    public static final int GL_DRAW_BUFFER4 = 0x8829;
    public static final int GL_DRAW_BUFFER5 = 0x882A;
    public static final int GL_DRAW_BUFFER6 = 0x882B;
    public static final int GL_DRAW_BUFFER7 = 0x882C;
    public static final int GL_DRAW_BUFFER8 = 0x882D;
    public static final int GL_DRAW_BUFFER9 = 0x882E;
    public static final int GL_FLOAT_MAT2 = 0x8B5A;
    public static final int GL_FLOAT_MAT3 = 0x8B5B;
    public static final int GL_FLOAT_MAT4 = 0x8B5C;
    public static final int GL_FLOAT_VEC2 = 0x8B50;
    public static final int GL_FLOAT_VEC3 = 0x8B51;
    public static final int GL_FLOAT_VEC4 = 0x8B52;
    public static final int GL_FRAGMENT_SHADER = 0x8B30;
    public static final int GL_FRAGMENT_SHADER_DERIVATIVE_HINT = 0x8B8B;
    public static final int GL_INFO_LOG_LENGTH = 0x8B84;
    public static final int GL_INT_VEC2 = 0x8B53;
    public static final int GL_INT_VEC3 = 0x8B54;
    public static final int GL_INT_VEC4 = 0x8B55;
    public static final int GL_LINK_STATUS = 0x8B82;
    public static final int GL_LOWER_LEFT = 0x8CA1;
    public static final int GL_MAX_COMBINED_TEXTURE_IMAGE_UNITS = 0x8B4D;
    public static final int GL_MAX_DRAW_BUFFERS = 0x8824;
    public static final int GL_MAX_FRAGMENT_UNIFORM_COMPONENTS = 0x8B49;
    public static final int GL_MAX_TEXTURE_COORDS = 0x8871;
    public static final int GL_MAX_TEXTURE_IMAGE_UNITS = 0x8872;
    public static final int GL_MAX_VARYING_FLOATS = 0x8B4B;
    public static final int GL_MAX_VERTEX_ATTRIBS = 0x8869;
    public static final int GL_MAX_VERTEX_TEXTURE_IMAGE_UNITS = 0x8B4C;
    public static final int GL_MAX_VERTEX_UNIFORM_COMPONENTS = 0x8B4A;
    public static final int GL_POINT_SPRITE = 0x8861;
    public static final int GL_POINT_SPRITE_COORD_ORIGIN = 0x8CA0;
    public static final int GL_SAMPLER_1D = 0x8B5D;
    public static final int GL_SAMPLER_1D_SHADOW = 0x8B61;
    public static final int GL_SAMPLER_2D = 0x8B5E;
    public static final int GL_SAMPLER_2D_SHADOW = 0x8B62;
    public static final int GL_SAMPLER_3D = 0x8B5F;
    public static final int GL_SAMPLER_CUBE = 0x8B60;
    public static final int GL_SHADER_OBJECT = 0x8B48;
    public static final int GL_SHADER_SOURCE_LENGTH = 0x8B88;
    public static final int GL_SHADER_TYPE = 0x8B4F;
    public static final int GL_SHADING_LANGUAGE_VERSION = 0x8B8C;
    public static final int GL_STENCIL_BACK_FAIL = 0x8801;
    public static final int GL_STENCIL_BACK_FUNC = 0x8800;
    public static final int GL_STENCIL_BACK_PASS_DEPTH_FAIL = 0x8802;
    public static final int GL_STENCIL_BACK_PASS_DEPTH_PASS = 0x8803;
    public static final int GL_STENCIL_BACK_REF = 0x8CA3;
    public static final int GL_STENCIL_BACK_VALUE_MASK = 0x8CA4;
    public static final int GL_STENCIL_BACK_WRITEMASK = 0x8CA5;
    public static final int GL_UPPER_LEFT = 0x8CA2;
    public static final int GL_VALIDATE_STATUS = 0x8B83;
    public static final int GL_VERTEX_ATTRIB_ARRAY_ENABLED = 0x8622;
    public static final int GL_VERTEX_ATTRIB_ARRAY_NORMALIZED = 0x886A;
    public static final int GL_VERTEX_ATTRIB_ARRAY_POINTER = 0x8645;
    public static final int GL_VERTEX_ATTRIB_ARRAY_SIZE = 0x8623;
    public static final int GL_VERTEX_ATTRIB_ARRAY_STRIDE = 0x8624;
    public static final int GL_VERTEX_ATTRIB_ARRAY_TYPE = 0x8625;
    public static final int GL_VERTEX_PROGRAM_POINT_SIZE = 0x8642;
    public static final int GL_VERTEX_PROGRAM_TWO_SIDE = 0x8643;
    public static final int GL_VERTEX_SHADER = 0x8B31;

    public static void glAttachShader(int p0, int p1) {
        com.github.lodestone.lwjgl3.opengl.GL20.glAttachShader(p0, p1);
    }

    public static void glBindAttribLocation(int p0, int p1, java.lang.CharSequence p2) {
        com.github.lodestone.lwjgl3.opengl.GL20.glBindAttribLocation(p0, p1, p2);
    }

    public static void glBindAttribLocation(int p0, int p1, java.nio.ByteBuffer p2) {
        com.github.lodestone.lwjgl3.opengl.GL20.glBindAttribLocation(p0, p1, p2);
    }

    public static void glBlendEquationSeparate(int p0, int p1) {
        com.github.lodestone.lwjgl3.opengl.GL20.glBlendEquationSeparate(p0, p1);
    }

    public static void glCompileShader(int p0) {
        com.github.lodestone.lwjgl3.opengl.GL20.glCompileShader(p0);
    }

    public static int glCreateProgram() {
        return com.github.lodestone.lwjgl3.opengl.GL20.glCreateProgram();
    }

    public static int glCreateShader(int p0) {
        return com.github.lodestone.lwjgl3.opengl.GL20.glCreateShader(p0);
    }

    public static void glDeleteProgram(int p0) {
        com.github.lodestone.lwjgl3.opengl.GL20.glDeleteProgram(p0);
    }

    public static void glDeleteShader(int p0) {
        com.github.lodestone.lwjgl3.opengl.GL20.glDeleteShader(p0);
    }

    public static void glDetachShader(int p0, int p1) {
        com.github.lodestone.lwjgl3.opengl.GL20.glDetachShader(p0, p1);
    }

    public static void glDisableVertexAttribArray(int p0) {
        com.github.lodestone.lwjgl3.opengl.GL20.glDisableVertexAttribArray(p0);
    }

    public static void glDrawBuffers(int p0) {
        com.github.lodestone.lwjgl3.opengl.GL20.glDrawBuffers(p0);
    }

    public static void glDrawBuffers(java.nio.IntBuffer p0) {
        com.github.lodestone.lwjgl3.opengl.GL20.glDrawBuffers(p0);
    }

    public static void glEnableVertexAttribArray(int p0) {
        com.github.lodestone.lwjgl3.opengl.GL20.glEnableVertexAttribArray(p0);
    }

    public static void glGetActiveAttrib(int p0, int p1, java.nio.IntBuffer p2, java.nio.IntBuffer p3, java.nio.IntBuffer p4, java.nio.ByteBuffer p5) {
        com.github.lodestone.lwjgl3.opengl.GL20.glGetActiveAttrib(p0, p1, p2, p3, p4, p5);
    }

    public static void glGetActiveUniform(int p0, int p1, java.nio.IntBuffer p2, java.nio.IntBuffer p3, java.nio.IntBuffer p4, java.nio.ByteBuffer p5) {
        com.github.lodestone.lwjgl3.opengl.GL20.glGetActiveUniform(p0, p1, p2, p3, p4, p5);
    }

    public static void glGetAttachedShaders(int p0, java.nio.IntBuffer p1, java.nio.IntBuffer p2) {
        com.github.lodestone.lwjgl3.opengl.GL20.glGetAttachedShaders(p0, p1, p2);
    }

    public static int glGetAttribLocation(int p0, java.lang.CharSequence p1) {
        return com.github.lodestone.lwjgl3.opengl.GL20.glGetAttribLocation(p0, p1);
    }

    public static int glGetAttribLocation(int p0, java.nio.ByteBuffer p1) {
        return com.github.lodestone.lwjgl3.opengl.GL20.glGetAttribLocation(p0, p1);
    }

    public static void glGetProgram(int p0, int p1, java.nio.IntBuffer p2) {
        com.github.lodestone.lwjgl3.opengl.GL20.glGetProgramiv(p0, p1, p2);
    }

    public static java.lang.String glGetProgramInfoLog(int p0, int p1) {
        return com.github.lodestone.lwjgl3.opengl.GL20.glGetProgramInfoLog(p0, p1);
    }

    public static void glGetProgramInfoLog(int p0, java.nio.IntBuffer p1, java.nio.ByteBuffer p2) {
        com.github.lodestone.lwjgl3.opengl.GL20.glGetProgramInfoLog(p0, p1, p2);
    }

    public static int glGetProgrami(int p0, int p1) {
        return com.github.lodestone.lwjgl3.opengl.GL20.glGetProgrami(p0, p1);
    }

    public static void glGetShader(int p0, int p1, java.nio.IntBuffer p2) {
        com.github.lodestone.lwjgl3.opengl.GL20.glGetShaderiv(p0, p1, p2);
    }

    public static java.lang.String glGetShaderInfoLog(int p0, int p1) {
        return com.github.lodestone.lwjgl3.opengl.GL20.glGetShaderInfoLog(p0, p1);
    }

    public static void glGetShaderInfoLog(int p0, java.nio.IntBuffer p1, java.nio.ByteBuffer p2) {
        com.github.lodestone.lwjgl3.opengl.GL20.glGetShaderInfoLog(p0, p1, p2);
    }

    public static java.lang.String glGetShaderSource(int p0, int p1) {
        return com.github.lodestone.lwjgl3.opengl.GL20.glGetShaderSource(p0, p1);
    }

    public static void glGetShaderSource(int p0, java.nio.IntBuffer p1, java.nio.ByteBuffer p2) {
        com.github.lodestone.lwjgl3.opengl.GL20.glGetShaderSource(p0, p1, p2);
    }

    public static int glGetShaderi(int p0, int p1) {
        return com.github.lodestone.lwjgl3.opengl.GL20.glGetShaderi(p0, p1);
    }

    public static void glGetUniform(int p0, int p1, java.nio.FloatBuffer p2) {
        com.github.lodestone.lwjgl3.opengl.GL20.glGetUniformfv(p0, p1, p2);
    }

    public static void glGetUniform(int p0, int p1, java.nio.IntBuffer p2) {
        com.github.lodestone.lwjgl3.opengl.GL20.glGetUniformiv(p0, p1, p2);
    }

    public static int glGetUniformLocation(int p0, java.lang.CharSequence p1) {
        return com.github.lodestone.lwjgl3.opengl.GL20.glGetUniformLocation(p0, p1);
    }

    public static int glGetUniformLocation(int p0, java.nio.ByteBuffer p1) {
        return com.github.lodestone.lwjgl3.opengl.GL20.glGetUniformLocation(p0, p1);
    }

    public static void glGetVertexAttrib(int p0, int p1, java.nio.DoubleBuffer p2) {
        com.github.lodestone.lwjgl3.opengl.GL20.glGetVertexAttribdv(p0, p1, p2);
    }

    public static void glGetVertexAttrib(int p0, int p1, java.nio.FloatBuffer p2) {
        com.github.lodestone.lwjgl3.opengl.GL20.glGetVertexAttribfv(p0, p1, p2);
    }

    public static void glGetVertexAttrib(int p0, int p1, java.nio.IntBuffer p2) {
        com.github.lodestone.lwjgl3.opengl.GL20.glGetVertexAttribiv(p0, p1, p2);
    }

    public static boolean glIsProgram(int p0) {
        return com.github.lodestone.lwjgl3.opengl.GL20.glIsProgram(p0);
    }

    public static boolean glIsShader(int p0) {
        return com.github.lodestone.lwjgl3.opengl.GL20.glIsShader(p0);
    }

    public static void glLinkProgram(int p0) {
        com.github.lodestone.lwjgl3.opengl.GL20.glLinkProgram(p0);
    }

    public static void glShaderSource(int p0, java.lang.CharSequence p1) {
        com.github.lodestone.lwjgl3.opengl.GL20.glShaderSource(p0, p1);
    }

    public static void glShaderSource(int p0, java.nio.ByteBuffer p1) {
        com.github.lodestone.lwjgl3.opengl.GL20.glShaderSource(p0, org.lwjgl.system.MemoryUtil.memUTF8(p1.duplicate()));
    }

    public static void glShaderSource(int p0, java.lang.CharSequence[] p1) {
        com.github.lodestone.lwjgl3.opengl.GL20.glShaderSource(p0, p1);
    }

    public static void glStencilFuncSeparate(int p0, int p1, int p2, int p3) {
        com.github.lodestone.lwjgl3.opengl.GL20.glStencilFuncSeparate(p0, p1, p2, p3);
    }

    public static void glStencilMaskSeparate(int p0, int p1) {
        com.github.lodestone.lwjgl3.opengl.GL20.glStencilMaskSeparate(p0, p1);
    }

    public static void glStencilOpSeparate(int p0, int p1, int p2, int p3) {
        com.github.lodestone.lwjgl3.opengl.GL20.glStencilOpSeparate(p0, p1, p2, p3);
    }

    public static void glUniform1(int p0, java.nio.FloatBuffer p1) {
        com.github.lodestone.lwjgl3.opengl.GL20.glUniform1fv(p0, p1);
    }

    public static void glUniform1(int p0, java.nio.IntBuffer p1) {
        com.github.lodestone.lwjgl3.opengl.GL20.glUniform1iv(p0, p1);
    }

    public static void glUniform1f(int p0, float p1) {
        com.github.lodestone.lwjgl3.opengl.GL20.glUniform1f(p0, p1);
    }

    public static void glUniform1i(int p0, int p1) {
        com.github.lodestone.lwjgl3.opengl.GL20.glUniform1i(p0, p1);
    }

    public static void glUniform2(int p0, java.nio.FloatBuffer p1) {
        com.github.lodestone.lwjgl3.opengl.GL20.glUniform2fv(p0, p1);
    }

    public static void glUniform2(int p0, java.nio.IntBuffer p1) {
        com.github.lodestone.lwjgl3.opengl.GL20.glUniform2iv(p0, p1);
    }

    public static void glUniform2f(int p0, float p1, float p2) {
        com.github.lodestone.lwjgl3.opengl.GL20.glUniform2f(p0, p1, p2);
    }

    public static void glUniform2i(int p0, int p1, int p2) {
        com.github.lodestone.lwjgl3.opengl.GL20.glUniform2i(p0, p1, p2);
    }

    public static void glUniform3(int p0, java.nio.FloatBuffer p1) {
        com.github.lodestone.lwjgl3.opengl.GL20.glUniform3fv(p0, p1);
    }

    public static void glUniform3(int p0, java.nio.IntBuffer p1) {
        com.github.lodestone.lwjgl3.opengl.GL20.glUniform3iv(p0, p1);
    }

    public static void glUniform3f(int p0, float p1, float p2, float p3) {
        com.github.lodestone.lwjgl3.opengl.GL20.glUniform3f(p0, p1, p2, p3);
    }

    public static void glUniform3i(int p0, int p1, int p2, int p3) {
        com.github.lodestone.lwjgl3.opengl.GL20.glUniform3i(p0, p1, p2, p3);
    }

    public static void glUniform4(int p0, java.nio.FloatBuffer p1) {
        com.github.lodestone.lwjgl3.opengl.GL20.glUniform4fv(p0, p1);
    }

    public static void glUniform4(int p0, java.nio.IntBuffer p1) {
        com.github.lodestone.lwjgl3.opengl.GL20.glUniform4iv(p0, p1);
    }

    public static void glUniform4f(int p0, float p1, float p2, float p3, float p4) {
        com.github.lodestone.lwjgl3.opengl.GL20.glUniform4f(p0, p1, p2, p3, p4);
    }

    public static void glUniform4i(int p0, int p1, int p2, int p3, int p4) {
        com.github.lodestone.lwjgl3.opengl.GL20.glUniform4i(p0, p1, p2, p3, p4);
    }

    public static void glUniformMatrix2(int p0, boolean p1, java.nio.FloatBuffer p2) {
        com.github.lodestone.lwjgl3.opengl.GL20.glUniformMatrix2fv(p0, p1, p2);
    }

    public static void glUniformMatrix3(int p0, boolean p1, java.nio.FloatBuffer p2) {
        com.github.lodestone.lwjgl3.opengl.GL20.glUniformMatrix3fv(p0, p1, p2);
    }

    public static void glUniformMatrix4(int p0, boolean p1, java.nio.FloatBuffer p2) {
        com.github.lodestone.lwjgl3.opengl.GL20.glUniformMatrix4fv(p0, p1, p2);
    }

    public static void glUseProgram(int p0) {
        com.github.lodestone.lwjgl3.opengl.GL20.glUseProgram(p0);
    }

    public static void glValidateProgram(int p0) {
        com.github.lodestone.lwjgl3.opengl.GL20.glValidateProgram(p0);
    }

    public static void glVertexAttrib1d(int p0, double p1) {
        com.github.lodestone.lwjgl3.opengl.GL20.glVertexAttrib1d(p0, p1);
    }

    public static void glVertexAttrib1f(int p0, float p1) {
        com.github.lodestone.lwjgl3.opengl.GL20.glVertexAttrib1f(p0, p1);
    }

    public static void glVertexAttrib1s(int p0, short p1) {
        com.github.lodestone.lwjgl3.opengl.GL20.glVertexAttrib1s(p0, p1);
    }

    public static void glVertexAttrib2d(int p0, double p1, double p2) {
        com.github.lodestone.lwjgl3.opengl.GL20.glVertexAttrib2d(p0, p1, p2);
    }

    public static void glVertexAttrib2f(int p0, float p1, float p2) {
        com.github.lodestone.lwjgl3.opengl.GL20.glVertexAttrib2f(p0, p1, p2);
    }

    public static void glVertexAttrib2s(int p0, short p1, short p2) {
        com.github.lodestone.lwjgl3.opengl.GL20.glVertexAttrib2s(p0, p1, p2);
    }

    public static void glVertexAttrib3d(int p0, double p1, double p2, double p3) {
        com.github.lodestone.lwjgl3.opengl.GL20.glVertexAttrib3d(p0, p1, p2, p3);
    }

    public static void glVertexAttrib3f(int p0, float p1, float p2, float p3) {
        com.github.lodestone.lwjgl3.opengl.GL20.glVertexAttrib3f(p0, p1, p2, p3);
    }

    public static void glVertexAttrib3s(int p0, short p1, short p2, short p3) {
        com.github.lodestone.lwjgl3.opengl.GL20.glVertexAttrib3s(p0, p1, p2, p3);
    }

    public static void glVertexAttrib4Nub(int p0, byte p1, byte p2, byte p3, byte p4) {
        com.github.lodestone.lwjgl3.opengl.GL20.glVertexAttrib4Nub(p0, p1, p2, p3, p4);
    }

    public static void glVertexAttrib4d(int p0, double p1, double p2, double p3, double p4) {
        com.github.lodestone.lwjgl3.opengl.GL20.glVertexAttrib4d(p0, p1, p2, p3, p4);
    }

    public static void glVertexAttrib4f(int p0, float p1, float p2, float p3, float p4) {
        com.github.lodestone.lwjgl3.opengl.GL20.glVertexAttrib4f(p0, p1, p2, p3, p4);
    }

    public static void glVertexAttrib4s(int p0, short p1, short p2, short p3, short p4) {
        com.github.lodestone.lwjgl3.opengl.GL20.glVertexAttrib4s(p0, p1, p2, p3, p4);
    }

    public static void glVertexAttribPointer(int p0, int p1, int p2, boolean p3, int p4, long p5) {
        com.github.lodestone.lwjgl3.opengl.GL20.glVertexAttribPointer(p0, p1, p2, p3, p4, p5);
    }

    public static void glVertexAttribPointer(int p0, int p1, int p2, boolean p3, int p4, java.nio.ByteBuffer p5) {
        com.github.lodestone.lwjgl3.opengl.GL20.glVertexAttribPointer(p0, p1, p2, p3, p4, p5);
    }

    private GL20() {
    }
}
