// Generated by runtime/generate-lwjgl2-bindings.py. Do not edit.
//
// LWJGL 2's GL21. Every method forwards to LWJGL 3's binding of the same GL
// function, reached through the package the compatibility jar relocates
// LWJGL 3's OpenGL module into. The constants are LWJGL 2's own values.
package org.lwjgl.opengl;

public final class GL21 {

    public static final int GL_COMPRESSED_SLUMINANCE = 0x8C4A;
    public static final int GL_COMPRESSED_SLUMINANCE_ALPHA = 0x8C4B;
    public static final int GL_COMPRESSED_SRGB = 0x8C48;
    public static final int GL_COMPRESSED_SRGB_ALPHA = 0x8C49;
    public static final int GL_CURRENT_RASTER_SECONDARY_COLOR = 0x845F;
    public static final int GL_FLOAT_MAT2x3 = 0x8B65;
    public static final int GL_FLOAT_MAT2x4 = 0x8B66;
    public static final int GL_FLOAT_MAT3x2 = 0x8B67;
    public static final int GL_FLOAT_MAT3x4 = 0x8B68;
    public static final int GL_FLOAT_MAT4x2 = 0x8B69;
    public static final int GL_FLOAT_MAT4x3 = 0x8B6A;
    public static final int GL_PIXEL_PACK_BUFFER = 0x88EB;
    public static final int GL_PIXEL_PACK_BUFFER_BINDING = 0x88ED;
    public static final int GL_PIXEL_UNPACK_BUFFER = 0x88EC;
    public static final int GL_PIXEL_UNPACK_BUFFER_BINDING = 0x88EF;
    public static final int GL_SLUMINANCE = 0x8C46;
    public static final int GL_SLUMINANCE8 = 0x8C47;
    public static final int GL_SLUMINANCE8_ALPHA8 = 0x8C45;
    public static final int GL_SLUMINANCE_ALPHA = 0x8C44;
    public static final int GL_SRGB = 0x8C40;
    public static final int GL_SRGB8 = 0x8C41;
    public static final int GL_SRGB8_ALPHA8 = 0x8C43;
    public static final int GL_SRGB_ALPHA = 0x8C42;

    public static void glUniformMatrix2x3(int p0, boolean p1, java.nio.FloatBuffer p2) {
        com.github.lodestone.lwjgl3.opengl.GL21.glUniformMatrix2x3fv(p0, p1, p2);
    }

    public static void glUniformMatrix2x4(int p0, boolean p1, java.nio.FloatBuffer p2) {
        com.github.lodestone.lwjgl3.opengl.GL21.glUniformMatrix2x4fv(p0, p1, p2);
    }

    public static void glUniformMatrix3x2(int p0, boolean p1, java.nio.FloatBuffer p2) {
        com.github.lodestone.lwjgl3.opengl.GL21.glUniformMatrix3x2fv(p0, p1, p2);
    }

    public static void glUniformMatrix3x4(int p0, boolean p1, java.nio.FloatBuffer p2) {
        com.github.lodestone.lwjgl3.opengl.GL21.glUniformMatrix3x4fv(p0, p1, p2);
    }

    public static void glUniformMatrix4x2(int p0, boolean p1, java.nio.FloatBuffer p2) {
        com.github.lodestone.lwjgl3.opengl.GL21.glUniformMatrix4x2fv(p0, p1, p2);
    }

    public static void glUniformMatrix4x3(int p0, boolean p1, java.nio.FloatBuffer p2) {
        com.github.lodestone.lwjgl3.opengl.GL21.glUniformMatrix4x3fv(p0, p1, p2);
    }

    private GL21() {
    }
}
