// Generated by runtime/generate-lwjgl2-bindings.py. Do not edit.
//
// LWJGL 2's GL30. Every method forwards to LWJGL 3's binding of the same GL
// function, reached through the package the compatibility jar relocates
// LWJGL 3's OpenGL module into. The constants are LWJGL 2's own values.
package org.lwjgl.opengl;

public final class GL30 {

    public static final int GL_ALPHA16F = 0x881C;
    public static final int GL_ALPHA16I = 0x8D8A;
    public static final int GL_ALPHA16UI = 0x8D78;
    public static final int GL_ALPHA32F = 0x8816;
    public static final int GL_ALPHA32I = 0x8D84;
    public static final int GL_ALPHA32UI = 0x8D72;
    public static final int GL_ALPHA8I = 0x8D90;
    public static final int GL_ALPHA8UI = 0x8D7E;
    public static final int GL_ALPHA_INTEGER = 0x8D97;
    public static final int GL_BGRA_INTEGER = 0x8D9B;
    public static final int GL_BGR_INTEGER = 0x8D9A;
    public static final int GL_BLUE_INTEGER = 0x8D96;
    public static final int GL_BUFFER_ACCESS_FLAGS = 0x911F;
    public static final int GL_BUFFER_MAP_LENGTH = 0x9120;
    public static final int GL_BUFFER_MAP_OFFSET = 0x9121;
    public static final int GL_CLAMP_FRAGMENT_COLOR = 0x891B;
    public static final int GL_CLAMP_READ_COLOR = 0x891C;
    public static final int GL_CLAMP_VERTEX_COLOR = 0x891A;
    public static final int GL_CLIP_DISTANCE0 = 0x3000;
    public static final int GL_CLIP_DISTANCE1 = 0x3001;
    public static final int GL_CLIP_DISTANCE2 = 0x3002;
    public static final int GL_CLIP_DISTANCE3 = 0x3003;
    public static final int GL_CLIP_DISTANCE4 = 0x3004;
    public static final int GL_CLIP_DISTANCE5 = 0x3005;
    public static final int GL_CLIP_DISTANCE6 = 0x3006;
    public static final int GL_CLIP_DISTANCE7 = 0x3007;
    public static final int GL_COLOR_ATTACHMENT0 = 0x8CE0;
    public static final int GL_COLOR_ATTACHMENT1 = 0x8CE1;
    public static final int GL_COLOR_ATTACHMENT10 = 0x8CEA;
    public static final int GL_COLOR_ATTACHMENT11 = 0x8CEB;
    public static final int GL_COLOR_ATTACHMENT12 = 0x8CEC;
    public static final int GL_COLOR_ATTACHMENT13 = 0x8CED;
    public static final int GL_COLOR_ATTACHMENT14 = 0x8CEE;
    public static final int GL_COLOR_ATTACHMENT15 = 0x8CEF;
    public static final int GL_COLOR_ATTACHMENT2 = 0x8CE2;
    public static final int GL_COLOR_ATTACHMENT3 = 0x8CE3;
    public static final int GL_COLOR_ATTACHMENT4 = 0x8CE4;
    public static final int GL_COLOR_ATTACHMENT5 = 0x8CE5;
    public static final int GL_COLOR_ATTACHMENT6 = 0x8CE6;
    public static final int GL_COLOR_ATTACHMENT7 = 0x8CE7;
    public static final int GL_COLOR_ATTACHMENT8 = 0x8CE8;
    public static final int GL_COLOR_ATTACHMENT9 = 0x8CE9;
    public static final int GL_COMPARE_REF_DEPTH_TO_TEXTURE = 0x884E;
    public static final int GL_COMPARE_REF_TO_TEXTURE = 0x884E;
    public static final int GL_COMPRESSED_RED = 0x8225;
    public static final int GL_COMPRESSED_RED_RGTC1 = 0x8DBB;
    public static final int GL_COMPRESSED_RG = 0x8226;
    public static final int GL_COMPRESSED_RG_RGTC2 = 0x8DBD;
    public static final int GL_COMPRESSED_SIGNED_RED_RGTC1 = 0x8DBC;
    public static final int GL_COMPRESSED_SIGNED_RG_RGTC2 = 0x8DBE;
    public static final int GL_CONTEXT_FLAGS = 0x821E;
    public static final int GL_CONTEXT_FLAG_FORWARD_COMPATIBLE_BIT = 0x1;
    public static final int GL_DEPTH24_STENCIL8 = 0x88F0;
    public static final int GL_DEPTH32F_STENCIL8 = 0x8CAD;
    public static final int GL_DEPTH_ATTACHMENT = 0x8D00;
    public static final int GL_DEPTH_BUFFER = 0x8223;
    public static final int GL_DEPTH_COMPONENT32F = 0x8CAC;
    public static final int GL_DEPTH_STENCIL = 0x84F9;
    public static final int GL_DEPTH_STENCIL_ATTACHMENT = 0x821A;
    public static final int GL_DRAW_FRAMEBUFFER = 0x8CA9;
    public static final int GL_DRAW_FRAMEBUFFER_BINDING = 0x8CA6;
    public static final int GL_FIXED_ONLY = 0x891D;
    public static final int GL_FLOAT_32_UNSIGNED_INT_24_8_REV = 0x8DAD;
    public static final int GL_FRAMEBUFFER = 0x8D40;
    public static final int GL_FRAMEBUFFER_ATTACHMENT_ALPHA_SIZE = 0x8215;
    public static final int GL_FRAMEBUFFER_ATTACHMENT_BLUE_SIZE = 0x8214;
    public static final int GL_FRAMEBUFFER_ATTACHMENT_COLOR_ENCODING = 0x8210;
    public static final int GL_FRAMEBUFFER_ATTACHMENT_COMPONENT_TYPE = 0x8211;
    public static final int GL_FRAMEBUFFER_ATTACHMENT_DEPTH_SIZE = 0x8216;
    public static final int GL_FRAMEBUFFER_ATTACHMENT_GREEN_SIZE = 0x8213;
    public static final int GL_FRAMEBUFFER_ATTACHMENT_OBJECT_NAME = 0x8CD1;
    public static final int GL_FRAMEBUFFER_ATTACHMENT_OBJECT_TYPE = 0x8CD0;
    public static final int GL_FRAMEBUFFER_ATTACHMENT_RED_SIZE = 0x8212;
    public static final int GL_FRAMEBUFFER_ATTACHMENT_STENCIL_SIZE = 0x8217;
    public static final int GL_FRAMEBUFFER_ATTACHMENT_TEXTURE_CUBE_MAP_FACE = 0x8CD3;
    public static final int GL_FRAMEBUFFER_ATTACHMENT_TEXTURE_LAYER = 0x8CD4;
    public static final int GL_FRAMEBUFFER_ATTACHMENT_TEXTURE_LEVEL = 0x8CD2;
    public static final int GL_FRAMEBUFFER_BINDING = 0x8CA6;
    public static final int GL_FRAMEBUFFER_COMPLETE = 0x8CD5;
    public static final int GL_FRAMEBUFFER_DEFAULT = 0x8218;
    public static final int GL_FRAMEBUFFER_INCOMPLETE_ATTACHMENT = 0x8CD6;
    public static final int GL_FRAMEBUFFER_INCOMPLETE_DRAW_BUFFER = 0x8CDB;
    public static final int GL_FRAMEBUFFER_INCOMPLETE_MISSING_ATTACHMENT = 0x8CD7;
    public static final int GL_FRAMEBUFFER_INCOMPLETE_MULTISAMPLE = 0x8D56;
    public static final int GL_FRAMEBUFFER_INCOMPLETE_READ_BUFFER = 0x8CDC;
    public static final int GL_FRAMEBUFFER_SRGB = 0x8DB9;
    public static final int GL_FRAMEBUFFER_SRGB_CAPABLE = 0x8DBA;
    public static final int GL_FRAMEBUFFER_UNDEFINED = 0x8219;
    public static final int GL_FRAMEBUFFER_UNSUPPORTED = 0x8CDD;
    public static final int GL_GREEN_INTEGER = 0x8D95;
    public static final int GL_HALF_FLOAT = 0x140B;
    public static final int GL_INDEX = 0x8222;
    public static final int GL_INTERLEAVED_ATTRIBS = 0x8C8C;
    public static final int GL_INT_SAMPLER_1D = 0x8DC9;
    public static final int GL_INT_SAMPLER_1D_ARRAY = 0x8DCE;
    public static final int GL_INT_SAMPLER_2D = 0x8DCA;
    public static final int GL_INT_SAMPLER_2D_ARRAY = 0x8DCF;
    public static final int GL_INT_SAMPLER_2D_RECT = 0x8DCD;
    public static final int GL_INT_SAMPLER_3D = 0x8DCB;
    public static final int GL_INT_SAMPLER_BUFFER = 0x8DD0;
    public static final int GL_INT_SAMPLER_CUBE = 0x8DCC;
    public static final int GL_INVALID_FRAMEBUFFER_OPERATION = 0x506;
    public static final int GL_MAJOR_VERSION = 0x821B;
    public static final int GL_MAP_FLUSH_EXPLICIT_BIT = 0x10;
    public static final int GL_MAP_INVALIDATE_BUFFER_BIT = 0x8;
    public static final int GL_MAP_INVALIDATE_RANGE_BIT = 0x4;
    public static final int GL_MAP_READ_BIT = 0x1;
    public static final int GL_MAP_UNSYNCHRONIZED_BIT = 0x20;
    public static final int GL_MAP_WRITE_BIT = 0x2;
    public static final int GL_MAX_ARRAY_TEXTURE_LAYERS = 0x88FF;
    public static final int GL_MAX_CLIP_DISTANCES = 0xD32;
    public static final int GL_MAX_COLOR_ATTACHMENTS = 0x8CDF;
    public static final int GL_MAX_PROGRAM_TEXEL_OFFSET = 0x8905;
    public static final int GL_MAX_RENDERBUFFER_SIZE = 0x84E8;
    public static final int GL_MAX_SAMPLES = 0x8D57;
    public static final int GL_MAX_TRANSFORM_FEEDBACK_INTERLEAVED_COMPONENTS = 0x8C8A;
    public static final int GL_MAX_TRANSFORM_FEEDBACK_SEPARATE_ATTRIBS = 0x8C8B;
    public static final int GL_MAX_TRANSFORM_FEEDBACK_SEPARATE_COMPONENTS = 0x8C80;
    public static final int GL_MAX_VARYING_COMPONENTS = 0x8B4B;
    public static final int GL_MINOR_VERSION = 0x821C;
    public static final int GL_MIN_PROGRAM_TEXEL_OFFSET = 0x8904;
    public static final int GL_NUM_EXTENSIONS = 0x821D;
    public static final int GL_PRIMITIVES_GENERATED = 0x8C87;
    public static final int GL_PROXY_TEXTURE_1D_ARRAY = 0x8C19;
    public static final int GL_PROXY_TEXTURE_2D_ARRAY = 0x8C1B;
    public static final int GL_QUERY_BY_REGION_NO_WAIT = 0x8E16;
    public static final int GL_QUERY_BY_REGION_WAIT = 0x8E15;
    public static final int GL_QUERY_NO_WAIT = 0x8E14;
    public static final int GL_QUERY_WAIT = 0x8E13;
    public static final int GL_R11F_G11F_B10F = 0x8C3A;
    public static final int GL_R16 = 0x822A;
    public static final int GL_R16F = 0x822D;
    public static final int GL_R16I = 0x8233;
    public static final int GL_R16UI = 0x8234;
    public static final int GL_R32F = 0x822E;
    public static final int GL_R32I = 0x8235;
    public static final int GL_R32UI = 0x8236;
    public static final int GL_R8 = 0x8229;
    public static final int GL_R8I = 0x8231;
    public static final int GL_R8UI = 0x8232;
    public static final int GL_RASTERIZER_DISCARD = 0x8C89;
    public static final int GL_READ_FRAMEBUFFER = 0x8CA8;
    public static final int GL_READ_FRAMEBUFFER_BINDING = 0x8CAA;
    public static final int GL_RED_INTEGER = 0x8D94;
    public static final int GL_RENDERBUFFER = 0x8D41;
    public static final int GL_RENDERBUFFER_ALPHA_SIZE = 0x8D53;
    public static final int GL_RENDERBUFFER_BINDING = 0x8CA7;
    public static final int GL_RENDERBUFFER_BLUE_SIZE = 0x8D52;
    public static final int GL_RENDERBUFFER_DEPTH_SIZE = 0x8D54;
    public static final int GL_RENDERBUFFER_GREEN_SIZE = 0x8D51;
    public static final int GL_RENDERBUFFER_HEIGHT = 0x8D43;
    public static final int GL_RENDERBUFFER_INTERNAL_FORMAT = 0x8D44;
    public static final int GL_RENDERBUFFER_RED_SIZE = 0x8D50;
    public static final int GL_RENDERBUFFER_SAMPLES = 0x8CAB;
    public static final int GL_RENDERBUFFER_STENCIL_SIZE = 0x8D55;
    public static final int GL_RENDERBUFFER_WIDTH = 0x8D42;
    public static final int GL_RG = 0x8227;
    public static final int GL_RG16 = 0x822C;
    public static final int GL_RG16F = 0x822F;
    public static final int GL_RG16I = 0x8239;
    public static final int GL_RG16UI = 0x823A;
    public static final int GL_RG32F = 0x8230;
    public static final int GL_RG32I = 0x823B;
    public static final int GL_RG32UI = 0x823C;
    public static final int GL_RG8 = 0x822B;
    public static final int GL_RG8I = 0x8237;
    public static final int GL_RG8UI = 0x8238;
    public static final int GL_RGB16F = 0x881B;
    public static final int GL_RGB16I = 0x8D89;
    public static final int GL_RGB16UI = 0x8D77;
    public static final int GL_RGB32F = 0x8815;
    public static final int GL_RGB32I = 0x8D83;
    public static final int GL_RGB32UI = 0x8D71;
    public static final int GL_RGB8I = 0x8D8F;
    public static final int GL_RGB8UI = 0x8D7D;
    public static final int GL_RGB9_E5 = 0x8C3D;
    public static final int GL_RGBA16F = 0x881A;
    public static final int GL_RGBA16I = 0x8D88;
    public static final int GL_RGBA16UI = 0x8D76;
    public static final int GL_RGBA32F = 0x8814;
    public static final int GL_RGBA32I = 0x8D82;
    public static final int GL_RGBA32UI = 0x8D70;
    public static final int GL_RGBA8I = 0x8D8E;
    public static final int GL_RGBA8UI = 0x8D7C;
    public static final int GL_RGBA_INTEGER = 0x8D99;
    public static final int GL_RGBA_INTEGER_MODE = 0x8D9E;
    public static final int GL_RGB_INTEGER = 0x8D98;
    public static final int GL_RG_INTEGER = 0x8228;
    public static final int GL_SAMPLER_1D_ARRAY = 0x8DC0;
    public static final int GL_SAMPLER_1D_ARRAY_SHADOW = 0x8DC3;
    public static final int GL_SAMPLER_2D_ARRAY = 0x8DC1;
    public static final int GL_SAMPLER_2D_ARRAY_SHADOW = 0x8DC4;
    public static final int GL_SAMPLER_BUFFER = 0x8DC2;
    public static final int GL_SAMPLER_CUBE_SHADOW = 0x8DC5;
    public static final int GL_SEPARATE_ATTRIBS = 0x8C8D;
    public static final int GL_STENCIL_ATTACHMENT = 0x8D20;
    public static final int GL_STENCIL_BUFFER = 0x8224;
    public static final int GL_STENCIL_INDEX1 = 0x8D46;
    public static final int GL_STENCIL_INDEX16 = 0x8D49;
    public static final int GL_STENCIL_INDEX4 = 0x8D47;
    public static final int GL_STENCIL_INDEX8 = 0x8D48;
    public static final int GL_TEXTURE_1D_ARRAY = 0x8C18;
    public static final int GL_TEXTURE_2D_ARRAY = 0x8C1A;
    public static final int GL_TEXTURE_ALPHA_TYPE = 0x8C13;
    public static final int GL_TEXTURE_BINDING_1D_ARRAY = 0x8C1C;
    public static final int GL_TEXTURE_BINDING_2D_ARRAY = 0x8C1D;
    public static final int GL_TEXTURE_BLUE_TYPE = 0x8C12;
    public static final int GL_TEXTURE_DEPTH_TYPE = 0x8C16;
    public static final int GL_TEXTURE_GREEN_TYPE = 0x8C11;
    public static final int GL_TEXTURE_INTENSITY_TYPE = 0x8C15;
    public static final int GL_TEXTURE_LUMINANCE_TYPE = 0x8C14;
    public static final int GL_TEXTURE_RED_TYPE = 0x8C10;
    public static final int GL_TEXTURE_SHARED_SIZE = 0x8C3F;
    public static final int GL_TEXTURE_STENCIL_SIZE = 0x88F1;
    public static final int GL_TRANSFORM_FEEDBACK_BUFFER = 0x8C8E;
    public static final int GL_TRANSFORM_FEEDBACK_BUFFER_BINDING = 0x8C8F;
    public static final int GL_TRANSFORM_FEEDBACK_BUFFER_MODE = 0x8C7F;
    public static final int GL_TRANSFORM_FEEDBACK_BUFFER_SIZE = 0x8C85;
    public static final int GL_TRANSFORM_FEEDBACK_BUFFER_START = 0x8C84;
    public static final int GL_TRANSFORM_FEEDBACK_PRIMITIVES_WRITTEN = 0x8C88;
    public static final int GL_TRANSFORM_FEEDBACK_VARYINGS = 0x8C83;
    public static final int GL_TRANSFORM_FEEDBACK_VARYING_MAX_LENGTH = 0x8C76;
    public static final int GL_UNSIGNED_INT_10F_11F_11F_REV = 0x8C3B;
    public static final int GL_UNSIGNED_INT_24_8 = 0x84FA;
    public static final int GL_UNSIGNED_INT_5_9_9_9_REV = 0x8C3E;
    public static final int GL_UNSIGNED_INT_SAMPLER_1D = 0x8DD1;
    public static final int GL_UNSIGNED_INT_SAMPLER_1D_ARRAY = 0x8DD6;
    public static final int GL_UNSIGNED_INT_SAMPLER_2D = 0x8DD2;
    public static final int GL_UNSIGNED_INT_SAMPLER_2D_ARRAY = 0x8DD7;
    public static final int GL_UNSIGNED_INT_SAMPLER_2D_RECT = 0x8DD5;
    public static final int GL_UNSIGNED_INT_SAMPLER_3D = 0x8DD3;
    public static final int GL_UNSIGNED_INT_SAMPLER_BUFFER = 0x8DD8;
    public static final int GL_UNSIGNED_INT_SAMPLER_CUBE = 0x8DD4;
    public static final int GL_UNSIGNED_INT_VEC2 = 0x8DC6;
    public static final int GL_UNSIGNED_INT_VEC3 = 0x8DC7;
    public static final int GL_UNSIGNED_INT_VEC4 = 0x8DC8;
    public static final int GL_UNSIGNED_NORMALIZED = 0x8C17;
    public static final int GL_VERTEX_ARRAY_BINDING = 0x85B5;
    public static final int GL_VERTEX_ATTRIB_ARRAY_INTEGER = 0x88FD;

    public static void glBeginConditionalRender(int p0, int p1) {
        com.github.lodestone.lwjgl3.opengl.GL30.glBeginConditionalRender(p0, p1);
    }

    public static void glBeginTransformFeedback(int p0) {
        com.github.lodestone.lwjgl3.opengl.GL30.glBeginTransformFeedback(p0);
    }

    public static void glBindBufferBase(int p0, int p1, int p2) {
        com.github.lodestone.lwjgl3.opengl.GL30.glBindBufferBase(p0, p1, p2);
    }

    public static void glBindBufferRange(int p0, int p1, int p2, long p3, long p4) {
        com.github.lodestone.lwjgl3.opengl.GL30.glBindBufferRange(p0, p1, p2, p3, p4);
    }

    public static void glBindFragDataLocation(int p0, int p1, java.lang.CharSequence p2) {
        com.github.lodestone.lwjgl3.opengl.GL30.glBindFragDataLocation(p0, p1, p2);
    }

    public static void glBindFragDataLocation(int p0, int p1, java.nio.ByteBuffer p2) {
        com.github.lodestone.lwjgl3.opengl.GL30.glBindFragDataLocation(p0, p1, p2);
    }

    public static void glBindFramebuffer(int p0, int p1) {
        com.github.lodestone.lwjgl3.opengl.GL30.glBindFramebuffer(p0, p1);
    }

    public static void glBindRenderbuffer(int p0, int p1) {
        com.github.lodestone.lwjgl3.opengl.GL30.glBindRenderbuffer(p0, p1);
    }

    public static void glBindVertexArray(int p0) {
        com.github.lodestone.lwjgl3.opengl.GL30.glBindVertexArray(p0);
    }

    public static void glBlitFramebuffer(int p0, int p1, int p2, int p3, int p4, int p5, int p6, int p7, int p8, int p9) {
        com.github.lodestone.lwjgl3.opengl.GL30.glBlitFramebuffer(p0, p1, p2, p3, p4, p5, p6, p7, p8, p9);
    }

    public static int glCheckFramebufferStatus(int p0) {
        return com.github.lodestone.lwjgl3.opengl.GL30.glCheckFramebufferStatus(p0);
    }

    public static void glClampColor(int p0, int p1) {
        com.github.lodestone.lwjgl3.opengl.GL30.glClampColor(p0, p1);
    }

    public static void glClearBuffer(int p0, int p1, java.nio.FloatBuffer p2) {
        com.github.lodestone.lwjgl3.opengl.GL30.glClearBufferfv(p0, p1, p2);
    }

    public static void glClearBuffer(int p0, int p1, java.nio.IntBuffer p2) {
        com.github.lodestone.lwjgl3.opengl.GL30.glClearBufferiv(p0, p1, p2);
    }

    public static void glClearBufferfi(int p0, int p1, float p2, int p3) {
        com.github.lodestone.lwjgl3.opengl.GL30.glClearBufferfi(p0, p1, p2, p3);
    }

    public static void glClearBufferu(int p0, int p1, java.nio.IntBuffer p2) {
        com.github.lodestone.lwjgl3.opengl.GL30.glClearBufferuiv(p0, p1, p2);
    }

    public static void glColorMaski(int p0, boolean p1, boolean p2, boolean p3, boolean p4) {
        com.github.lodestone.lwjgl3.opengl.GL30.glColorMaski(p0, p1, p2, p3, p4);
    }

    public static void glDeleteFramebuffers(int p0) {
        com.github.lodestone.lwjgl3.opengl.GL30.glDeleteFramebuffers(p0);
    }

    public static void glDeleteFramebuffers(java.nio.IntBuffer p0) {
        com.github.lodestone.lwjgl3.opengl.GL30.glDeleteFramebuffers(p0);
    }

    public static void glDeleteRenderbuffers(int p0) {
        com.github.lodestone.lwjgl3.opengl.GL30.glDeleteRenderbuffers(p0);
    }

    public static void glDeleteRenderbuffers(java.nio.IntBuffer p0) {
        com.github.lodestone.lwjgl3.opengl.GL30.glDeleteRenderbuffers(p0);
    }

    public static void glDeleteVertexArrays(int p0) {
        com.github.lodestone.lwjgl3.opengl.GL30.glDeleteVertexArrays(p0);
    }

    public static void glDeleteVertexArrays(java.nio.IntBuffer p0) {
        com.github.lodestone.lwjgl3.opengl.GL30.glDeleteVertexArrays(p0);
    }

    public static void glDisablei(int p0, int p1) {
        com.github.lodestone.lwjgl3.opengl.GL30.glDisablei(p0, p1);
    }

    public static void glEnablei(int p0, int p1) {
        com.github.lodestone.lwjgl3.opengl.GL30.glEnablei(p0, p1);
    }

    public static void glEndConditionalRender() {
        com.github.lodestone.lwjgl3.opengl.GL30.glEndConditionalRender();
    }

    public static void glEndTransformFeedback() {
        com.github.lodestone.lwjgl3.opengl.GL30.glEndTransformFeedback();
    }

    public static void glFlushMappedBufferRange(int p0, long p1, long p2) {
        com.github.lodestone.lwjgl3.opengl.GL30.glFlushMappedBufferRange(p0, p1, p2);
    }

    public static void glFramebufferRenderbuffer(int p0, int p1, int p2, int p3) {
        com.github.lodestone.lwjgl3.opengl.GL30.glFramebufferRenderbuffer(p0, p1, p2, p3);
    }

    public static void glFramebufferTexture1D(int p0, int p1, int p2, int p3, int p4) {
        com.github.lodestone.lwjgl3.opengl.GL30.glFramebufferTexture1D(p0, p1, p2, p3, p4);
    }

    public static void glFramebufferTexture2D(int p0, int p1, int p2, int p3, int p4) {
        com.github.lodestone.lwjgl3.opengl.GL30.glFramebufferTexture2D(p0, p1, p2, p3, p4);
    }

    public static void glFramebufferTexture3D(int p0, int p1, int p2, int p3, int p4, int p5) {
        com.github.lodestone.lwjgl3.opengl.GL30.glFramebufferTexture3D(p0, p1, p2, p3, p4, p5);
    }

    public static void glFramebufferTextureLayer(int p0, int p1, int p2, int p3, int p4) {
        com.github.lodestone.lwjgl3.opengl.GL30.glFramebufferTextureLayer(p0, p1, p2, p3, p4);
    }

    public static int glGenFramebuffers() {
        return com.github.lodestone.lwjgl3.opengl.GL30.glGenFramebuffers();
    }

    public static void glGenFramebuffers(java.nio.IntBuffer p0) {
        com.github.lodestone.lwjgl3.opengl.GL30.glGenFramebuffers(p0);
    }

    public static int glGenRenderbuffers() {
        return com.github.lodestone.lwjgl3.opengl.GL30.glGenRenderbuffers();
    }

    public static void glGenRenderbuffers(java.nio.IntBuffer p0) {
        com.github.lodestone.lwjgl3.opengl.GL30.glGenRenderbuffers(p0);
    }

    public static int glGenVertexArrays() {
        return com.github.lodestone.lwjgl3.opengl.GL30.glGenVertexArrays();
    }

    public static void glGenVertexArrays(java.nio.IntBuffer p0) {
        com.github.lodestone.lwjgl3.opengl.GL30.glGenVertexArrays(p0);
    }

    public static void glGenerateMipmap(int p0) {
        com.github.lodestone.lwjgl3.opengl.GL30.glGenerateMipmap(p0);
    }

    public static int glGetFragDataLocation(int p0, java.lang.CharSequence p1) {
        return com.github.lodestone.lwjgl3.opengl.GL30.glGetFragDataLocation(p0, p1);
    }

    public static int glGetFragDataLocation(int p0, java.nio.ByteBuffer p1) {
        return com.github.lodestone.lwjgl3.opengl.GL30.glGetFragDataLocation(p0, p1);
    }

    public static void glGetFramebufferAttachmentParameter(int p0, int p1, int p2, java.nio.IntBuffer p3) {
        com.github.lodestone.lwjgl3.opengl.GL30.glGetFramebufferAttachmentParameteriv(p0, p1, p2, p3);
    }

    public static int glGetFramebufferAttachmentParameteri(int p0, int p1, int p2) {
        return com.github.lodestone.lwjgl3.opengl.GL30.glGetFramebufferAttachmentParameteri(p0, p1, p2);
    }

    public static void glGetRenderbufferParameter(int p0, int p1, java.nio.IntBuffer p2) {
        com.github.lodestone.lwjgl3.opengl.GL30.glGetRenderbufferParameteriv(p0, p1, p2);
    }

    public static int glGetRenderbufferParameteri(int p0, int p1) {
        return com.github.lodestone.lwjgl3.opengl.GL30.glGetRenderbufferParameteri(p0, p1);
    }

    public static java.lang.String glGetStringi(int p0, int p1) {
        return com.github.lodestone.lwjgl3.opengl.GL30.glGetStringi(p0, p1);
    }

    public static void glGetTexParameterI(int p0, int p1, java.nio.IntBuffer p2) {
        com.github.lodestone.lwjgl3.opengl.GL30.glGetTexParameterIiv(p0, p1, p2);
    }

    public static int glGetTexParameterIi(int p0, int p1) {
        return com.github.lodestone.lwjgl3.opengl.GL30.glGetTexParameterIi(p0, p1);
    }

    public static void glGetTexParameterIu(int p0, int p1, java.nio.IntBuffer p2) {
        com.github.lodestone.lwjgl3.opengl.GL30.glGetTexParameterIuiv(p0, p1, p2);
    }

    public static int glGetTexParameterIui(int p0, int p1) {
        return com.github.lodestone.lwjgl3.opengl.GL30.glGetTexParameterIui(p0, p1);
    }

    public static java.lang.String glGetTransformFeedbackVarying(int p0, int p1, int p2, java.nio.IntBuffer p3, java.nio.IntBuffer p4) {
        return com.github.lodestone.lwjgl3.opengl.GL30.glGetTransformFeedbackVarying(p0, p1, p2, p3, p4);
    }

    public static void glGetTransformFeedbackVarying(int p0, int p1, java.nio.IntBuffer p2, java.nio.IntBuffer p3, java.nio.IntBuffer p4, java.nio.ByteBuffer p5) {
        com.github.lodestone.lwjgl3.opengl.GL30.glGetTransformFeedbackVarying(p0, p1, p2, p3, p4, p5);
    }

    public static void glGetUniformu(int p0, int p1, java.nio.IntBuffer p2) {
        com.github.lodestone.lwjgl3.opengl.GL30.glGetUniformuiv(p0, p1, p2);
    }

    public static void glGetVertexAttribI(int p0, int p1, java.nio.IntBuffer p2) {
        com.github.lodestone.lwjgl3.opengl.GL30.glGetVertexAttribIiv(p0, p1, p2);
    }

    public static void glGetVertexAttribIu(int p0, int p1, java.nio.IntBuffer p2) {
        com.github.lodestone.lwjgl3.opengl.GL30.glGetVertexAttribIuiv(p0, p1, p2);
    }

    public static boolean glIsEnabledi(int p0, int p1) {
        return com.github.lodestone.lwjgl3.opengl.GL30.glIsEnabledi(p0, p1);
    }

    public static boolean glIsFramebuffer(int p0) {
        return com.github.lodestone.lwjgl3.opengl.GL30.glIsFramebuffer(p0);
    }

    public static boolean glIsRenderbuffer(int p0) {
        return com.github.lodestone.lwjgl3.opengl.GL30.glIsRenderbuffer(p0);
    }

    public static boolean glIsVertexArray(int p0) {
        return com.github.lodestone.lwjgl3.opengl.GL30.glIsVertexArray(p0);
    }

    public static java.nio.ByteBuffer glMapBufferRange(int p0, long p1, long p2, int p3, java.nio.ByteBuffer p4) {
        return com.github.lodestone.lwjgl3.opengl.GL30.glMapBufferRange(p0, p1, p2, p3, p4);
    }

    public static void glRenderbufferStorage(int p0, int p1, int p2, int p3) {
        com.github.lodestone.lwjgl3.opengl.GL30.glRenderbufferStorage(p0, p1, p2, p3);
    }

    public static void glRenderbufferStorageMultisample(int p0, int p1, int p2, int p3, int p4) {
        com.github.lodestone.lwjgl3.opengl.GL30.glRenderbufferStorageMultisample(p0, p1, p2, p3, p4);
    }

    public static void glTexParameterI(int p0, int p1, java.nio.IntBuffer p2) {
        com.github.lodestone.lwjgl3.opengl.GL30.glTexParameterIiv(p0, p1, p2);
    }

    public static void glTexParameterIi(int p0, int p1, int p2) {
        com.github.lodestone.lwjgl3.opengl.GL30.glTexParameterIi(p0, p1, p2);
    }

    public static void glTexParameterIu(int p0, int p1, java.nio.IntBuffer p2) {
        com.github.lodestone.lwjgl3.opengl.GL30.glTexParameterIuiv(p0, p1, p2);
    }

    public static void glTexParameterIui(int p0, int p1, int p2) {
        com.github.lodestone.lwjgl3.opengl.GL30.glTexParameterIui(p0, p1, p2);
    }

    public static void glTransformFeedbackVaryings(int p0, java.lang.CharSequence[] p1, int p2) {
        com.github.lodestone.lwjgl3.opengl.GL30.glTransformFeedbackVaryings(p0, p1, p2);
    }

    public static void glUniform1u(int p0, java.nio.IntBuffer p1) {
        com.github.lodestone.lwjgl3.opengl.GL30.glUniform1uiv(p0, p1);
    }

    public static void glUniform1ui(int p0, int p1) {
        com.github.lodestone.lwjgl3.opengl.GL30.glUniform1ui(p0, p1);
    }

    public static void glUniform2u(int p0, java.nio.IntBuffer p1) {
        com.github.lodestone.lwjgl3.opengl.GL30.glUniform2uiv(p0, p1);
    }

    public static void glUniform2ui(int p0, int p1, int p2) {
        com.github.lodestone.lwjgl3.opengl.GL30.glUniform2ui(p0, p1, p2);
    }

    public static void glUniform3u(int p0, java.nio.IntBuffer p1) {
        com.github.lodestone.lwjgl3.opengl.GL30.glUniform3uiv(p0, p1);
    }

    public static void glUniform3ui(int p0, int p1, int p2, int p3) {
        com.github.lodestone.lwjgl3.opengl.GL30.glUniform3ui(p0, p1, p2, p3);
    }

    public static void glUniform4u(int p0, java.nio.IntBuffer p1) {
        com.github.lodestone.lwjgl3.opengl.GL30.glUniform4uiv(p0, p1);
    }

    public static void glUniform4ui(int p0, int p1, int p2, int p3, int p4) {
        com.github.lodestone.lwjgl3.opengl.GL30.glUniform4ui(p0, p1, p2, p3, p4);
    }

    public static void glVertexAttribI1(int p0, java.nio.IntBuffer p1) {
        com.github.lodestone.lwjgl3.opengl.GL30.glVertexAttribI1iv(p0, p1);
    }

    public static void glVertexAttribI1i(int p0, int p1) {
        com.github.lodestone.lwjgl3.opengl.GL30.glVertexAttribI1i(p0, p1);
    }

    public static void glVertexAttribI1u(int p0, java.nio.IntBuffer p1) {
        com.github.lodestone.lwjgl3.opengl.GL30.glVertexAttribI1uiv(p0, p1);
    }

    public static void glVertexAttribI1ui(int p0, int p1) {
        com.github.lodestone.lwjgl3.opengl.GL30.glVertexAttribI1ui(p0, p1);
    }

    public static void glVertexAttribI2(int p0, java.nio.IntBuffer p1) {
        com.github.lodestone.lwjgl3.opengl.GL30.glVertexAttribI2iv(p0, p1);
    }

    public static void glVertexAttribI2i(int p0, int p1, int p2) {
        com.github.lodestone.lwjgl3.opengl.GL30.glVertexAttribI2i(p0, p1, p2);
    }

    public static void glVertexAttribI2u(int p0, java.nio.IntBuffer p1) {
        com.github.lodestone.lwjgl3.opengl.GL30.glVertexAttribI2uiv(p0, p1);
    }

    public static void glVertexAttribI2ui(int p0, int p1, int p2) {
        com.github.lodestone.lwjgl3.opengl.GL30.glVertexAttribI2ui(p0, p1, p2);
    }

    public static void glVertexAttribI3(int p0, java.nio.IntBuffer p1) {
        com.github.lodestone.lwjgl3.opengl.GL30.glVertexAttribI3iv(p0, p1);
    }

    public static void glVertexAttribI3i(int p0, int p1, int p2, int p3) {
        com.github.lodestone.lwjgl3.opengl.GL30.glVertexAttribI3i(p0, p1, p2, p3);
    }

    public static void glVertexAttribI3u(int p0, java.nio.IntBuffer p1) {
        com.github.lodestone.lwjgl3.opengl.GL30.glVertexAttribI3uiv(p0, p1);
    }

    public static void glVertexAttribI3ui(int p0, int p1, int p2, int p3) {
        com.github.lodestone.lwjgl3.opengl.GL30.glVertexAttribI3ui(p0, p1, p2, p3);
    }

    public static void glVertexAttribI4(int p0, java.nio.ByteBuffer p1) {
        com.github.lodestone.lwjgl3.opengl.GL30.glVertexAttribI4bv(p0, p1);
    }

    public static void glVertexAttribI4(int p0, java.nio.IntBuffer p1) {
        com.github.lodestone.lwjgl3.opengl.GL30.glVertexAttribI4iv(p0, p1);
    }

    public static void glVertexAttribI4(int p0, java.nio.ShortBuffer p1) {
        com.github.lodestone.lwjgl3.opengl.GL30.glVertexAttribI4sv(p0, p1);
    }

    public static void glVertexAttribI4i(int p0, int p1, int p2, int p3, int p4) {
        com.github.lodestone.lwjgl3.opengl.GL30.glVertexAttribI4i(p0, p1, p2, p3, p4);
    }

    public static void glVertexAttribI4u(int p0, java.nio.ByteBuffer p1) {
        com.github.lodestone.lwjgl3.opengl.GL30.glVertexAttribI4ubv(p0, p1);
    }

    public static void glVertexAttribI4u(int p0, java.nio.IntBuffer p1) {
        com.github.lodestone.lwjgl3.opengl.GL30.glVertexAttribI4uiv(p0, p1);
    }

    public static void glVertexAttribI4u(int p0, java.nio.ShortBuffer p1) {
        com.github.lodestone.lwjgl3.opengl.GL30.glVertexAttribI4usv(p0, p1);
    }

    public static void glVertexAttribI4ui(int p0, int p1, int p2, int p3, int p4) {
        com.github.lodestone.lwjgl3.opengl.GL30.glVertexAttribI4ui(p0, p1, p2, p3, p4);
    }

    public static void glVertexAttribIPointer(int p0, int p1, int p2, int p3, long p4) {
        com.github.lodestone.lwjgl3.opengl.GL30.glVertexAttribIPointer(p0, p1, p2, p3, p4);
    }

    public static void glVertexAttribIPointer(int p0, int p1, int p2, int p3, java.nio.ByteBuffer p4) {
        com.github.lodestone.lwjgl3.opengl.GL30.glVertexAttribIPointer(p0, p1, p2, p3, p4);
    }

    public static void glVertexAttribIPointer(int p0, int p1, int p2, int p3, java.nio.IntBuffer p4) {
        com.github.lodestone.lwjgl3.opengl.GL30.glVertexAttribIPointer(p0, p1, p2, p3, p4);
    }

    public static void glVertexAttribIPointer(int p0, int p1, int p2, int p3, java.nio.ShortBuffer p4) {
        com.github.lodestone.lwjgl3.opengl.GL30.glVertexAttribIPointer(p0, p1, p2, p3, p4);
    }

    private GL30() {
    }
}
